repoman/pym/repoman/scanner.py

repoman: skip QA checks in manifest mode (bug 586864)
The relevent Scanner loop control logic broke in commit 4062c69dc27a
because it was relying on the return value from the Manifest module's
"check" method.
Fixes: 4062c69dc27a ("repoman: Move manifest generation to modules/commit/manifest.py")
X-Gentoo-Bug: 586864
X-Gentoo-Bug-url: https://bugs.gentoo.org/show_bug.cgi?id=586864

repoman: skip QA checks in manifest mode (bug 586864)

---

bin/chpathtool.py

Fix chpathtool.py so that it won't try to compare a byte string with an
integer in python3. This change is also compatible with python2.
X-Gentoo-Bug: 587198
X-Gentoo-Bug-url: https://bugs.gentoo.org/show_bug.cgi?id=587198

chpathtool.py: fix byte comparison logic for python3 (bug 587198)

---

pym/_emerge/depgraph.py
pym/portage/tests/resolver/soname/test_slot_conflict_reinstall.py
pym/portage/tests/resolver/test_slot_conflict_rebuild.py
pym/portage/tests/resolver/test_slot_operator_reverse_deps.py

Fix check_reverse_dependencies to ignore dependencies of parent packages
for which updates are desirable, and add required  _want_update_pkg
support for DependencyArg parents. This solves a missed llvm update by
ignoring a reverse dependency from the installed instance of clang,
since an update to a newer version of clang is desirable.
In order to cope with this change, there are 2 existing unit tests
that require larger --backtrack settings in order to succeed.
X-Gentoo-Bug: 584626
X-Gentoo-Bug-url: https://bugs.gentoo.org/show_bug.cgi?id=584626

depgraph: fix missed llvm update (bug 584626)

---

man/emerge.1
pym/_emerge/actions.py
pym/_emerge/depgraph.py
pym/_emerge/main.py
pym/portage/tests/emerge/test_simple.py

This option will cause emerge to automatically apply autounmask changes
to configuration files, and continue to execute the specified command.
If the dependency calculation is not entirely successful, then emerge
will simply abort without modifying any configuration files.
This sort of behavior can be very useful in a continuous integration
setting, where the emerge invocation might be inside of a container that
is later discarded (so there is no threat of negative consequences).
It's also safe for general use, when combined with the --ask option.
X-Gentoo-Bug: 582624
X-Gentoo-Bug-url: https://bugs.gentoo.org/show_bug.cgi?id=582624

Add emerge --autounmask-continue option (bug 582624)

---

pym/portage/metadata.py

Since commit 9abbda7d054761ae6c333d3e6d420632b9658b6d, users with
FEATURES=metadata-transfer enabled would receive a KeyError when
an existing cache entry contained \_mtime_ instead of \_md5_. Fix
it to simply overwrite the cache entry in this case.
Fixes: 9abbda7d0547 ("portage.cache: write md5 instead of mtime (bug 568934)")
X-Gentoo-Bug: 568934
X-Gentoo-Bug-url: https://bugs.gentoo.org/show_bug.cgi?id=568934

action_metadata: handle missing _md5_ key (bug 568934)

---

pym/portage/cache/flat_hash.py

Fix the _setitem method to use mkstemp in order to avoid a
race condition when multiple pid namespaces share the same
cache directory.
Reported-by: Mike Frysinger <vapier@chromium.org>
X-Chromium-Bug: 477727
X-Chromium-Bug-url: https://bugs.chromium.org/p/chromium/issues/detail?id=477727

flat_hash: use mkstemp in _setitem

---

pym/_emerge/depgraph.py
pym/portage/tests/resolver/test_runtime_cycle_merge_order.py

Previously, it was possible for _serialize_tasks to count some
dependencies of a runtime cycle as part of that cycle, leading to
sub-optimal merge order for these dependencies because they got
grouped together with the cycle in the overall merge order. Fix
it to separate these dependencies from the cycle, and merge them
earlier.
X-Gentoo-Bug: 590514
X-Gentoo-Bug-url: https://bugs.gentoo.org/show_bug.cgi?id=590514

depgraph._serialize_tasks: improve runtime cycle handling (bug 590514)

---

repoman/pym/repoman/modules/scan/depend/_depend_checks.py

X-Gentoo-bug: 591184
X-Gentoo-bug-url: https://bugs.gentoo.org/show_bug.cgi?id=591184

repoman: deduplicate dependency.syntax errors (bug 591184)

---

repoman/pym/repoman/modules/scan/depend/_depend_checks.py

Fix accounting for baddepsyntax so that it doesn't count invalid
PROPERTIES, since it's only intended to count invalid *DEPEND.
Also remove unused counts for invalid LICENSE and PROVIDE.

repoman: fix _depend_checks baddepsyntax accounting

---

pym/portage/tests/ebuild/test_ipc_daemon.py
pym/portage/util/_eventloop/EventLoop.py

EventLoop: add run_until_complete method (bug 591760)
This emulates the asyncio.AbstractEventLoop.run_until_complete(future)
interface, which will make it possible to reduce latency in situations
where it is desirable for a loop to exit at the earliest opportunity.
The most tangible benefit of this change is that it provides a
migration path to asyncio, which will allow us to rely on a standard
library instead of our own internal event loop implementation.
In order to migrate to asyncio, more work is planned:
* Migrate all internal use of the EventLoop.iteration method to the new
run_until_complete(future) method, and remove the EventLoop.iteration
method (or make it private as long as it's needed to implement
run_until_complete for older python versions).
* Implement all EventLoop …

EventLoop: add run_until_complete method (bug 591760)

---

pym/portage/package/ebuild/config.py

X-Gentoo-bug: 584328
X-Gentoo-bug-url: https://bugs.gentoo.org/show_bug.cgi?id=584328

config.environ: handle missing ctypes for check_locale (bug 584328)

---

pym/portage/news.py
pym/portage/tests/news/test_NewsItem.py

Validate Display-If-Installed with EAPI 0 or 5.
Add support for trailing wildcard matching for Display-If-Profile.
X-Gentoo-bug: 577372
X-Gentoo-bug-url: https://bugs.gentoo.org/show_bug.cgi?id=577372

news: Support News-Item-Format 2.0

---

pym/portage/cache/fs_template.py

Fixes 5652bc88514b ("flat_hash: use mkstemp in _setitem)
X-Gentoo-Bug: 594358
X-Gentoo-Bug-URL: https://bugs.gentoo.org/594358

cache.fs_template: set 0o644 defaut perms

---

pym/portage/package/ebuild/doebuild.py
pym/portage/package/ebuild/prepare_build_dirs.py

Fixes: a41c0f8b9081 ("doebuild: Support finding lib* for ccache/distcc/icecc masquerade dir")
X-Gentoo-Bug: 594982
X-Gentoo-Bug-URL: https://bugs.gentoo.org/594982

doebuild_environment: disable ccache/distcc/icecc when necessary (bug 594982)

---

bin/ebuild.sh
bin/phase-functions.sh

This will avoid undesirable interactions with the python sitedir,
as reported in bug 574002. Since the temporary HOME is not guaranteed
to exist for some phases, use PORTAGE_PYM_PATH as a fallback. Also,
use PORTAGE_PYM_PATH inside __dyn_clean, since HOME is removed there.
X-Gentoo-Bug: 595028
X-Gentoo-Bug-URL: https://bugs.gentoo.org/595028
@floppym

ebuild.sh: start phases in temporary HOME if available (bug 595028)

---

.travis.yml
README
setup.py

The libc bindings are optional, since ctypes is used as a fallback when
they are not available. The libc bindings do not support cross-
compilation, therefore it is useful to be able to build them
conditionally. This patch adds an option to enable them conditionally,
which the ebuild can use by adding the following code to the
python_prepare_all function:
if use native-extensions; then
printf "[build_ext]\nportage-ext-modules=true" >> \
setup.cfg || die
fi
X-Gentoo-Bug: 594744
X-Gentoo-Bug-URL: https://bugs.gentoo.org/594744

setup.py: enable libc bindings optionally (bug 594744)

---

bin/emerge-webrsync
man/make.conf.5

emerge-webrsync: use gkeys to verify OpenPGP signatures (bug 597918)
Use gkeys to verify OpenPGP signatures by default. Refresh the gentoo
snapshot signing key before signature verification, in order to ensure
that the latest revocation data is available. Add an --insecure option
which disables signature verification. Warn about man-in-the-middle
attacks when the --insecure option is used. Deprecate the pre-existing
webrsync-gpg feature since it requires manual gpg configuration.
X-Gentoo-Bug: 597918
X-Gentoo-Bug-URL: https://bugs.gentoo.org/show_bug.cgi?id=597918
Acked-by: Brian Dolbec <dolsen@gentoo.org>

emerge-webrsync: use gkeys to verify gpg signatures (bug 597918)

---

pym/_emerge/depgraph.py
pym/portage/dep/dep_check.py

Constrain _expand_new_virtuals output in order to avoid incorrect
re-ordering of || deps in the dep_zapdeps function, as reported in
bug 597752.
The incorrect dep_zapdeps behavior involved a problem in the
construction of the _dep_choice.cp_map dictionary inside the
dep_zapdeps function, with this input:
|| ( dev-java/icedtea-bin:8 =virtual/jdk-1.8.0-r3 >=virtual/jdk-1.5 )
( dev-java/icedtea-bin:7 =virtual/jdk-1.7.0-r2 >=virtual/jdk-1.5 )
The cp_map for virtual/jdk-1.7.0-r2 erroneously contained
virtual/jdk-1.8.0-r3 because that was the highest virtual/jdk matched
by the >=virtual/jdk-1.5 atom. This patch removes the >=virtual/jdk-1.5
atom from the _expand_new_virtuals output, in order to avoid triggering
the erroneous dep_zapdeps behavior. The >=virtual/jdk-1.5 atom is not
completely …

_expand_new_virtuals: constrain output for dep_zapdeps (bug 597752)

---

pym/portage/sync/modules/git/git.py

This reverts commit 84413bb1dd9df322568ce25efc5b7854a43d03c7, and all of the related commits that followed:
d075422a89 sync: always pass -q --unmerged to git-update-index
f77fcd6b0b [sync] Run `git update-index --refresh` when doing shallow pulls
f5d258656d GitSync.update: handle git rev-list failure (bug 594822)
55aef9bf29 GitSync.update: use git reset --merge instead of --hard (bug 552814)
Shallow fetch is not a practical default at this time, given performance
issues introduced by `git update-index` and `git prune` (see bug 599008).
X-Gentoo-Bug: 552814
X-Gentoo-Bug-URL: https://bugs.gentoo.org/show_bug.cgi?id=552814

Revert "GitSync.update: respect sync-depth (bug 552814)"

---

pym/portage/dbapi/vartree.py

Before a package is merged, prune any libraries from the registry that no
longer exist on disk, in case they have been manually removed. This has
to be done prior to merge, since after merge it is non-trivial to
distinguish these files from files that have just been merged.
The performance impact of this change is negligible. It uses one lstat
call for each preserved library, and the plib_registry.store() call does
not actually write to disk unless it has found something to remove from
the registry.
X-Gentoo-Bug: 599240
X-Gentoo-Bug-URL: https://bugs.gentoo.org/show_bug.cgi?id=599240

preserve-libs: handle manually removed libraries better (bug 599240)

---

pym/portage/dep/__init__.py
pym/portage/dep/dep_check.py

When selecting packages to determine which choices have upgrades
or downgrades relative to other choices, make the package selections
internally consistent by choosing a package that satisfies all atoms
in the choice which match a package in the same slot.
Also, fix the Atom.match() method to handle _pkg_str instances,
since dep_zapdeps can pass in _pkg_str instances instead of Package
instances.
X-Gentoo-Bug: 600346
X-Gentoo-Bug-URL: https://bugs.gentoo.org/show_bug.cgi?id=600346

dep_zapdeps: make package selections internally consistent (bug 600346)

---

man/portage.5
pym/portage/manifest.py
pym/portage/package/ebuild/digestcheck.py
pym/portage/repository/config.py

This setting determines whether digests are checked for files declared
in the Manifest with MISC type (includes ChangeLog and metadata.xml
files). Defaults to true.
The current GLEP 60 draft specifies that non-strict handling of MISC
digests should be supported.
X-Gentoo-Bug: 600128
X-Gentoo-Bug-URL: https://bugs.gentoo.org/show_bug.cgi?id=600128

repos.conf: support strict-misc-digests attribute (bug 600128)

---

bin/phase-helpers.sh

Since txz unpack support was added in commit
daa65a336102050396482f08c77524fe99e48c9f, it has been non-functional,
as follows:
phase-helpers.sh: line 521: ___eapi_supports_txz: command not found
unpack portage-2.3.2.txz: file format not recognized. Ignoring.
Fixes: daa65a336102 ("Add tentative EAPI6 .txz unpack support")
X-Gentoo-Bug: 600660
X-Gentoo-Bug-URL: https://bugs.gentoo.org/show_bug.cgi?id=600660

unpack: fix txz unpack support (bug 600660)

---

pym/portage/package/ebuild/doebuild.py

Allow ebuilds to install files with portage group permissions, as
a means to restrict access to package manager resources.
X-Gentoo-Bug: 600804
X-Gentoo-Bug-URL: https://bugs.gentoo.org/show_bug.cgi?id=600804

_post_src_install_uid_fix: allow files with portage group permission (bug 600804)

---

bin/ebuild
pym/portage/package/ebuild/config.py

Ensure that config adjustments are applied to all relevant
config instances, in order to prevent inconsistencies like
the one that triggered bug 601466.
X-Gentoo-Bug: 601466
X-Gentoo-Bug-URL: https://bugs.gentoo.org/show_bug.cgi?id=601466

bin/ebuild: fix EBUILD_FORCE_TEST / RESTRICT interaction (bug 601466)

---

pym/portage/dbapi/bintree.py
pym/portage/versions.py

Fix the binarytree._read_metadata method to return empty strings for
undefined metadata values, in order to fulfill a contract with the
_pkg_str class. This prevents an AttributeError triggered by old
binary packages which have undefined repository metadata, as reported
in bug 603826.
X-Gentoo-bug: 603826
X-Gentoo-bug-url: https://bugs.gentoo.org/603826

binarytree._read_metadata: return empty strings for undefined values (bug 603826)

---

pym/_emerge/depgraph.py

When an update has been skipped, clearly display both the selected and
skipped packages.
X-Gentoo-bug: 602854
X-Gentoo-bug-url: https://bugs.gentoo.org/602854

depgraph: clarify "update has been skipped" message (bug 602854)

---

bin/portageq

When the email address of a maintainer contains unescaped
regex-special characters (such as '+'), the maintainer-email match may
return undesirable results.
Add a command line option '--no-regex' to use re.escape() with list
comprehension on maintainer emails when constructing the matcher
regex. This way, an exact string match can be made rather than a regex
match.
X-Gentoo-bug: 604164
X-Gentoo-bug-url: https://bugs.gentoo.org/604164

portageq: allow disabling regex matching of maintainer emails #604164

---

repoman/pym/repoman/qa_data.py

There are still a few packages left that put linguist-tools, linuxtv-dvb-headers, and os-headers to RDEPEND.
https://qa-reports.gentoo.org/output/genrdeps/rindex/dev-qt/linguist-tools:
```
app-text/cutemarked-0.11.3
```
https://qa-reports.gentoo.org/output/genrdeps/rindex/virtual/linuxtv-dvb-headers:
```
media-libs/libdvb-0.5.5.1-r3
media-tv/mythtv-0.27.5_p20151025:dvb
media-tv/mythtv-0.27.6_p20160318:dvb
media-tv/mythtv-0.27_p20140321:dvb
media-tv/mythtv-0.28:dvb
media-video/mplayer-1.2-r2:dvb
media-video/mplayer-1.2.1:dvb
media-video/mplayer-1.2_pre20150214-r1:dvb
media-video/mplayer-1.3.0:dvb
media-video/mplayer-9999:dvb
media-video/mpv-0.18.0-r1:dvb
media-video/mpv-0.22.0-r1:dvb
media-video/mpv-0.23.0:dvb
media-video/mpv-0.9.2-r1:dvb
media-video/mpv-9999:dvb
``` …

Add 3 more packages to RDEPEND.suspect to prevent further abuse

---

pym/portage/util/env_update.py

prefix-standalone has a glibc installed by portage with ldconfig
under EROOT/sbin.  It should be called during env-update.
For prefix-rpath, host glibc is used and env-update should not
care about ldconfig.  In this case, no ldconfig is in EROOT/sbin
and ldconfig is skipped.
X-Gentoo-Bug: 532100
X-Gentoo-Bug-URL: https://bugs.gentoo.org/show_bug.cgi?id=532100

env-update should call ldconfig if found in EROOT

---

bin/socks5-server.py

Use the idna codec to decode the destination address that is read
from the client. This fixes a "TypeError: must be str, not bytes"
exception raised from getaddrinfo with Python 3.4.5.
X-Gentoo-Bug: 604474
X-Gentoo-Bug-URL: https://bugs.gentoo.org/show_bug.cgi?id=604474

bin/socks5-server.py: convert address from bytes to str (bug 604474)

---

pym/_emerge/depgraph.py

Fixes: 11467fc64099 ("depgraph: soname dependency resolution (bug 282639)")
X-Gentoo-Bug: 606464
X-Gentoo-Bug-URL: https://bugs.gentoo.org/show_bug.cgi?id=606464

depgraph: fix 'SonameAtom' object is not subscriptable (bug 606464)

---

pym/portage/util/env_update.py

Since commit 1bc49bead14ddd31c94921fe9c3d1972f0737056, env_update
would raise the following exception with crossdev configurations
when ${CHOST}-ldconfig is not available:
TypeError: access: can't specify None for path argument
Fixes: 1bc49bead14d ("env-update: call ldconfig if found in EROOT")
X-Gentoo-Bug: 606832
X-Gentoo-Bug-URL: https://bugs.gentoo.org/show_bug.cgi?id=606832

env-update: skip os.access call when ldconfig is None (bug 606832)

---

pym/_emerge/actions.py
pym/portage/emaint/modules/sync/sync.py

Handle the tuple returned from SyncRepos._sync since commit
f143e58dd3fd80ab67121e7a62e8cf47151d3907. Also fix the
SyncRepos._sync method to prevent corruption of the returncode
variable.
Fixes: f143e58dd3fd ("emaint: exit with non-zero status code when module fails (bug 567478)")
X-Gentoo-Bug: 606588
X-Gentoo-Bug-URL: https://bugs.gentoo.org/show_bug.cgi?id=606588

action_sync: fix TypeError: 'int' object is not subscriptable (bug 606588)

---

pym/portage/process.py

Make spawn force instantiation of portage.data.userpriv_groups in the
main process, in order to avoid redundant instantiation in child
processes. This mitigates the impact of "Bad file descriptor" errors
reported in bug 582098, by avoiding redundant instantiation of
userpriv_groups in child processes. It may even solve the problem
completely, if the "Bad file descriptor" errors are triggered by
interactions between garbage collection and the file descriptor
operations performed in the _exec function by the _setup_pipes call.
X-Gentoo-Bug: 582098
X-Gentoo-Bug-URL: https://bugs.gentoo.org/show_bug.cgi?id=582098

spawn: instantiate userpriv_groups before fork (bug 582098)

---

pym/portage/tests/sync/test_sync_local.py

The missing pym/portage/tests/sync/__test__.py file is the
reason that travis did not trigger the TypeError that was
fixed in commit 23f239134b0290cbe0435e13d8f1b1757c6d8524.

tests: add missing __test__.py files

---

pym/portage/emaint/modules/sync/sync.py
pym/portage/sync/controller.py

This fixes the following DeprecationWarning with Python 3.6:
pym/portage/sync/controller.py:117: DeprecationWarning: 'async' and 'await' will become reserved keywords in Python 3.7
def async(self, emerge_config=None, repo=None, master_hooks=True):
X-Gentoo-Bug: 607922
X-Gentoo-Bug-URL: https://bugs.gentoo.org/show_bug.cgi?id=607922

SyncManager: rename async method to sync_async (bug 607922)

---

pym/portage/util/_async/PopenProcess.py

Override the _set_returncode method to set the Popen.returncode
attribute, in order to suppress Python 3.6 ResourceWarnings which
erroneously report that the subprocess is still running.
X-Gentoo-Bug: 608594
X-Gentoo-Bug-URL: https://bugs.gentoo.org/show_bug.cgi?id=608594

PopenProcess: suppress ResourceWarning subprocess "still running" (bug 608594)

---

repoman/pym/repoman/modules/vcs/git/status.py

Use repoman_popen context manager, in order to suppress Python 3.6
ResourceWarnings which report that the subprocess is still running.
X-Gentoo-Bug: 608594
X-Gentoo-Bug-URL: https://bugs.gentoo.org/show_bug.cgi?id=608594

Status.check: suppress ResourceWarning subprocess "still running" (bug 608594)

---

repoman/man/repoman.1
repoman/pym/repoman/modules/scan/fetch/fetches.py
repoman/pym/repoman/qa_data.py

This checks for files with zero size in filesdir. The QA script at
https://qa-reports.gentoo.org/output/find-binary-files.txt reports a
couple of them which at least in part are blunders.

repoman: Check for empty files in filesdir.

---

pym/_emerge/actions.py
pym/portage/emaint/modules/sync/sync.py

Emerge will only display messages if --quiet is not set.
The word 'emaint' has been removed from two messages to avoid confusion.

emerge: make emerge --sync print messages from SyncRepos.auto_sync()

---

pym/_emerge/actions.py

The auto-sync attribute is more useful for emerge --sync with zero repo arguments. When specific repo arguments are given to emerge --sync, it makes sense to sync those repos regardless of the auto-sync attribute.
X-Gentoo-Bug: 610328
X-Gentoo-Bug-URL: https://bugs.gentoo.org/show_bug.cgi?id=610328

emerge: sync given repos even if auto-sync is false (bug 610328)

---

pym/portage/util/compression_probe.py

X-Gentoo-Bug: 609462
X-Gentoo-Bug-Url: https://bugs.gentoo.org/show_bug.cgi?id=609462

compression_probe: support zstandard (zstd) decompression (bug 609462)

---

man/portage.5
pym/portage/repository/config.py
pym/portage/sync/modules/git/__init__.py
pym/portage/sync/modules/git/git.py

Since sync-depth actually controls clone depth, rename it
to clone-depth, and show a warning message when the sync-depth
option has been specified:
UserWarning: repos.conf: sync-depth is deprecated, use clone-depth instead
This makes it feasible to change the meaning of sync-depth in
the future (it could be used to control git pull depth).
X-Gentoo-Bug: 552814
X-Gentoo-Bug-URL: https://bugs.gentoo.org/show_bug.cgi?id=552814

repos.conf: rename sync-depth option to clone-depth

---

bin/etc-update

Don't try to use an interactive editor to obtain the difference between
files.  Fall back to plain `diff -q` in this case.
X-Gentoo-Bug: 544440
X-Gentoo-Bug-URL: https://bugs.gentoo.org/show_bug.cgi?id=544440

etc-update: fix hang when using_editor is set, bug #544440

---

pym/portage/util/__init__.py

Support -* in order to make it easier to create profiles for
minimal systems (especially those built entirely from binary
packages).
X-Gentoo-Bug: 610670
X-Gentoo-Bug-URL: https://bugs.gentoo.org/show_bug.cgi?id=610670

grabfile_package: support -* in profile "packages" files (bug 610670)

---

pym/portage/sync/modules/git/__init__.py
pym/portage/sync/modules/git/git.py

The CheckGitConfig._check_depth method must not set the sync_depth
attribute, or else it will trigger "sync-depth is deprecated" messages.
Fixes: b3f6297a791a ("repos.conf: rename sync-depth option to clone-depth")
X-Gentoo-Bug: 610708
X-Gentoo-Bug-Url: https://bugs.gentoo.org/show_bug.cgi?id=610708

GitSync: fix spurious "sync-depth is deprecated" messages (bug 610708)

---

man/emerge.1
pym/_emerge/create_depgraph_params.py
pym/_emerge/depgraph.py
pym/_emerge/main.py
pym/portage/tests/resolver/ResolverPlayground.py
pym/portage/tests/resolver/test_bdeps.py

It's useful to automatically enable --with-bdeps so that @world updates
will update all packages that are not eligible for removal by
emerge --depclean. However, many users of binary packages do not want
unnecessary build time dependencies installed, therefore do not
auto-enable --with-bdeps for installation actions when the --usepkg
option is enabled.
A new --with-bdeps-auto=<y|n> option is provided, making it possible to
enable or disable the program logic that causes --with-bdeps to be
automatically enabled. Use --with-bdeps-auto=n to prevent --with-bdeps
from being automatically enabled for installation actions. This is useful
for some rare cases in which --with-bdeps triggers unsolvable dependency
conflicts (and putting --with-bdeps=n in EMERGE_DEFAULT_OPTS would cause
undesirable …

emerge: auto-enable --with-bdeps if --usepkg is not enabled (bug 598444)

---

pym/portage/dep/__init__.py

Since it's possible for a URI to contain parenthesis, only call
missing_white_space_check for tokens that fail to validate with
token_class. The missing_white_space_check function only serves
to clarify exception messages, so it must not be allowed to
reject valid tokens.
X-Gentoo-Bug: 611838
X-Gentoo-Bug-Url: https://bugs.gentoo.org/show_bug.cgi?id=611838

use_reduce: reserve missing_white_space_check for invalid tokens (bug 611838)

---

pym/_emerge/depgraph.py
pym/portage/tests/resolver/test_slot_operator_runtime_pkg_mask.py

In some cases the backtracking runtime package mask can interact badly
with slot operator rebuilds, preventing a solution from being found.
This patch fixes the problem, which is demonstrated by the included
unit test.
X-Gentoo-bug: 612094
X-Gentoo-bug-url: https://bugs.gentoo.org/show_bug.cgi?id=612094

depgraph: fix runtime package mask interaction with slot operator rebuilds (bug 612094)

---

pym/portage/package/ebuild/config.py

Fix setcpv to correctly regenerate USE when the IUSE differs from
the previous setcpv call. Changes in IUSE affect USE_EXPAND
wildcard expansion in the regenerate method.
X-Gentoo-bug: 611896
X-Gentoo-bug-url: https://bugs.gentoo.org/show_bug.cgi?id=611896

config.setcpv: fix handling of IUSE changes (bug 611896)

---

pym/portage/tests/util/file_copy/test_copyfile.py
pym/portage/util/file_copy/__init__.py
pym/portage/util/movefile.py
setup.py
src/portage_util_file_copy_reflink_linux.c

movefile: support in-kernel file copying on Linux (bug 607868)
Perform in-kernel file copying when possible, and also support
reflinks and sparse files. If the optimized implementation
fails at runtime, gracefully fallback to a plain read/write
loop.
Compile-time and run-time fallbacks are implemented, so that
any incompatiblities will be handled gracefully. For example,
if the code is compiled on a system that supports the
copy_file_range syscall, but at run-time an older kernel that
does not support this syscall is detected, it will be handled
gracefully. There are similar fallbacks for lack of lseek
SEEK_DATA and sendfile support.
X-Gentoo-Bug: 607868
X-Gentoo-Bug-Url: https://bugs.gentoo.org/show_bug.cgi?id=607868

movefile: support in-kernel file copying on Linux (bug 607868)

---

pym/_emerge/depgraph.py
pym/portage/tests/resolver/test_slot_operator_exclusive_slots.py

Fix check_reverse_dependencies to ignore dependencies of parent packages
that could be uninstalled in order to solve a blocker conflict. This case
is similar to the one from bug 584626, except that the relevant parent
package is in an older slot which is blocked by a newer slot. In this
case, the _upgrade_available method returns False, because the package
in the older slot is the highest version version available for its
slot. Therefore, a new _in_blocker_conflict method is needed to detect
parent packages that cold be uninstalled. The included unit test fails
without this fix.
Since the _in_blocker_conflict method requires information that is
collected by the _validate_blockers method, the _validate_blockers
method now has to be called before the _process_slot_conflict and …

depgraph: fix slot operator rebuild for llvm:0 to llvm:4 upgrade (bug 612772)

---

pym/_emerge/depgraph.py
pym/portage/tests/resolver/test_slot_operator_exclusive_slots.py
pym/portage/tests/util/test_digraph.py
pym/portage/util/digraph.py

Fix check_reverse_dependencies to ignore direct circular dependencies,
since these dependencies tend to prevent updates of packages. This
solves a missed update from llvm:0 to llvm:4 when clang is not in the
world file, as demonstrated by the included test case.
X-Gentoo-bug: 612874
X-Gentoo-bug-url: https://bugs.gentoo.org/show_bug.cgi?id=612874

depgraph: avoid missed update with slot operator and circ dep (bug 612874)

---

pym/_emerge/depgraph.py
pym/portage/tests/resolver/test_binary_pkg_ebuild_visibility.py

Fix the --use-ebuild-visibility option to reject binary packages for
which ebuilds are either masked or unavailable. The included test case
fails with out this fix.
X-Gentoo-bug: 612960
X-Gentoo-bug-url: https://bugs.gentoo.org/show_bug.cgi?id=612960

emerge: fix --use-ebuild-visibility to reject binary packages (bug 612960)

---

pym/_emerge/depgraph.py
pym/portage/tests/resolver/test_binary_pkg_ebuild_visibility.py

Fix emerge --usepkg to use a binary package when the corresponding
ebuild is not available (and --use-ebuild-visibility is not enabled),
in cases when no other package is available to satisfy the dependency.
This reverts an unintended behavior change from commit
e309323f156528a8a79a1f755e1326e8880346b7.
Fixes: e309323f1565 ("emerge: fix --use-ebuild-visibility to reject binary packages (bug 612960)")
X-Gentoo-bug: 613360
X-Gentoo-bug-url: https://bugs.gentoo.org/show_bug.cgi?id=613360

emerge: fix --usepkg when ebuild is not available (bug 613360)

---

bin/emirrordist
pym/_emerge/PollScheduler.py
pym/_emerge/Scheduler.py
pym/portage/_emirrordist/FetchIterator.py
pym/portage/_emirrordist/MirrorDistTask.py
pym/portage/tests/util/eventloop/test_call_soon_fifo.py
pym/portage/util/_async/AsyncScheduler.py
pym/portage/util/_async/SchedulerInterface.py
pym/portage/util/_eventloop/EventLoop.py

Since asyncio.AbstractEventLoop has no equivalent to the idle
callbacks implemented by the EventLoop.idle_add method, it is
necessary to implement the AbstractEventLoop.call_soon and
call_soon_threadsafe methods, so that idle_add usage can
eventually be eliminated.
X-Gentoo-bug: 591760
X-Gentoo-bug-url: https://bugs.gentoo.org/show_bug.cgi?id=591760

 EventLoop: implement call_soon for asyncio compat (bug 591760)

---

pym/portage/tests/ebuild/test_ipc_daemon.py
pym/portage/tests/util/eventloop/test_call_soon_fifo.py
pym/portage/tests/util/futures/test_done_callback.py
pym/portage/util/_async/SchedulerInterface.py
pym/portage/util/_eventloop/EventLoop.py
pym/portage/util/futures/futures.py

Implement the add_done_callback and remove_done_callback methods, since
they are required in order to make further progress toward asyncio
compatibility.
Also implement the AbstractEventLoop create_future method for the
EventLoop class, so that it returns an instance of _EventLoopFuture.
EventLoop currently does not implement some of the
asyncio.AbstractEventLoop methods that asyncio.Future requires for
its add_done_callback implementation, and create_future conveniently
solves this problem.
X-Gentoo-bug: 591760
X-Gentoo-bug-url: https://bugs.gentoo.org/show_bug.cgi?id=591760

Future: implement add_done_callback for asyncio compat (bug 591760)

---

pym/_emerge/SpawnProcess.py
pym/_emerge/SubProcess.py

Fix SpawnProcess._pipe_logger_exit to wait for process exit status
asynchronously, in order to avoid event loop recursion. This is
required for asyncio compatibility, and also protects emerge from
exceeding the maximum recursion depth limit like in bug 402335.
X-Gentoo-bug: 613990
X-Gentoo-bug-url: https://bugs.gentoo.org/show_bug.cgi?id=613990

SpawnProcess: fix event loop recursion in _pipe_logger_exit (bug 613990)

---

pym/_emerge/actions.py
pym/portage/dbapi/bintree.py

Fix action_build to populate binarytree instances with remote package
metadata following config reload, using a new getbinpkg_refresh=False
parameter to prevent redundant fetching of remote package metadata.
X-Gentoo-bug: 614474
X-Gentoo-bug-url: https://bugs.gentoo.org/show_bug.cgi?id=614474
Fixes: e2d88ef3ff59 ("Add emerge --autounmask-continue option (bug 582624)")

emerge: fix --autounmask-continue to work with --getbinpkg (bug 614474)

---

pym/_emerge/EbuildBuild.py
pym/_emerge/Scheduler.py
pym/portage/package/ebuild/_spawn_nofetch.py

X-Gentoo-bug: 614116
X-Gentoo-bug-url: https://bugs.gentoo.org/show_bug.cgi?id=614116

EbuildBuild: fix event loop recursion in _fetchonly_exit (bug 614116)

---

pym/_emerge/actions.py

If settings["PORTAGE_NICENESS"] is undefined, portage crashes with a
KeyError when trying to print the error.
Signed-off-by: Peter Foley <pefoley2@pefoley.com>
X-Gentoo-bug: 615328
X-Gentoo-bug-url: https://bugs.gentoo.org/show_bug.cgi?id=615328

Prevent crash if os.nice() fails

---

pym/_emerge/depgraph.py
pym/portage/tests/util/test_digraph.py
pym/portage/util/digraph.py

Sometimes _complete_graph calls _slot_operator_update_probe, which
sometimes calls _in_blocker_conflict. This case occurs infrequently,
so call _validate_blockers only if needed.
Fixes: a83bb83909c5 ("depgraph: trigger slot operator rebuilds via _complete_graph (bug 614390)")
X-Gentoo-bug: 615982
X-Gentoo-bug-url: https://bugs.gentoo.org/show_bug.cgi?id=615982

depgraph._in_blocker_conflict: call _validate_blockers if needed (bug 615982)

---

setup.py
src/portage_util_file_copy_reflink_linux.c

The loff_t type is a GNU extension, so use the portable off_t
type instead. Also, enable Large File Support macros in setup.py,
for 64-bit offsets.
Reported-by: Patrick Steinhardt <ps@pks.im>
X-Gentoo-bug: 617778
X-Gentoo-bug-url: https://bugs.gentoo.org/show_bug.cgi?id=617778
I'm thinking this is going to be more portable that the -D_GNU_SOURCE approach from https://github.com/gentoo/portage/pull/159.
@pks-t @blueness

file_copy: replace loff_t with off_t for portability (bug 617778)

---

src/portage_util_file_copy_reflink_linux.c

Fix the lseek offset for the plain read/write loop to account
for buffered data that has not been written to to the output
file yet (due to previous interruption by EINTR). This code
only affects Linux 2.6.32 and earlier (newer kernels use
copy_file_range or sendfile).
X-Gentoo-bug: 618086
X-Gentoo-bug-url: https://bugs.gentoo.org/show_bug.cgi?id=618086

file_copy: fix lseek offset after EINTR (bug 618086)

---

man/emerge.1
pym/_emerge/depgraph.py
pym/_emerge/main.py
pym/portage/tests/resolver/test_autounmask.py
pym/portage/tests/resolver/test_autounmask_use_breakage.py
pym/portage/tests/resolver/test_slot_conflict_unsatisfied_deep_deps.py

emerge: terminate backtracking early for autounmask changes (bug 615680)
Since autounmask changes are a strong indicator that backtracking
will ultimately fail to produce a solution, terminate early for
autounmask changes, and add a --autounmask-backtrack=<y|n> option
to modify this behavior. The --autounmask-continue option implies
--autounmask-backtrack=y behavior, for backward compatibility.
When backtracking terminates early, the following warning message
is displayed after the autounmask change(s):
* In order to avoid wasting time, backtracking has terminated early
* due to the above autounmask change(s). The --autounmask-backtrack=y
* option can be used to force further backtracking, but there is no
* guarantee that it will produce a solution.
With this change, five of the existing …

emerge: terminate backtracking early for autounmask changes (bug 615680)

---

man/emerge.1
pym/_emerge/depgraph.py
pym/_emerge/main.py
pym/portage/tests/resolver/test_onlydeps_minimal.py

Add --onlydeps-with-rdeps=n option in order to omit pure
run-time dependencies with --onlydeps. The dependencies
that get pulled in are those that are necessary for the
equivalent --buildpkgonly command to succeed. The default
--onlydeps behavior remains unchanged.
X-Gentoo-bug: 294719
X-Gentoo-bug-url: https://bugs.gentoo.org/show_bug.cgi?id=294719

emerge: add --onlydeps-with-rdeps=<y|n> option (bug 294719)

---

pym/_emerge/actions.py
pym/portage/tests/emerge/test_simple.py

In order to avoid possible confusion when the user has specified
--autounmask-continue and EMERGE_DEFAULT_OPTS contains
--autounmask=n, display a warning message as follows:
```
* --autounmask-continue has been disabled by --autounmask=n
```
X-Gentoo-bug: 619612
X-Gentoo-bug-url: https://bugs.gentoo.org/show_bug.cgi?id=619612

emerge: warn for --autounmask-continue with --autounmask=n (bug 619612)

---

pym/_emerge/depgraph.py

With FEATURES=binpkg-multi-instance, it is normal to have some
unused binary packages, so don't warn if the selected package
is the latest version and the most recent build.
X-Gentoo-bug: 619620
X-Gentoo-bug-url: https://bugs.gentoo.org/show_bug.cgi?id=619620

depgraph: account for binpkg-multi-instance in unused warning (bug 619620)

---

man/portage.5

The -* wildcard has been supported since portage-2.3.4, but it was
not explicitly documented.
X-Gentoo-Bug: 610670
X-Gentoo-Bug-URL: https://bugs.gentoo.org/show_bug.cgi?id=610670

man/portage.5: document -* in profile "packages" files (bug 610670)

---

pym/_emerge/depgraph.py
pym/portage/tests/resolver/test_autounmask_binpkg_use.py

When there are autounmask USE changes, avoid unnecessary rebuilds
by accepting binary packages that were rejected due to the preexisting
USE configuration. This reuses the prune_rebuilds backtracker support
which was added for bug 439688.
X-Gentoo-bug: 619626
X-Gentoo-bug-url: https://bugs.gentoo.org/show_bug.cgi?id=619626

depgraph: prune unnecessary rebuilds for --autounmask-continue (bug 619626)

---

pym/portage/dbapi/bintree.py
pym/portage/util/_urlopen.py

When https certificate and hostname verification is enabled for
stdlib http clients (PEP 476), use python for If-Modified-Since
header support. When python lacks PEP 476 support, continue to
use FETCHCOMMAND for https certificate and hostname verification
(see security bug 469888).
X-Gentoo-bug: 625246
X-Gentoo-bug-url: https://bugs.gentoo.org/show_bug.cgi?id=625246

emerge --getbinpkg: https support for If-Modified-Since

---

bin/install-qa-check.d/80multilib-strict

Disable recursion into subdirectories, in order to avoid false-positives.
The MULTILIB_STRICT_EXEMPT variable only served to filter false-positives
that were triggered by recursion, so it will no longer be needed.
X-Gentoo-bug: 424423
X-Gentoo-bug-url: https://bugs.gentoo.org/show_bug.cgi?id=424423

multilib-strict: disable recursion into subdirectories (bug 424423)

---

bin/phase-helpers.sh

Combine the patch basenames from all matched directories into a
list, and apply them in POSIX sorted order.  This allows patches in
more-specific directories to override patches of the same basename found
in less-specific directories. An empty patch (or /dev/null symlink)
negates a patch with the same basename found in a less-specific
directory.
This behavior is much more flexible and intuitive than the previous one,
while remaining backward-compatible to some extent.
NOTE: The implementation uses an associative array, which requires bash
version 4 or later.
X-Gentoo-bug: 608880
X-Gentoo-bug-url: https://bugs.gentoo.org/608880

eapply_user: combine sort for all dirs (bug 608880)

---

man/emerge.1
pym/_emerge/depgraph.py
pym/_emerge/main.py
pym/portage/tests/resolver/test_autounmask_keep_keywords.py

The option prevents --autounmask from making changes to
package.accept_keywords. This option does not imply
--autounmask-keep-masks, so --autounmask is still allowed
to create package.unmask changes unless the
--autounmask-keep-masks is also specified.
X-Gentoo-bug: 622480
X-Gentoo-bug-url: https://bugs.gentoo.org/622480

emerge: add --autounmask-keep-keywords option (bug 622480)

---

bin/quickpkg

Revert accidental changes to the "protect" function's return value
that were mixed in with changes to the "quickpkg_atom" function's
return value.
Fixes: cff2c0149142 ("Support different compressors for binary packages")
X-Gentoo-bug: 628010
X-Gentoo-bug-url: https://bugs.gentoo.org/628010

quickpkg: revert accidental changes to "protect" function (bug 628010)

---

bin/quickpkg

Revert premature return from the quickpkg_atom function for atoms
that match multiple slots. This fixes it to create packages for
all matched slots, rather than just the lowest version.
Fixes: cff2c0149142 ("Support different compressors for binary packages")
X-Gentoo-bug: 628060
X-Gentoo-bug-url: https://bugs.gentoo.org/628060

quickpkg: revert premature return from quickpkg_atom (bug 628060)

---

pym/portage/util/digraph.py

It's more likely that a higher valued priority will not be
ignored, therefore search in descending order.
@trofi

digraph: search for relevant priority in descending order

---

pym/portage/package/ebuild/_config/special_env_vars.py

DOCS is used by default_src_install.
X-Gentoo-bug: 627106
X-Gentoo-bug-url: https://bugs.gentoo.org/627106

config/env_blacklist: add DOCS (bug 627106)

---

pym/_emerge/AsynchronousLock.py
pym/portage/tests/locks/test_asynchronous_lock.py

Python 3.7 does not support thread-less builds.
Reported-by: Arfrever Frehtes Taifersar Arahesis <Arfrever@Apache.Org>
See: https://bugs.python.org/issue31370
X-Gentoo-bug: 630730
X-Gentoo-bug-url: https://bugs.gentoo.org/630730

AsynchronousLock: allow missing dummy_threading for Python 3.7

---

bin/postinst-qa-check.d/50gnome2-utils
bin/postinst-qa-check.d/50xdg-utils

Use a separate all_files array to accumulate the results
from all loops, so that [[ ${files[@]} ]] only checks for
files found during the current loop.

postinst-qa-check.d: fix [[ ${files[@]} ]] logic in for loops

---

pym/_emerge/depgraph.py

In order for the eliminate_pkg loop to produce deterministic results,
the order of the pkgs list must not be random. Prefer to eliminate
installed packages first, in case rebuilds are needed, and also sort
in ascending order so that older versions are eliminated first.
X-Gentoo-bug: 631894
X-Gentoo-bug-url: https://bugs.gentoo.org/631894
@danielrobbins

depgraph: make _minimize_children deterministic (bug 631894)

---

pym/_emerge/depgraph.py
pym/portage/tests/resolver/test_slot_conflict_update.py

When the slot conflict solver decides that it is "forced"
to choose a particular package, recursively force the
dependencies as well. Prior to this fix, substitution of
`@world` in the arguments for SlotConflictMaskUpdateTestCase
caused the test to fail because the solver removed
boost-build-1.53.0 from the graph event though it had
added the parent boost-1.53.0 package to the "forced"
set.
X-Gentoo-bug: 632210
X-Gentoo-bug-url: https://bugs.gentoo.org/632210

_solve_..slot_conflicts: make "forced" set recursive (bug 632210)

---

pym/_emerge/depgraph.py
pym/portage/tests/resolver/test_autounmask_use_backtrack.py

Only backtrack if changes break a USE dependency. Prior
to this fix, the included test case succeeded only with
a --backtrack setting of 3 or more, but now it succeeds
with a --backtrack setting of 2.
X-Gentoo-bug: 632598
X-Gentoo-bug-url: https://bugs.gentoo.org/632598

want_restart_for_use_change: backtrack only if needed (bug 632598)

---

bin/ebuild-helpers/prepstrip

If debugedit is not found in PATH, then use debugedit
installed by app-arch/rpm (if available).
Suggested-by: Francesco Riosa <vivo75@gmail.com>
Bug: https://bugs.gentoo.org/634378
@vivo75

prepstrip: use debugedit from rpm if necessary (bug 634378)

---

bin/misc-functions.sh
bin/postinst-qa-check.d/50gnome2-utils
bin/postinst-qa-check.d/50xdg-utils
bin/preinst-qa-check.d/50gnome2-utils
bin/preinst-qa-check.d/50xdg-utils
pym/portage/package/ebuild/doebuild.py

In order to prevent false-positives during postinst_qa_check,
use a preinst_qa_check function to initialize a baseline state
for the postinst checks.
Bug: https://bugs.gentoo.org/635474

postinst_qa_check: initialize preinst state (bug 635474)

---

pym/portage/dep/dep_check.py
pym/portage/tests/resolver/test_or_downgrade_installed.py

Prefer to install a new package rather than to downgrade an
installed package. If the installed package should be
downgraded due to it being masked, then allow the downgrade.
Bug: https://bugs.gentoo.org/635540

dep_zapdeps: install new package, avoid downgrade (bug 635540)

---

pym/portage/dep/_dnf.py
pym/portage/dep/dep_check.py
pym/portage/tests/dep/test_dnf_convert.py
pym/portage/tests/dep/test_overlap_dnf.py
pym/portage/tests/resolver/test_virtual_minimize_children.py

dep_check: use DNF to optimize overlapping virtual || deps (bug 632026)
Deps like these:
|| ( foo bar ) || ( bar baz )
Translate to disjunctive normal form (DNF):
|| ( ( foo bar ) ( foo baz ) ( bar bar ) ( bar baz ) )
Using DNF, if none of the packages are currently installed,
then the ( bar bar ) choice will be automatically preferred
since it is satisfied by the fewest number of packages.
If the ( foo baz ) choice is already satisfied, then that
choice will be preferred instead.
Since DNF results in exponential explosion of the formula,
only use DNF for the parts of the dependencies that have
overlapping atoms.
In order to simplify the implementation of the dnf_convert
function, this patch also fixes _expand_new_virtuals to
normalize results in the same way as use_reduce (with no …

dep_check: use DNF to optimize overlapping || deps (bug 632026)

---

repoman/pym/repoman/tests/simple/test_simple.py
repoman/setup.py

Various code involving the .repoman_not_installed file assumes
that the 'pym' directory should be added to sys.path, therefore
create a pym -> lib symlink during unit tests.
Bug: https://bugs.gentoo.org/637460

repoman/setup.py: create pym -> lib symlink for unit tests (bug 637460)

---

COPYING
bin/doins.py
bin/ebuild-helpers/doins
pym/portage/tests/bin/test_doins.py

doins is written in bash. However, specifically in case that
too many files are installed, it is very slow.
This CL rewrites the script in python for performance.
BUG=chromium:712659
TEST=time (./setup_board --forace && \
./build_package --withdev && \
./build_image --noenable_rootfs_verification test)
===Before===
real    21m35.445s
user    93m40.588s
sys     21m31.224s
===After===
real    17m30.106s
user    94m1.812s
sys     20m13.468s
Change-Id: Ib10f623961ba316753d58397cff5e72fbc343339
Reviewed-on: https://chromium-review.googlesource.com/559225
X-Chromium-Bug: 712659
X-Chromium-Bug-url: https://bugs.chromium.org/p/chromium/issues/detail?id=712659
X-Gentoo-Bug: 624526
X-Gentoo-Bug-url: https://bugs.gentoo.org/624526

Rewrite doins by python (bug 624526).

---

pym/_emerge/Scheduler.py
pym/_emerge/main.py
pym/portage/package/ebuild/config.py

The Scheduler._env_sanity_check method executed too late
to prevent a KeyError for ARCH in getmaskingstatus, so
use profile_check to detect missing ARCH and exit earlier.
Bug: https://bugs.gentoo.org/586214

profile_check: detect missing ARCH variable (bug 586214)

---

pym/_emerge/depgraph.py
pym/portage/tests/resolver/test_disjunctive_depend_order.py
pym/portage/tests/resolver/test_onlydeps_minimal.py

Since built-time deps tend to be a superset of run-time deps, evaluate
disjunctive build-time deps before run-time deps, so that choices for
build-time deps influence choices for run-time deps.
Also, fix OnlydepsMinimalTestCase to specify ambiguous_merge_order,
since the merge order is affected by the order of evaluation.
Bug: https://bugs.gentoo.org/639346
@danielrobbins

depgraph: eval disjunctive build deps earlier (bug 639346)

---

pym/_emerge/BinpkgExtractorAsync.py

Fixes: b4b0e6b0aaa1 ("BinpkgExtractorAsync: remove trailer when decompressing binary packages")
Bug: https://bugs.gentoo.org/640450

BinpkgExtractorAsync: use posix compatible head arguments (bug 640450)

---

pym/_emerge/Package.py
pym/portage/dbapi/__init__.py
pym/portage/package/ebuild/config.py
pym/portage/tests/dbapi/test_fakedbapi.py

Since profile IUSE_IMPLICIT settings may diverge from those
that a binary package was built with, consider members of
built USE settings to be members of IUSE_EFFECTIVE. Only do
this for EAPIs that support IUSE_EFFECTIVE, since built USE
settings for earlier EAPIs may contain a large number of
irrelevant flags.
Note that the binary package may be remote, so it's only
possible to rely on metadata that is available in the remote
Packages file, and the IUSE_IMPLICIT header in the Packages
file is vulnerable to mutation.
Bug: https://bugs.gentoo.org/640318

Handle binary package IUSE_IMPLICIT divergence (bug 640318)

---

pym/portage/dep/soname/multilib_category.py
pym/portage/util/elf/constants.py

Discovered as missing ELF as:
* QA Notice: Unrecognized ELF file(s):
*      ALTERA_NIOS2;/lib/libz.so.1.2.11;libz.so.1;;libc.so.6;
Signed-off-by: Sergei Trofimovich <slyfox@gentoo.org>

multilib_category.py: add ALTERA_NIOS2 ELF type

---

pym/portage/tests/bin/test_doins.py

Use integer comparison in order to avoid failures like the
following:
AssertionError: 1515530127.479328 != 1515530127.479327

testDoInsOption: fix timestamp comparison to work in travis

---

bin/doins.py

Since conversion to/from float results in timestamp precision loss
with less than Python 3.3, do not use the python implementation
in this case.
Bug: https://bugs.gentoo.org/642632
Fixes: d459f05ff71f ("bin/doins.py: implement install -p option (bug 642632)")

bin/doins.py: avoid timestamp precision loss with python2 (bug 642632)

---

pym/portage/dep/dep_check.py
pym/portage/tests/resolver/test_virtual_minimize_children.py

Fix new_slot_count to exclude virtual packages, since they are considered
to have zero-cost. This solves an issue where the catalyst stage1 build
would unexpectedly pull in static-dev to satisfy virtual/dev-manager,
but eudev is the preferred choice.
Bug: https://bugs.gentoo.org/645190
Fixes: 9fdaf9bdbdf5 ("dep_check: use DNF to optimize overlapping virtual || deps (bug 632026)")
Reported-by: Ben Kohler <bkohler@gmail.com>

dep_zapdeps: exclude virtuals from new_slot_count (bug 645190)

---

pym/portage/dep/dep_check.py
pym/portage/tests/resolver/test_or_upgrade_installed.py

Fix the code from bug 643974 to set the installed_downgrade flag only
if the selected newer package is either installed or in the graph. This
is currently needed for appropriate handling of virtual/rust-1.19.0,
since there's an upgrade to dev-lang/rust-1.23.0 available which may
not be desired since it would mean that dev-lang/rust-bin-1.19.0 has
to be installed in order to satisfy virtual/rust-1.19.0:
|| ( =dev-lang/rust-1.19.0* =dev-lang/rust-bin-1.19.0* )
So, the rust-bin choice is desirable only if the rust-1.23.0 package is
already installed or in the graph.
Fixes: 86ba22da7a2f ("dep_zapdeps: install new package, allow upgrade (bug 643974)")
Bug: https://bugs.gentoo.org/645416

dep_zapdeps: fix virtual/rust handling (bug 645416)

---

man/emerge.1
pym/_emerge/create_depgraph_params.py
pym/_emerge/depgraph.py
pym/_emerge/main.py

The --dynamic-deps=n default causes confusion for users that are
accustomed to dynamic deps, therefore add a --changed-deps-report
option that is enabled by default for deep updates (if --usepkgonly
is not enabled).
The report is entirely suppressed in the following cases in which
the packages with changed dependencies are entirely harmless to the
user:
* --changed-deps or --dynamic-deps is enabled
* none of the packages with changed deps are in the graph
These cases suppress noise for the unaffected user, even though some
of the changed dependencies might be worthy of revision bumps.
The --quiet option suppresses the NOTE section of the report, but
the HINT section is still displayed since it might help users
resolve problems that are solved by --changed-deps.
Example output is as …

emerge: add --changed-deps-report option (bug 645780)

---

pym/portage/dep/dep_check.py
pym/portage/tests/dep/test_overlap_dnf.py
pym/portage/tests/resolver/test_virtual_minimize_children.py

Sorting of choices by new_slot_count causes the order of
choices specified in the ebuild to be discarded, and
new_slot_count may have variance related to the order that
packages are added to the graph. This variance can
contribute to outcomes that appear to be random, like when
catalyst stage1 builds sometimes pull in paludis to
satisfy perl-cleaner dependencies.
Meanwhile, the order specified in the ebuild has no
variance, and the preferences that it specifies can serve
as a crucial sources of guidance. Therefore, take advantage
of the order specified in the ebuild whenever possible, and
use new_slot_count only when it is needed to select optimal
choices from DNF (as in bug 632026).
This fixes random outcomes in the unit test for bug 645002.
Previously, the unit test pulled in paludis …

dep_zapdeps: sort by new_slot_count for DNF only (bug 645002)

---

man/emerge.1
pym/_emerge/Scheduler.py
pym/_emerge/create_depgraph_params.py
pym/_emerge/depgraph.py

There's been a lot of pushback involving the --dynamic-deps=n default.
What we really need is a tool to apply dependency changes in-place,
without the need for a rebuild.
Reverts: 2905e1c2c28d ("Disable dynamic-deps by default")
Bug: https://bugs.gentoo.org/646458

emerge: enable --dynamic-deps=y by default once again (bug 646458)

---

man/emerge.1
pym/_emerge/create_depgraph_params.py

This option is too noisy to enable by default, since it reports
hundreds of packages for most users.
Suggested-by: Michał Górny <mgorny@gentoo.org>

emerge: disable --changed-deps-report by default (bug 645780)

---

bin/filter-bash-environment.py
pym/portage/tests/bin/test_filter_bash_env.py

Use sys.stdin.buffer instead of sys.stdin.buffer.raw, for buffered input.
Also use raw bytes instead of unicode strings, in order to avoid making
assumptions about character encodings, and also to avoid overhead from
unicode decoding/encoding.
Since the % operator does not support bytes operands in python3.4, use
the + operator to format strings of bytes.
Bug: https://bugs.gentoo.org/647654

filter-bash-environment.py: use buffered input, raw bytes (bug 647654)

---

pym/_emerge/search.py

Since search strings containing a slash do no work unless category
match mode is enabled, use slash to auto-detect category match mode,
so that users do not have to prefix the search string with the special
@ symbol.
Bug: https://bugs.gentoo.org/647940

emerge --search: use slash to auto-detect category (bug 647940)

---

bin/ebuild
bin/emerge
pym/portage/process.py

For python3.4 and later, default to close_fds=False, since file
descriptors are non-inheritable by default due to PEP 446. This solves
a performance problem on systems like FreeBSD, where our get_open_fds
function returns all possible file descriptor values (including those
that are not open).
Bug: https://bugs.gentoo.org/648432
See: https://www.python.org/dev/peps/pep-0446/

portage.process.spawn: default close_fds=False (bug 648432)

---

pym/portage/dbapi/porttree.py
pym/portage/tests/util/futures/test_iter_completed.py
pym/portage/util/_async/AsyncTaskFuture.py
pym/portage/util/futures/iter_completed.py
pym/portage/util/futures/wait.py

Add async_aux_get method that returns a Future and otherwise
behaves identically to aux_get. Use async_aux_get to implement
the synchronous aux_get method.
Also add iter_completed convenience function.
The iter_completed function is similar to asyncio.as_completed, but
takes an iterator of futures as input, and includes support for
max_jobs and max_load parameters. The default values for max_jobs
and max_load correspond to multiprocessing.cpu_count().
Example usage for async_aux_get:
```python
import portage
from portage.util.futures.iter_completed import iter_completed
portdb = portage.portdb
future_cpv = {}
def future_generator():
for cpv in portdb.cp_list('sys-apps/portage'):
future = portdb.async_aux_get(cpv, portage.auxdbkeys)
future_cpv[id(future)] = cpv
yield future
for future in …
```

portdbapi: add async_aux_get method (bug 648790)

---

pym/portage/package/ebuild/doebuild.py

Remove a nosandbox assignment that never executes, since the condition for
the 'if' statement always evaluates to False:
```python
nosandbox = ( "userpriv" in features and
"usersandbox" not in features and
"userpriv" not in restrict and
"nouserpriv" not in restrict )
```
If nosandbox is True, it implies that the following expression is False:
```python
( "userpriv" not in features or
"userpriv" in restrict or
"nouserpriv" in restrict )
```
Therefore, the condition for the 'if' statement always evaluates to False.
Reported-by: Douglas Freed <dwfreed@mtu.edu>

_spawn_actionmap: simplify nosandbox logic

---

bin/postinst-qa-check.d/50gnome2-utils

For the first install of gtk-update-icon-cache, there's no
way to initialize state during preinst, so we have to ignore
this package in order to avoid false positives.
Bug: https://bugs.gentoo.org/649464

gnome2-utils postinst: fix false positive for gtk-update-icon-cache (bug 649464)

---

pym/portage/util/_eventloop/EventLoop.py
pym/portage/util/monotonic.py

Use time.monotonic() which is available in Python 3.3 and later,
and otherwise emulate it by using an offset to counteract any
backward movements.
Bug: https://bugs.gentoo.org/591760

EventLoop: implement time method for asyncio compat (bug 591760)

---

pym/portage/sync/modules/git/git.py

Bug: https://bugs.gentoo.org/650754

GitSync: abort early for missing git command (bug 650754)

---

man/emerge.1
pym/_emerge/create_depgraph_params.py
pym/_emerge/depgraph.py
pym/_emerge/main.py
pym/portage/tests/resolver/test_complete_graph.py

Ignore the @world package set and its dependencies. This may be useful
if there is a desire to perform an action even though it might break
the dependencies of some installed packages (it might also remove
installed packages in order to solve blockers). This also alters the
behavior of --complete-graph options so that only deep dependencies
of packages given as arguments are included in the dependency graph.
This option may be useful as an alternative to --nodeps in cases where
it is desirable to account for dependencies of packages given as
arguments.
Bug: https://bugs.gentoo.org/608564

emerge: add --ignore-world [ y | n ] option (bug 608564)

---

pym/_emerge/depgraph.py
pym/portage/tests/resolver/test_autounmask.py

Fix autounmask to generate USE changes that violate REQUIRED_USE, in
order to prevent it from trying to create inappropriate keywords or
package.unmask. This solves the problem reported in bug 622462, where
it inappropriately unmasked a newer version of qscintilla. With this
fix, it will generate USE changes that violate REQUIRED_USE, and then
report the issue as follows:
```
emerge: there are no ebuilds built with USE flags to satisfy ">=x11-libs/qscintilla-2.9.3-r2:=[qt5(+)]".
!!! One of the following packages is required to complete your request:
- x11-libs/qscintilla-2.9.4::test_repo (Change USE: +qt5, this change violates use flag constraints defined by x11-libs/qscintilla-2.9.4: 'exactly-one-of ( qt4 qt5 )')
```
Note that it may be possible for autounmask to try harder to solve …

emerge --autounmask: prevent unmask due to unsatisfied REQUIRED_USE (bug 622462)

---

pym/portage/eapi.py
pym/portage/package/ebuild/config.py

This is also implemented in portage-mgorny by the following commit:
https://github.com/mgorny/portage/commit/386cdb131c99b01541d53c8c894b2ec6534b6dea
Bug: https://bugs.gentoo.org/568884

Disallow package.provided in EAPI 7

---

man/emerge.1
pym/_emerge/create_depgraph_params.py
pym/_emerge/depgraph.py
pym/_emerge/main.py
pym/portage/tests/resolver/test_slot_change_without_revbump.py

This is similar to --changed-deps, but for SLOT metadata.
Bug: https://bugs.gentoo.org/631358

emerge: add --changed-slot [ y | n ] option (bug 631358)

---

bin/misc-functions.sh
bin/phase-functions.sh
pym/_emerge/EbuildPhase.py
pym/_emerge/PackagePhase.py
pym/portage/dbapi/vartree.py
pym/portage/util/install_mask.py

{,PKG_}INSTALL_MASK support for exclusions (bug 651214)
This patch series adds {,PKG_}INSTALL_MASK support for exclusions.
This includes a python implementation of INSTALL_MASK, with
matching performed by fnmatch code from these portage-mgorny
commits:
https://github.com/mgorny/portage/commit/f5ac3af3216d209618a2f232b4bf720bc8b520ad
https://github.com/mgorny/portage/commit/346da88d931de55cea1ab9657df30e26603469a6
I have specifically excluded changes related to [bug 364633](https://bugs.gentoo.org/364633), since
CONTENTS modifications add a significant amount of complexity which
has nothing to do with exclusion support.
Michał Górny (1):
{,PKG_}INSTALL_MASK: Support exclusions (bug 651214)
Zac Medico (3):
{,PKG_}INSTALL_MASK: record value in vardb
EbuildPhase: add PackagePhase class for …

{,PKG_}INSTALL_MASK support for exclusions (bug 651214)

---

bin/misc-functions.sh
bin/phase-functions.sh
pym/portage/dbapi/vartree.py

For binary packages, honor the INSTALL_MASK configuration that
exists at install time, since it might differ from the build time
setting.
Fixes: 3416876c0ee7 ("{,PKG_}INSTALL_MASK: python implementation")
Bug: https://bugs.gentoo.org/651952

INSTALL_MASK: honor install time config for binary packages (bug 651952)

---

repoman/cnf/repository/linechecks.yaml
repoman/cnf/repository/qa_data.yaml
repoman/cnf/repository/repository.yaml
repoman/man/repoman.1
repoman/pym/repoman/argparser.py
repoman/pym/repoman/modules/scan/module.py
repoman/pym/repoman/qa_data.py
repoman/pym/repoman/scanner.py
repoman/setup.py

This disables the new repository modules feature by default,
and it can be enabled in REPOMAN_DEFAULT_OPTS if desired.

repoman: add --experimental-repository-modules=<y|n> option

---

cnf/repos.conf
man/portage.5
pym/portage/repository/config.py
pym/portage/sync/modules/rsync/rsync.py
pym/portage/sync/syncbase.py
pym/portage/tests/util/futures/test_retry.py
pym/portage/util/_eventloop/EventLoop.py
pym/portage/util/backoff.py
pym/portage/util/futures/executor/fork.py
pym/portage/util/futures/futures.py
pym/portage/util/futures/retry.py

Since key refresh is prone to failure, retry using exponential
backoff with random jitter. This adds the following sync-openpgp-*
configuration settings:
sync-openpgp-key-refresh-retry-count = 40
Maximum number of times to retry key refresh if it fails.  Between
each  key  refresh attempt, there is an exponential delay with a
constant multiplier and a uniform random multiplier between 0 and 1.
sync-openpgp-key-refresh-retry-delay-exp-base = 2
The base of the exponential expression. The exponent is the number
of previous refresh attempts.
sync-openpgp-key-refresh-retry-delay-max = 60
Maximum  delay between each retry attempt, in units of seconds. This
places a limit on the length of the exponential delay.
sync-openpgp-key-refresh-retry-delay-mult = 4
Multiplier for the exponential delay. …

rsync: add key refresh retry (bug 649276)

---

pym/portage/dbapi/porttree.py
pym/portage/tests/util/futures/asyncio/test_event_loop_in_fork.py
pym/portage/tests/util/futures/test_iter_completed.py
pym/portage/util/_eventloop/EventLoop.py
pym/portage/util/futures/__init__.py
pym/portage/util/futures/_asyncio.py
pym/portage/util/futures/events.py
pym/portage/util/futures/futures.py
pym/portage/util/futures/iter_completed.py
pym/portage/util/futures/unix_events.py

This provides minimal interoperability with existing asyncio code,
by adding a portage.util.futures.unix_events.DefaultEventLoopPolicy
class that makes asyncio use portage's internal event loop when an
instance is passed into asyncio.set_event_loop_policy(). The
get_event_loop() method of this policy returns an instance of a
_PortageEventLoop class that wraps portage's internal event loop and
implements asyncio's AbstractEventLoop interface.
The portage.util.futures.asyncio module refers to the real
asyncio module when available, and otherwise falls back to a
minimal implementation that works with python2.7. The included
EventLoopInForkTestCase demonstrates usage, and works with all
supported versions of python, include python2.7.
In python3.4 and later, API consumers can use asyncio …

Add minimal asyncio.AbstractEventLoop implementation (bug 649588)

---

pym/_emerge/depgraph.py
pym/portage/tests/resolver/test_slot_operator_rebuild.py

If the parent is not installed, check if it needs to be rebuilt against
an installed instance, since otherwise it could trigger downgrade of
an installed instance.
Bug: https://bugs.gentoo.org/652938

_slot_operator.._reinstalls: probe binpkg rebuild (bug 652938)

---

pym/portage/tests/util/futures/asyncio/test_child_watcher.py
pym/portage/util/_eventloop/EventLoop.py
pym/portage/util/futures/_asyncio.py
pym/portage/util/futures/unix_events.py

Use a _PortageChildWatcher class to wrap portage's internal event loop
and implement asyncio's AbstractChildWatcher interface.
Bug: https://bugs.gentoo.org/649588

Implement AbstractEventLoopPolicy.get_child_watcher() (bug 649588)

---

pym/portage/tests/util/futures/asyncio/test_subprocess_exec.py
pym/portage/util/futures/unix_events.py

In python versions that support asyncio, this allows API consumers
to use the asyncio.create_subprocess_exec() function with portage's
internal event loop. Currently, subprocess.PIPE is not implemented
because that would require an implementation of asyncio's private
asyncio.unix_events._UnixReadPipeTransport class. However, it's
possible to use pipes created with os.pipe() for stdin, stdout,
and stderr, as demonstrated in the included unit tests.
Bug: https://bugs.gentoo.org/649588

Implement _PortageEventLoop.subprocess_exec (bug 649588)

---

cnf/repos.conf
man/portage.5
pym/portage/sync/modules/rsync/rsync.py

Some users have reported that using all processors to verify
manifests results in overloading, therefore default to using
a single processor. On modern hardware, verification of the
gentoo repository completes in less than 20 seconds, so using
multiple processors is not really necessary. Also, gemato-13.0
disables parallel verification due to the unresolved deadlock
issue reported in bug 647964, so this brings the default
portage configuration into alignment with current gemato
behavior.
Bug: https://bugs.gentoo.org/650696
Bug: https://bugs.gentoo.org/647964

rsync: default to sync-rsync-verify-jobs = 1 (bug 650696)

---

pym/portage/tests/util/futures/test_iter_completed.py
pym/portage/util/futures/iter_completed.py

This serves as a wrapper around portage's internal TaskScheduler
class, allowing TaskScheduler API consumers to be migrated to use
asyncio interfaces.
Bug: https://bugs.gentoo.org/591760

Add async_iter_completed for asyncio migration (bug 591760)

---

pym/_emerge/actions.py
pym/_emerge/main.py
pym/portage/dbapi/bintree.py
pym/portage/package/ebuild/config.py
pym/portage/package/ebuild/profile_iuse.py

For emerge --usepkgonly mode, it's useful to be able to operate without
dependence on a local ebuild repository and profile. Therefore,
merge Packages header settings from the binary package database
(including binhost(s) if enabled) into the profile configuration,
in order to propagate implicit IUSE and USE_EXPAND settings for use
with binary and installed packages. Values are appended, so the result
is a union of elements.
Also use ARCH from the binary package database if it's not defined by
the profile, since ARCH is used for validation by emerge's profile_check
function, and also for KEYWORDS logic in the _getmaskingstatus function.
All changes are currently confined to --usepkgonly mode, since this is
the mode where it is needed the most, and this ensures that behavior of …

emerge --usepkgonly: propagate implicit IUSE and USE_EXPAND (bug 640318)

---

pym/_emerge/AbstractEbuildProcess.py
pym/_emerge/AsynchronousLock.py
pym/_emerge/Binpkg.py
pym/_emerge/EbuildBuild.py
pym/_emerge/EbuildBuildDir.py
pym/_emerge/PackageUninstall.py
pym/_emerge/Scheduler.py
pym/portage/dbapi/vartree.py
pym/portage/package/ebuild/doebuild.py
pym/portage/tests/ebuild/test_ipc_daemon.py
pym/portage/tests/locks/test_asynchronous_lock.py

Asynchronoulsy handle locking of both the category directory and
build directory.
Bug: https://bugs.gentoo.org/614112

EbuildBuildDir: add async_lock method (bug 614112)

---

pym/_emerge/EbuildBuild.py
pym/_emerge/EbuildFetcher.py
pym/portage/dbapi/porttree.py

Bug: https://bugs.gentoo.org/653810
Zac Medico (5):
portdbapi: add async_fetch_map method (bug 653810)
EbuildFetcher: inherit CompositeTask (bug 653810)
EbuildFetcher: add _async_uri_map method (bug 653810)
EbuildFetcher: use _async_uri_map in _start (bug 653810)
EbuildFetcher: add async_already_fetched method (bug 653810)
pym/_emerge/EbuildBuild.py    |   8 +++-
pym/_emerge/EbuildFetcher.py  | 105 ++++++++++++++++++++++++++++++++----------
pym/portage/dbapi/porttree.py |  75 +++++++++++++++++++++++-------
3 files changed, 146 insertions(+), 42 deletions(-)

EbuildFetcher._get_uri_map(): fix event loop recursion (bug 653810)

---

pym/_emerge/actions.py

Fix emerge --config exit status so that it will return 1 if
the pkg_config function calls die.
Bug: https://bugs.gentoo.org/653638

emerge --config: return pkg_config exit status (bug 653638)

---

pym/_emerge/AbstractPollTask.py
pym/_emerge/AsynchronousLock.py
pym/_emerge/AsynchronousTask.py
pym/_emerge/CompositeTask.py
pym/portage/tests/ebuild/test_ipc_daemon.py
pym/portage/util/SlotObject.py
pym/portage/util/_async/AsyncScheduler.py
pym/portage/util/_async/AsyncTaskFuture.py

Since the AsynchronousTask.wait() method is prone to event loop
recursion, deprecate it, and add an async_wait() method method to
replace it. Instead of using task.wait() in order to implicitly run
the event loop, now loop.run_until_complete(task.async_wait()) will
be used to explicitly run the event loop. This explicit approach will
make it more obvious when code will trigger event loop recursion
which would not be compatible with asyncio's default event loop.
Bug: https://bugs.gentoo.org/653856
Zac Medico (2):
AsynchronousTask: add scheduler attribute (bug 653856)
AsynchronousTask: add async_wait() method (bug 653856)
pym/_emerge/AbstractPollTask.py             |  3 +--
pym/_emerge/AsynchronousLock.py             |  2 +-
pym/_emerge/AsynchronousTask.py             | 25 …

AsynchronousTask: add async_wait() method (bug 653856)

---

pym/portage/dbapi/porttree.py
pym/portage/package/ebuild/_parallel_manifest/ManifestScheduler.py
pym/portage/package/ebuild/_parallel_manifest/ManifestTask.py
pym/portage/tests/dbapi/test_portdb_cache.py
pym/portage/util/futures/iter_completed.py

In order to avoid event loop recursion, pass fetchlist_dict to
ManifestTask as a Future.
Bug: https://bugs.gentoo.org/653946

ManifestScheduler: async fetchlist_dict (bug 653946)

---

pym/portage/_emirrordist/FetchIterator.py

Since construction of FetchTask instances requires results from
aux_get calls that would trigger event loop recursion when executed
synchronously, add an _async_fetch_tasks function to construct
FetchTask instances asynchronously and return a Future. Use an
_EbuildFetchTasks class to wait for the FetchTask instances to
become available, and then execute them.
Bug: https://bugs.gentoo.org/654038

FetchIterator: fix event loop recursion (bug 654038)

---

pym/_emerge/AbstractEbuildProcess.py
pym/_emerge/AbstractPollTask.py
pym/_emerge/AsynchronousLock.py
pym/_emerge/AsynchronousTask.py
pym/_emerge/CompositeTask.py
pym/_emerge/FifoIpcDaemon.py
pym/_emerge/PipeReader.py
pym/_emerge/SpawnProcess.py
pym/_emerge/SubProcess.py
pym/portage/_emirrordist/MirrorDistTask.py
pym/portage/util/_async/AsyncScheduler.py
pym/portage/util/_async/AsyncTaskFuture.py
pym/portage/util/_async/PipeLogger.py
pym/portage/util/_async/PipeReaderBlockingIO.py
pym/portage/util/_async/SchedulerInterface.py

Make the wait() and _async_wait() methods raise InvalidStateError
when the event loop is running and the returncode is not available,
since these cases would trigger event loop recursion. There are no
known remaining cases that cause event loop recursion via wait()
and _async_wait(), and this patch protects against changes that would
accidentally re-introduce event loop recursion.
Since the wait() method now raises InvalidStateError in cases where
it previously would have called the _wait() method, this patch makes
it possible to remove the _wait() method implementations from all
subclasses of AsynchronousTask. Subclasses that used the _wait()
method to perform cleanup now use the _async_wait() method instead.
Bug: https://bugs.gentoo.org/653856

AsynchronousTask: disable event loop recursion (bug 653856)

---

pym/portage/package/ebuild/config.py

Since SYSROOT=/ interacts badly with autotools.eclass (bug 654600),
and no EAPI expects SYSROOT to have a trailing slash, always strip
the trailing slash from SYSROOT.
Bug: https://bugs.gentoo.org/654600
Fixes: a41dacf7926c ("Export SYSROOT and ESYSROOT in ebuild env in EAPI 7")
@chewi

config.environ:	always strip slash from	SYSROOT	(bug 654600)

---

pym/_emerge/depgraph.py
pym/portage/tests/resolver/test_autounmask.py
pym/portage/tests/resolver/test_slot_collisions.py

When autounmask USE changes violate REQUIRED_USE, rather than
recalculate with autounmask disabled, display the autounmask USE
changes along with the REQUIRED_USE violation. Adjust unit tests
to allow for the autounmask USE changes that were previously
discarded. For the case reported in bug 654782, the output will
appear as follows:
```
The following keyword changes are necessary to proceed:
(see "package.accept_keywords" in the portage(5) man page for more details)
=app-editors/retext-7.0.1-r1 ~amd64
The following USE changes are necessary to proceed:
(see "package.use" in the portage(5) man page for more details)
>=dev-python/PyQt5-5.9.2 printsupport webengine network gui widgets
!!! The ebuild selected to satisfy "dev-python/PyQt5[gui,network,printsupport,webengine,widgets,python_targe …
```

depgraph.autounmask_breakage_detected: ignore REQUIRED_USE violations (bug 654782)

---

pym/portage/util/_async/SchedulerInterface.py
pym/portage/util/_eventloop/asyncio_event_loop.py
pym/portage/util/_eventloop/global_event_loop.py
pym/portage/util/futures/_asyncio/__init__.py
pym/portage/util/futures/unix_events.py

For python3.4 and later, in the main process, replace portage's
internal event loop with the standard library's asyncio event
loop. Continue to use portage's internal event loop in subprocesses,
since asyncio's event loop is not guaranteed to work well in
subprocesses (see upstream python issues 22087 and 29703).
An _AsyncioEventLoopPolicy class, derived from _PortageEventLoopPolicy,
is needed for some unit tests that modify asyncio's event loop policy.
This policy is not needed for anything other than unit testing. Portage
uses asyncio's default event loop policy, and API consumers are free to
use any desired event loop policy.
Portage's asynchronous functions that accept a 'loop' parameter will
work with any compatible asyncio.AbstractEventLoop implementation, since
an internal …

global_event_loop: use asyncio event loop (bug 654390)

---

pym/_emerge/EbuildPhase.py
pym/_emerge/MiscFunctionsProcess.py
pym/portage/package/ebuild/doebuild.py

Since SELinux does not allow LD_PRELOAD across domain transitions,
disable the LD_PRELOAD sandbox for preinst_selinux_labels.
Bug: https://bugs.gentoo.org/655996
@perfinion

preinst_selinux_labels: disable LD_PRELOAD sandbox (bug 655996)

---

pym/portage/tests/util/dyn_libs/test_soname_deps.py
pym/portage/util/_dyn_libs/soname_deps.py

Packages like ebtables have internal libraries that lack a DT_SONAME
field in their ELF header. Consumers of these internal libraries have
DT_RUNPATH entries that refer to the directory containing the internal
libraries. For library dependencies that are satisfied by internal
libraries like this, it is inappropriate for SonameDepsProcessor to
include these depenedencies in the REQUIRES metadata, therefore fix
SonameDepsProcessor to automatically detect this case and exclude
these dependencies from the REQUIRES metadata. This solves incorrect
reporting of broken soname dependencies like the following:
```
$ emerge -p --depclean --ignore-soname-deps=n
Calculating dependencies... done!
* Broken soname dependencies found:
*
*   x86_64: libebt_redirect.so required by:
* …
```

SonameDepsProcessor: handle internal libs without DT_SONAME (bug 646190)

---

pym/portage/util/_eventloop/asyncio_event_loop.py

Fix portage commands to exit immediately for any unhandled
exceptions that are raised while the asyncio event loop is running
without a tty. If we have a tty then start the debugger,
since in might aid in diagnosis of the problem.
In order to avoid potential interference with API consumers, do not
call set_exception_handler unless portage._internal_caller is True.
Bug: https://bugs.gentoo.org/658684

AsyncioEventLoop: exit after unhandled exception (bug 658684)

---

pym/portage/tests/util/test_install_mask.py
pym/portage/util/install_mask.py

Fix the python INSTALL_MASK implementation so that a trailing slash
matches a directory, for compatibility with the previous bash
implementation.
Fixes: 3416876c0ee7 ("{,PKG_}INSTALL_MASK: python implementation")
Bug: https://bugs.gentoo.org/658322

{,PKG_}INSTALL_MASK: support trailing slash (bug 658322)

---

bin/install-qa-check.d/10executable-issues
bin/install-qa-check.d/10ignored-flags
bin/misc-functions.sh

For all scanelf path arguments that are used in processing of
the `%p` format string, normalize the argument to have a trailing
slash, so that the leading slash is consistently stripped in
the expansion of the `%p` format string.
Bug: https://bugs.gentoo.org/659228

scanelf: fix %p format string for EAPI 7 (bug 659228)

---

cnf/repos.conf
man/portage.5
pym/portage/repository/config.py
pym/portage/sync/modules/rsync/rsync.py

Sync into a quarantine subdirectory, using the rsync --link-dest option
to create hardlinks to identical files in the previous snapshot of the
repository. If hardlinks are not supported, then show a warning message
and sync directly to the normal repository location.
If verification succeeds, then the quarantine subdirectory is synced
to the normal repository location, and the quarantine subdirectory
is deleted. If verification fails, then the quarantine directory is
preserved for purposes of analysis.
Even if verification happens to be disabled, the quarantine directory
is still useful for making the repository update more atomic, so that
it is less likely that normal repository location will be observed in
a partially synced state.
The new behavior may conflict with configurations that …

rsync: quarantine data prior to verification (bug 660410)

---

man/portage.5
pym/portage/repository/config.py
pym/portage/sync/modules/git/git.py

Support sync-depth for shallow sync, using git reset --merge just
like in the earlier implementation that was reverted in commit
ab840ac982d3c8b676b89f6bedd14e85dd06870f. Also, use git gc --auto
in order to trigger periodic housekeeping and hopefully avoid
errors from automatic git gc calls as reported in bug 599008.
The default sync-depth is unlimited, which means that default
behavior remains unchanged (unlike the previous implementation that
was reverted).
Bug: https://bugs.gentoo.org/552814
Bug: https://bugs.gentoo.org/599008

GitSync: support sync-depth (bug 552814)

---

pym/portage/tests/util/futures/test_compat_coroutine.py
pym/portage/util/futures/compat_coroutine.py

For readability, it's desirable to make asynchronous code use
coroutines to avoid callbacks when possible. For python2 compatibility,
generators that yield Futures can be used to implement coroutines.
Add a compat_coroutine module which provides a @coroutine decorator
and a coroutine_return function that can be used to return a value
from a generator. The decorated function returns a Future which is
done when the generator is exhausted. Usage is very similar to asyncio
coroutine usage in python3.4 (see unit tests).
Bug: https://bugs.gentoo.org/660426

Add python2 compatible coroutine support (bug 660426)

---

pym/_emerge/depgraph.py
pym/portage/dbapi/porttree.py

Make portdbapi.cp_list return _pkg_str instances that have a 'repo'
attribute (bindbapi.cp_list already does this), with results
in ascending order by (pkg.version, repo.priority). Optimize
portdbapi.findname2 to use the 'repo' attribute to enable cached
results for files previously found by the portdbapi.cp_list
method, avoiding filesystem access when possible. Optimize the
depgraph._iter_match_pkgs_atom method by elimination of the repo
loop, since portdbapi.cp_list now returns separate items when the
same package version is found in multiple repos.
Bug: https://bugs.gentoo.org/650814

portdbapi.cp_list: cache repo associations (bug 650814)

---

pym/portage/package/ebuild/config.py

Optimize config to stat profile.bashrc files once in the constructor,
in order to avoid repeated stat calls in the setcpv method.
Bug: https://bugs.gentoo.org/649806

config: cache profile.bashrc stat results (bug 649806)

---

pym/portage/repository/config.py

Pass the main-repo name from repos.conf as the repository name
for the PORTDIR RepoConfig constructor, so that it can override
the main repo location even if the profiles/repo_name file does
not exist yet (like in a stage3 tarball).
Bug: https://bugs.gentoo.org/661276
Reported-by: Jorge Manuel B. S. Vicetto <jmbsvicetto@gentoo.org>

RepoConfig: fix make.conf PORTDIR override (bug 661276)

---

pym/portage/dbapi/__init__.py
repoman/pym/repoman/modules/scan/depend/profile.py

For the empty profile that's used to check dependencies of
ebuilds that have empty KEYWORDS, populate implicit IUSE
from all of the make.defaults files found in the relevant
repositories (this should take less than 1 second on most
hardware). Since the IUSE.missing check cannot be performed
without implicit IUSE settings, this makes the IUSE.missing
check work for ebuilds with empty KEYWORDS.
Bug: https://bugs.gentoo.org/660982

repoman: populate implicit IUSE for empty profile (bug 660982)

---

bin/emerge-webrsync
lib/portage/sync/modules/webrsync/__init__.py
lib/portage/sync/modules/webrsync/webrsync.py
man/portage.5
misc/emerge-delta-webrsync

Add repos.conf settings that enable sync-openpgp-key-path support for
both emerge-webrsync and emerge-delta-webrsync:
```
sync-webrsync-delta = true|false
Use app-portage/emerge-delta-webrsync to minimize
bandwidth. Defaults to false.
sync-webrsync-keep-snapshots = true|false
Keep snapshots in DISTDIR (do not delete). Defaults to false.
sync-webrsync-verify-signature = true|false
Require the detached tarball signature to contain a good OpenPGP
signature. This  uses the OpenPGP key(ring) specified by the
sync-openpgp-key-path setting. Defaults to false.
```
Bug: https://bugs.gentoo.org/661838

webrsync: support sync-openpgp-key-path (bug 661838)

---

bin/install-qa-check.d/60pngfix

If xargs supports the --max-procs option then use the makeopts_jobs
function from helper-functions.sh to generate a --max-procs argument.
Use xargs `-L 1` to limit the number of png files per pngfix process,
in order to ensure that enough processes are spawned, since otherwise
xargs minimizes the number of processes spawned. A benchmark with
flightgear-data-2018.2.1 shows that larger values of -L only decrease
performance.
Bug: https://bugs.gentoo.org/630292
Reviewed-by: Lars Wendler <polynomial-c@gentoo.org>
Reviewed-by: Mike Gilbert <floppym@gentoo.org>

install-qa-check.d/60pngfix: parallel support (bug 630292)

---

lib/portage/tests/util/futures/asyncio/test_subprocess_exec.py
lib/portage/util/futures/_asyncio/__init__.py
lib/portage/util/futures/_asyncio/process.py
lib/portage/util/futures/_asyncio/streams.py
lib/portage/util/futures/compat_coroutine.py

The asyncio.create_subprocess_exec function is essential for
using subprocesses in coroutines, so add support to do this
for python2. This paves the way for extensive use of coroutines
in portage, since coroutines are well-suited for many portage
tasks that involve subprocesses.
Bug: https://bugs.gentoo.org/662388

Add asyncio.create_subprocess_exec support for python2 (bug 662388)

---

bin/install-qa-check.d/90bad-bin-group-write
bin/install-qa-check.d/90bad-bin-owner

Discussed and implemented in,
https://bugs.gentoo.org/629398
Michael Orlitzky (2):
bin/install-qa-check.d: add new 90bad-bin-owner QA check.
bin/install-qa-check.d: add new 90bad-bin-group-write QA check.

Two insecure ownership and group-writability QA checks

---

bin/isolated-functions.sh

For USERLAND=BSD, set XARGS="gxargs -r" if gxargs is available,
so the code from bug 630292 works for USERLAND=BSD.
Fixes: 50283f1abb77 (install-qa-check.d/60pngfix: parallel support (bug 630292))
Reported-by: Michał Górny <mgorny@gentoo.org>
Bug: https://bugs.gentoo.org/663256

XARGS: use gxargs for USERLAND=BSD (bug 663256)

---

lib/portage/package/ebuild/config.py

Make RESTRICT=test prevent the "test" USE flag from being added to
features USE flags when FEATURES=test is enabled, in order to preserve
default behavior for ebuilds that set RESTRICT=test. The code that sets
the restrict_test variable in the setcpv method must execute earlier
now, but the logic is unchanged. Note that it is still possible to
enable USE=test for ebuilds that set RESTRICT=test, but FEATURES=test
will not do it, so it will only be triggered by an explicit USE=test
setting by the user or profile.
Fixes: 8c5598c1af2c ("Replace implicit {FEATURES->USE}=test forcing with USE default")
Bug: https://bugs.gentoo.org/663278

Make features USE respect RESTRICT=test (bug 663278)

---

lib/portage/package/ebuild/config.py

Initialize default features USE state, and reset when appropriate,
so that the "test" flag state is correct for evaluation of !test?
conditionals in RESTRICT.
Fixes: 45986341a80c ("Support !test? conditionals in RESTRICT (bug 663278)")

config: default features USE for conditional RESTRICT (bug 663848)

---

lib/portage/package/ebuild/_config/LocationsManager.py

When ROOT or PORTAGE_CONFIGROOT is entirely empty, map
the value to / since otherwise is becomes the current
working directory which gives undesirable results.
Bug: https://bugs.gentoo.org/663904

LocationsManager: map empty root var to / (bug 663904)

---

lib/portage/repository/config.py
lib/portage/repository/storage/__init__.py
lib/portage/repository/storage/hardlink_quarantine.py
lib/portage/repository/storage/hardlink_rcu.py
lib/portage/repository/storage/inplace.py
lib/portage/repository/storage/interface.py
lib/portage/sync/controller.py
lib/portage/sync/modules/rsync/rsync.py
lib/portage/sync/syncbase.py
lib/portage/tests/sync/test_sync_local.py
lib/portage/tests/util/futures/test_compat_coroutine.py
lib/portage/util/futures/_asyncio/__init__.py
lib/portage/util/futures/_sync_decorator.py
lib/portage/util/futures/compat_coroutine.py
man/portage.5

Add a boolean sync-rcu repos.conf setting that behaves as follows:
sync-rcu = yes|no
Enable read-copy-update (RCU) behavior for sync operations. The
current latest immutable version of a repository will be referenced
by a symlink found where the repository would normally be located
(see the location setting). Repository consumers should resolve
the cannonical path of this symlink before attempt to access
the repository, and all operations should be read-only, since
the repository is considered immutable. Updates occur by atomic
replacement of the symlink, which causes new consumers to use the
new immutable version, while any earlier consumers continue to
use the cannonical path that was resolved earlier. This option
requires sync-allow-hardlinks and sync-rcu-store-dir options to
be …

Add sync-rcu support for rsync (bug 662070)

---

lib/portage/dbapi/porttree.py

Add an async_xmatch method, and use it to implement the synchronous
xmatch method. Deprecate unused xmatch method parameters. Use the
compat_coroutine decorator for backward compatibility with python2.7
(via PEP 342 enhanced generators).
Bug: https://bugs.gentoo.org/666940
Suggested-by: Daniel Robbins <drobbins@funtoo.org>
@danielrobbins

portdbapi: add async_xmatch method (bug 666940)

---

lib/portage/package/ebuild/doebuild.py

Respect the order of paths defined in /etc/env.d/*, so that
packages like llvm can rely on ordering relative to paths
defined in /etc/env.d/50baselayout since baselayout-2.6.
See: https://gitweb.gentoo.org/proj/baselayout.git/commit/?id=277e5b9e55717873b87eb541a95f4f2ae0c60a4d
Bug: https://bugs.gentoo.org/667662

_doebuild_path: Respect order defined in ROOTPATH (bug 667662)

---

bin/estrip

The purpose of RESTRICT=strip is to prevent files from being stripped,
not to silence QA checks about pre-stripped files.

estrip: Report pre-stripped files even with RESTRICT=strip

---

lib/portage/repository/config.py

It will make future changes easier and more readable.
Signed-off-by: Arfrever Frehtes Taifersar Arahesis <Arfrever@Apache.Org>

portage.repository.config: Sort some tuples and put each element on separate line.

---

lib/portage/process.py
lib/portage/sync/modules/git/git.py
lib/portage/tests/sync/test_sync_local.py

Use portage.process.spawn (with new cwd parameter) and self.spawn_kwargs
to drop privileges for git gc and merge commands.
Fixes: 3cd8cf93abb6 ("GitSync: abort checkout for signature problem (bug 660372)")
Fixes: 903c4b1a6768 ("GitSync: support sync-depth (bug 552814)")
Bug: https://bugs.gentoo.org/669496
Zac Medico (2):
portage.process.spawn: add cwd parameter
git: drop privileges for gc and merge (bug 669496)
lib/portage/process.py                    | 13 ++++++++++---
lib/portage/sync/modules/git/git.py       | 10 ++++++----
lib/portage/tests/sync/test_sync_local.py |  9 ++++++++-
3 files changed, 24 insertions(+), 8 deletions(-)

git: drop privileges for gc and merge (bug 669496)

---

lib/portage/process.py

Make child processes inherit the current process's environment by
default, so that behavior is equivalent to the standard library's
subprocess module.
Bug: https://bugs.gentoo.org/672440

portage.process.spawn: inherit env by default (bug 672440)

---

bin/ebuild-helpers/bsd/sed
bin/ebuild-helpers/portageq
bin/ebuild-helpers/unprivileged/chown
bin/ebuild-helpers/xattr/install
lib/portage/tests/resolver/ResolverPlayground.py

Ensure that essential_binaries symlinks do not refer to internal
wrapper scripts, in order to avoid infinite recursion. Use the
same ebuild-helpers pattern as the portageq wrapper script since
daeb75b345c4433218ab9e7a5319e8914092f048.
Fixes: 1b5edbb5ec70 ("_doebuild_path: do not use host PATH by default and prepend EPREFIX PATH")

ResolverPlayground: exclude internal wrappers from essential_binaries PATH

---

bin/ebuild.sh
lib/portage/package/ebuild/doebuild.py

In ebuild.sh, grant sandbox write access directly to
${PORTAGE_TMPDIR}/portage, since write access to ${PORTAGE_TMPDIR}
itself is not needed. Also, remove the _check_temp_dir symlink
check from bug 378403, since a symlink is permissible if write
access is granted directly to ${PORTAGE_TMPDIR}/portage.
Bug: https://bugs.gentoo.org/673738
Bug: https://bugs.gentoo.org/378403

ebuild.sh: sandbox write to ${PORTAGE_TMPDIR}/portage (bug 673738)

---

lib/_emerge/AbstractEbuildProcess.py
lib/portage/package/ebuild/doebuild.py

Whitelist the same phases that are whitelisted for FEATURES=cgroup,
since pid-sandbox is less valuable and is likely to have unintended
consenquences during these phases.
Bug: https://bugs.gentoo.org/673794

pid-sandbox: whitelist selected pkg_* phases (bug 673794)

---

bin/misc-functions.sh
lib/portage/tests/resolver/ResolverPlayground.py

The canonicalize function is required by install-qa-check.d/05prefix.
Fixes: aa0a94198794 ("ecompress: Replace with implementation from portage[mgorny]")
Bug: https://bugs.gentoo.org/670484

misc-functions.sh: restore canonicalize func (bug 675284)

---

lib/portage/tests/util/test_install_mask.py
lib/portage/util/install_mask.py

For scalability, use a tree structure to index patterns that are
anchored with a leading slash.
Patterns anchored with leading slash are indexed by leading non-glob
components, making it possible to minimize the number of fnmatch
calls. For example:
```
/foo*/bar -> {'.': ['/foo*/bar']}
/foo/bar* -> {'foo': {'.': ['/foo/bar*']}}
/foo/bar/ -> {'foo': {'bar': {'.': ['/foo/bar/']}}}
```
Bug: https://bugs.gentoo.org/675826

INSTALL_MASK: index patterns anchored with leading slash (bug 675826)

---

bin/pid-ns-init
lib/portage/process.py

Use subprocess.Popen to correctly configure the signal disposition
of the child process, since os.fork leaves the signal disposition
in a state which may be inappropriate for various signals including
SIGPIPE, SIGQUIT, SIGTERM, and SIGINT. For python implementations
other that CPython >= 3, use preexec_fn to manually configure the
signal disposition (I have found that this is necessary for CPython
2.7 and all PyPy versions tested, including PyPy3).
Bug: https://bugs.gentoo.org/675828

pid-ns-init: fix child process signal disposition (bug 675828)

---

bin/ebuild.sh

Use local -x ECLASS, and also make __export_funcs_var a local variable,
since this is simpler than managing these variables as globals
(eliminates PECLASS and prev_export_funcs_var variables). As an
additional benefit, this prevents interference from ebuild variables
as reported in bug 656354 for the ECLASS variable.
Bug: https://bugs.gentoo.org/656354
Bug: https://bugs.gentoo.org/676014

inherit: use local -x ECLASS (bug 676014)

---

bin/pid-ns-init

Use setsid to isolate the parent process from signals sent
to the process group, and forward signals to the entire
process group with kill(0, signum).
Bug: https://bugs.gentoo.org/675870

pid-sandbox: pid-ns-init setsid support (bug 675870)

---

bin/pid-ns-init
lib/portage/process.py

Drop permissions only for subprocess of pid-ns-init but not pid-ns-init
itself. With FEATURES="pid-sandbox userpriv", pid-ns-init should be
run with unchanged permissions (usually UID=0, GID=0).
Bug: https://bugs.gentoo.org/675868
Signed-off-by: Arfrever Frehtes Taifersar Arahesis <Arfrever@Apache.Org>

pid-sandbox: run pid-ns-init as root (bug 675868)

---

bin/pid-ns-init

Set the controlling terminal to the stdout pty after calling setsid,
in order to avoid "No such device or address" ENXIO errors when
attempting to open /dev/tty.
Bug: https://bugs.gentoo.org/675868

pid-sandbox: pid-ns-init TIOCSCTTY after setsid (bug 675868)

---

bin/pid-ns-init

The fcntl.ioctl call raises IOError, which is different from OSError
for python2. Use EnvironmentError for compatibility.
Bug: https://bugs.gentoo.org/675868
Fixes: ce0656337268 ("pid-sandbox: pid-ns-init TIOCSCTTY after setsid (bug 675868)")

pid-sandbox: handle EnvironmentError for python2 compat (bug 675868)

---

bin/ebuild.sh
bin/phase-helpers.sh
lib/portage/package/ebuild/_config/special_env_vars.py
lib/portage/package/ebuild/config.py

When trying to figure out why it took so long to do a no-op kernel
build (re-build when nothing changed) on Chrome OS, I tracked down one
slowdown to cros-kernel2_src_configure().  This function was taking
~900 ms to execute.
The bulk of that slowdown was in iterating over the list of config
fragments, specifically the "use ${fragment}" test.  We currently have
77 fragments so we were effectively calling the "use" function 77
times.
Digging through the portage code, the slow part of the "use" function
was the block of code to confirm that you specified each USE flag in
your IUSE.  Commenting out the whole "elif" block of code there sped
things up so that the entire cros-kernel2_src_configure() was now
taking ~130 ms.  This means that each call to the "use" function was
taking about 10 ms. …

Speed up testing against IUSE by not using regexp

---

lib/portage/util/_eventloop/asyncio_event_loop.py

Before the exception handler invokes the pdb shell, enable SIGINT so
that the user can exit with Control-C (otherwise SIGKILL is needed).
Bug: https://bugs.gentoo.org/672540

AsyncioEventLoop: enable SIGINT in exception handler (bug 672540)

---

lib/_emerge/depgraph.py
lib/portage/__init__.py
lib/portage/cache/mappings.py
lib/portage/dbapi/porttree.py
lib/portage/news.py
lib/portage/package/ebuild/fetch.py
lib/portage/sync/__init__.py
lib/portage/sync/controller.py

This is no longer needed becuase collections.OrderedDict is available
since Python 2.7.

Remove internal OrderedDict implementation

---

lib/portage/__init__.py
lib/portage/tests/dep/testAtom.py
lib/portage/tests/emerge/test_emerge_slot_abi.py
lib/portage/tests/resolver/test_slot_abi.py
lib/portage/tests/resolver/test_slot_abi_downgrade.py
lib/portage/tests/resolver/test_slot_collisions.py
lib/portage/tests/resolver/test_slot_operator_autounmask.py
lib/portage/tests/resolver/test_targetroot.py
lib/portage/tests/update/test_move_slot_ent.py

All of these EAPIs are obsolete since their features are available in official EAPIs.

Deprecate EAPIs 4-slot-abi, 5-hdepend, and 7_pre1

---

lib/_emerge/BinpkgVerifier.py
lib/portage/package/ebuild/fetch.py
lib/portage/tests/ebuild/test_fetch.py

Direct FETCHCOMMAND/RESUMECOMMAND output to a temporary file with
a constant `.__download__` suffix, and atomically rename the file
to remove the suffix only after the download has completed
successfully (includes digest verification when applicable).
Also add unit tests to cover most fetch cases.
Bug: https://bugs.gentoo.org/175612

fetch: atomic downloads (bug 175612)

---

bin/eapi.sh
bin/install-qa-check.d/95empty-dirs
man/make.conf.5

Suggested-by: Pacho Ramos <@pacho2>
Bug: https://bugs.gentoo.org/651678

Enable FEATURES=strict-keepdir behavior for new EAPIs

---

lib/portage/dbapi/__init__.py

This corrects a problem triggered with USE defaults where repoman
returns an incorrect negative match for an atom with USE defaults.
For example, it triggered this dependency.bad error:
```
RepoMan scours the neighborhood...
dependency.bad [fatal]        2
dev-libs/libxml2/libxml2-2.9.9-r1.ebuild: DEPEND: ~riscv(default/linux/riscv/17.0/rv64gc)
[     '>=dev-lang/python-exec-2:=[python_targets_python2_7(-)?,python_targets_python3_5(-)?,python_targets_python3_6(-)?,python_targets_python3_7(-)?,-python_single_target_python2_7(-),-python_single_target_python3_5(-),-python_single_target_python3_6(-),-python_single_target_python3_7(-)]']
dev-libs/libxml2/libxml2-2.9.9-r1.ebuild: RDEPEND: ~riscv(default/linux/riscv/17.0/rv64gc)
[     '>=dev-lang/python-exec-2:=[python_targets_python2_7(-)?,python …
```

repoman: check IUSE in _match_use for USE defaults (bug 685482)

---

lib/portage/dep/soname/multilib_category.py
lib/portage/util/elf/constants.py

In order to avoid possibe misidentification, only the following ABIs
are recognized:
* lp64
* lp64d
The compute_multilib_category function correctly identifies both
riscv_lp64 and riscv_lp64d files found in the experimental stages
from https://dev.gentoo.org/~dilfridge/stages/rv64gc-multilib/.
Bug: https://bugs.gentoo.org/686194
Reviewed-by: Andreas K. Hüttel <dilfridge@gentoo.org>

Recognize riscv ABIs (bug 686194)

---

bin/estrip

estrip: Fix inconsistent behavior between EAPI < 7 and EAPI >= 7.
Bug: https://bugs.gentoo.org/685532
Signed-off-by: Arfrever Frehtes Taifersar Arahesis <Arfrever@Apache.Org>

estrip: Fix inconsistent behavior between EAPI < 7 and EAPI >= 7

---

lib/portage/package/ebuild/_config/helper.py

Fix prune_incremental to preserve the last -*, since otherwise an
empty value would trigger fallback to a default value. This ensures
that `ACCEPT_LICENSE="-*"` behaves as intended.

Fix ACCEPT_LICENSE="-*" to behave as intended (bug 686406)

---

lib/portage/dbapi/porttree.py

If the file does not exist locally or the size is not correct,
use the file with the `.__download__` suffix to compute the
remaining_size to fetch.
Bug: https://bugs.gentoo.org/688124

portdbapi.getfetchsizes: use .__download__ suffix

---

bin/emerge-webrsync
cnf/repos.conf
lib/portage/package/ebuild/config.py
lib/portage/sync/modules/webrsync/webrsync.py
man/make.conf.5
misc/emerge-delta-webrsync

Enable sync-webrsync-verify-signature by default in repos.conf (due to
dependencies the ebuild will make this conditional on USE=rsync-verify
in the same way as the default sync-rsync-verify-metamanifest value).
Use a new PORTAGE_TEMP_GPG_DIR variable to distinguish indirect
emerge-webrsync calls that use gemato for secure key refresh, and
disable direct emerge-webrsync calls.
Deprecate FEATURES=webrsync-gpg and use it to trigger a
backward-compatibility mode where direct emerge-webrsync calls are
allowed (but trigger a warning message). Since direct emerge-webrsync
calls do not use gemato for secure key refresh, this behavior will
not be supported in a future release.
Bug: https://bugs.gentoo.org/689506

repos.conf: default sync-webrsync-verify-signature

---

bin/dispatch-conf

Bug: https://bugs.gentoo.org/690304

dispatch-conf: use writemsg for unicode safety (bug 690304)

---

tox.ini

lxml-4.4.0 does not support py34.

tox.ini: py34: lxml<4.4.0

---

bin/ebuild

Fix the following AttributeError error:
```
File "/usr/lib/python-exec/python3.6/ebuild", line 318, in <module>
type_name=pkg_type)
File "/usr/lib64/python3.6/site-packages/_emerge/Package.py", line 72, in __init__
db = self.cpv._db
AttributeError: 'str' object has no attribute '_db'
```
Bug: https://bugs.gentoo.org/532674
Fixes: bfe7892202b8 ("_pkg_str: add _db attribute (bug 640318)")

bin/ebuild: Fix to work with installed package

---

lib/portage/exception.py

For pypy 7.1 self.args is empty, triggering this IndexError:
```
File "<string>", line 53, in <module>
File "/usr/lib/pypy2.7/site-packages/_emerge/main.py", line 1289, in emerge_main
return run_action(emerge_config)
File "/usr/lib/pypy2.7/site-packages/_emerge/actions.py", line 3230, in run_action
emerge_config.args, spinner)
File "/usr/lib/pypy2.7/site-packages/_emerge/actions.py", line 2081, in action_uninstall
for i in e.args[0]:
IndexError: tuple index out of range
```
Bug: https://bugs.gentoo.org/692412

AmbiguousPackageName: initialize self.args for pypy compat

---

man/glsa-check.1
setup.py

In order to eliminate the [duplicate implementation from gentoolkit](https://github.com/gentoo/gentoolkit/pull/5),
install glsa-check into /usr/bin and add man page from gentoolkit.
Bug: https://bugs.gentoo.org/463952

glsa-check: install in /usr/bin (bug 463952)

---

bin/glsa-check
man/glsa-check.1

Add a glsa-check --quiet option which is compatible with gentoolkit's
glsa-check.
Bug: https://bugs.gentoo.org/692872

glsa-check: Forward port --quiet option from gentoolkit

---

lib/portage/sync/modules/rsync/rsync.py

Use the original hostname if it resolves to a single IP, since DNS
lookup must occur in the rsync process for compatibility with things
like proxychains that allocate a surrogate IP which is only valid
within the current process.
Bug: https://bugs.gentoo.org/693026

rsync: proxychains compatibility (bug 693026)

---

lib/portage/const.py
lib/portage/dbapi/bintree.py
man/make.conf.5

Trust that the PKGDIR index file is valid, meaning that no packages
have been manually added or removed since the last call to emaint --fix
binhost. This feature eliminates overhead involved with detection of
packages that have been manually added or removed, which significantly
improves performance in some cases, such as when PKGDIR resides on
a high-latency network file system.
Bug: https://bugs.gentoo.org/688902
@mattst88

Add FEATURES=pkgdir-index-trusted

---

lib/_emerge/actions.py
man/emerge.1

The emerge --changelog option is not very useful since the
gentoo repository no longer includes ChangeLog files.
Bug: https://bugs.gentoo.org/693096

emerge: deprecate --changelog option (bug 693096)

---

lib/_emerge/depgraph.py

Make backtracking continue as long as the backtracker has remaining
nodes to explore. This fixes a case where it would terminate prematurely
when the depgraph.need_restart() method returned False, even the the
backtracker had remaining nodes to explore.
Bug: https://bugs.gentoo.org/693242

_backtrack_depgraph: fix premature backtracking termination (bug 693242)

---

lib/_emerge/depgraph.py
lib/_emerge/resolver/backtracking.py
lib/portage/tests/resolver/test_slot_conflict_update_virt.py
lib/portage/tests/resolver/test_slot_operator_complete_graph.py
lib/portage/tests/resolver/test_slot_operator_runtime_pkg_mask.py

When a slot conflict occurs involving a package that is matched by all
involved parent atoms, consider masking the package in order to avoid
a possible missed update. The included unit test demonstrates the case
fixed by this patch. There are 2 previously existing unit tests that
require larger backtracking values in order to succeed with this patch,
since more possible solutions are now considered.
Bug: https://bugs.gentoo.org/692746

_slot_confict_backtrack: consider masking a package matched by all parent atoms (bug 692746)

---

bin/glsa-check

Use a regular expression to search for CVE ids in GLSA references.
Import unicode_literals from `__future__` since portage's Glsa class
returns unicode strings for all python versions.
Reported-by: Georg Weiss <gentoo@georgweiss.de>
Bug: https://bugs.gentoo.org/692134

glsa-check: fix truncated CVE ids in listmode (bug 692134)

---

bin/glsa-check
man/glsa-check.1

Add --reverse option which causes GLSAs to be listed in reverse order,
so that the most recent GLSAs are listed earlier.
Suggested-by: Pavel Sanda <ps@twin.jikos.cz>
Bug: https://bugs.gentoo.org/235970

glsa-check: add --reverse option (bug 235970)

---

lib/_emerge/depgraph.py
lib/portage/tests/resolver/test_aggressive_backtrack_downgrade.py

In order to suppress the sort of aggressive backtracking that can
trigger undesirable downgrades as in bug 693836, do not backtrack
for an unsatisfied dependency if there's an available package in
the runtime package mask which was involved in a slot conflict and
satisfied all involved parent atoms. Instead, discard the current
depgraph in favor of other backtracking configurations that may
exist. This case would not have been encountered prior to the fix
for bug 692746 which enabled backtracking for the type of slot
conflict that is detected here.
Fixes: 994ac00aa764 ("_slot_confict_backtrack: consider masking a package matched by all parent atoms (bug 692746)")
Bug: https://bugs.gentoo.org/693836

_add_dep: less aggressive backtracking (bug 693836)

---

cnf/sets/portage.conf
lib/portage/_sets/__init__.py
lib/portage/_sets/dbapi.py

Use a lib* glob to support SYMLINK_LIB=no.
Bug: https://bugs.gentoo.org/693980

x11-module-rebuild: support SYMLINK_LIB=no (bug 693980)

---

lib/_emerge/create_depgraph_params.py
lib/_emerge/depgraph.py
lib/_emerge/main.py
lib/portage/tests/resolver/test_autounmask.py
man/emerge.1

Add emerge --autounmask-license and --autounmask-use options which are
enabled by default, and disable package.keywords/mask changes by
default. For backward compatibility, previous behavior of
--autounmask=y and --autounmask=n is entirely preserved. Users can
get the old behavior simply by adding --autounmask to the make.conf
EMERGE_DEFAULT_OPTS variable.
Bug: https://bugs.gentoo.org/658648

Disable autounmask package.keywords/mask changes by default

---

lib/_emerge/main.py

Do not use parse_known_args to parse positional arguments, since that
causes unknown options to be handled like unknown positional arguments.
Bug: https://bugs.gentoo.org/673400

emerge: fix error message for unknown options (bug 673400)

---

lib/portage/package/ebuild/fetch.py

This avoids confusing "No such file or directory" errors as demonstrated
by the following test case:
```
$ ln -s /foo/bar /tmp/sudo-1.8.29rc1.tar.gz
$ wget http://distfiles.gentoo.org/distfiles/sudo-1.8.29rc1.tar.gz -O /tmp/sudo-1.8.29rc1.tar.gz
/tmp/sudo-1.8.29rc1.tar.gz: No such file or directory
```
Bug: https://bugs.gentoo.org/698046

fetch: remove symlink created by FETCHCOMMAND_RSYNC (bug 698046)

---

lib/portage/_emirrordist/DeletionTask.py
lib/portage/_emirrordist/FetchTask.py
lib/portage/tests/util/test_file_copier.py
lib/portage/util/_async/FileCopier.py

Use ForkExecutor to capture exceptions instead of showing
a full traceback. FileCopier callers will now be responsible
for displaying relevant exception messages.
Bug: https://bugs.gentoo.org/699400

emaint: clean up FileCopier exception logging

---

lib/portage/tests/util/test_file_copier.py
lib/portage/util/_async/FileCopier.py

Use native copyfile for zero-copy and sparse file support, and copy
permission bits like shutil.copy.

FileCopier: native zero-copy and sparse file support

---

lib/_emerge/Binpkg.py
lib/_emerge/Scheduler.py
lib/_emerge/actions.py
lib/_emerge/depgraph.py
lib/_emerge/main.py
lib/portage/dbapi/__init__.py
lib/portage/dbapi/bintree.py
lib/portage/dbapi/vartree.py
lib/portage/tests/emerge/test_simple.py
man/emerge.1

Enable use of installed packages directly as binary
packages. This is similar to using binary packages produced by
quickpkg(1), but installed packages are used directly as though
they are binary packages. This option only works in combination
with the --root=DIR option, and it comes with the caveat that
packages are only allowed to be installed into the root that
is specified by the --root=DIR option. The other root which
serves as a source of packages is assumed to be immutable
during the entire operation (similar to --buildpkgonly mode).
Default behavior for handling of protected configuration files
is controlled by the QUICKPKG_DEFAULT_OPTS variable. When a
configuration file is not included because it is protected, an
ewarn message is logged.
Suggested use cases:
* Install packages …

emerge: add --quickpkg-direct option

---

lib/_emerge/depgraph.py
lib/portage/tests/resolver/test_virtual_minimize_children.py

When disjunctive dependencies are queued, group together disjunctions
from the same dependency string so that any overlap between them will
trigger expansion to DNF.
Bug: https://bugs.gentoo.org/701996

_queue_disjunctive_deps: group disjunctions (bug 701996)

---

lib/_emerge/Scheduler.py
lib/_emerge/create_depgraph_params.py
lib/_emerge/depgraph.py
lib/_emerge/main.py
man/emerge.1

Assume that packages may have implicit dependencies on packages which
belong to the @system set. This option is enabled by default. One of
the effects of disabling this option is to allow the --jobs option
to spawn jobs without accounting for the possiblity of implicit
dependencies on packages that belong to the @system set (this causes
the @system set to behave more like the @profile set).
Bug: https://bugs.gentoo.org/681312

emerge: add --implicit-system-deps <y|n> option (bug 681312)

---

lib/_emerge/depgraph.py
lib/_emerge/resolver/slot_collision.py

Bug: https://bugs.gentoo.org/310009

emerge: Show package USE in conflict messages

---

bin/emerge-webrsync

Support gentoo-YYYYMMDD snapshots for forward compatibility, and
portage-YYYYMMDD snapshots for backward compatibility.
Bug: https://bugs.gentoo.org/693454

emerge-webrsync: support gentoo-YYYYMMDD snapshots

---

lib/portage/process.py

For example, the message will now look like this:
Unable to unshare: EPERM (for FEATURES="ipc-sandbox mount-sandbox network-sandbox pid-sandbox")
Bug: https://bugs.gentoo.org/680456

process: display relevant FEATURES when unshare fails

---

lib/_emerge/depgraph.py
lib/portage/dep/__init__.py
lib/portage/tests/dep/test_use_reduce.py
lib/portage/tests/resolver/test_with_test_deps.py

When USE=test is not enabled, allow circular test dependencies
by treating them like PDEPEND. When USE=test is enabled, circular
dependencies are still not allowed, as shown in unit tests.
Suggested-by: Michał Górny <mgorny@gentoo.org>
Bug: https://bugs.gentoo.org/703348

emerge --with-test-deps: allow circular deps

---

lib/_emerge/depgraph.py
lib/portage/tests/resolver/test_merge_order.py

Ensure that all members of a buildtime dependency cycle are merged
as a group, such that packages which depend on one or more members
of the group will only be merged *after* the entire group has been
merged.
This extends runtime cycle handling to also handle buildtime cycles
in cases where the buildtime dependencies happen to be satisfied by
installed packages. In situations when this is necessary, it is
desirable to rely on the old installed instances of these packages
as little as possible, since they might have been broken by the
upgrade of a package that is a member of the dependency cycle.
Upgrading members of the cycle as a group effectively minimizes
reliance on the old installed package instances, avoiding some cases
of bug 199856. For example, it should avoid bug 703676, where …

_serialize_tasks: limit scope of dropped circular dependencies

---

lib/portage/dep/dep_check.py
lib/portage/tests/resolver/test_circular_choices.py

Buildtime cycle breaking was not enabled in cases where
the all_in_graph variable was False, and this prevented the
pypy / pypy-exe dependency cycle from being broken as shown
in the test case for bug 705986. In order to break more
buildtime cycles, enable cycle breaking regardless of the
state of the all_in_graph variable.
Bug: https://bugs.gentoo.org/705986

dep_zapdeps: break more buildtime cycles (bug 705986)

---

bin/ebuild-helpers/dosym

According to PMS, dosym callers need to explicitly prefix the first
argument with ${EPREFIX} if that's desired.
https://bugs.gentoo.org/615594

dosym: revert deprecated prefix compat (bug 615594)

---

lib/portage/package/ebuild/_config/KeywordsManager.py

The /etc/portage/package.keywords file has been long deprecated
in favor of /etc/portage/package.accept_keywords. The file would
be useful if we could make it behave like package.keywords in
profiles (see bug 491166), but it's safest if we trigger a
UserWarning for some time before we change the meaning in a
future version of portage. The message looks like this:
UserWarning: /etc/portage/package.keywords is deprecated, use /etc/portage/package.accept_keywords instead
Bug: https://bugs.gentoo.org/491166
Bug: https://bugs.gentoo.org/607852

UserWarning if /etc/portage/package.keywords exists

---

lib/_emerge/depgraph.py
lib/portage/dep/dep_check.py
lib/portage/tests/resolver/test_or_choices.py
lib/portage/tests/resolver/test_or_upgrade_installed.py

Prefer choices that include a slot upgrade when appropriate, like for
the || ( llvm:10 ... llvm:7 ) case reported in bug 706278. In order
to avoid pulling in inappropriate slot upgrades, like those which
should only be pulled in with --update and --deep, add a want_update
flag to each choice which is True for choices that pull in a new slot
for which an update is desirable.
Mark the test case for bug 480736 as todo, since the "undesirable"
slot upgrade which triggers a blocker conflict in this test case is
practically indistinguishable from a desirable slot upgrade. This
particular blocker conflict is no longer relevant, since current
versions of media-libs/libpostproc are no longer compatible with
any available media-video/ffmpeg slot. In order to solve this test
case, some fancy …

dep_zapdeps: adjust || preference for slot upgrades (bug 706278)

---

lib/portage/dep/dep_check.py
lib/portage/tests/resolver/test_or_choices.py

For depclean actions, prefer choices where all packages have been
pulled into the graph, except for choices that eliminate upgrades.
This solves the test case for bug 707108, where depclean eliminated
a new slot of python that had been pulled in by a world update.
This should also prevent non-deterministic elimination of the
latest vala slot that was reported in bug 693790.
NOTE: There's a common perception (expressed in bug 705700) that
emerge is pulling in an "unecessary" python slot in cases when that
python slot is not enabled in PYTHON_TARGETS. However, the so-called
"unnecessary" slot is practically indistinguishable from a desirable
upgrade such as the missed llvm slot upgrade that was reported in
bug 706278. Therefore, be advised that emerge must pull in the
highest visible slot …

depclean: do not eliminate upgrades (bug 707108)

---

lib/portage/dep/dep_check.py
lib/portage/tests/resolver/test_or_choices.py

Prefer choices where all packages have been pulled into the
graph (except for choices that eliminate upgrades). This
logic must be consistent between both update and removal
(depclean) actions in order to avoid pulling in packages
only to have them removed by depclean, as reported in
bug 649622 for virtual/w3m.
Bug: https://bugs.gentoo.org/649622

dep_zapdeps: prefer choices with all in graph (bug 649622)

---

lib/portage/util/_dyn_libs/LinkageMapELF.py

In order to account for internal library resolution which a package
may implement (useful at least for handling of bundled libraries),
generate implicit runpath entries for any needed sonames which are
provided by the same owner package.
For packages that have bundled versions of system libraries, this will
prevent preserve-libs from unecessarily preserving system libraries as
reported in bug 705736. For the www-client/firefox-bin-72.0.2 package,
this adds an implicit /opt/firefox runpath entry to 15 files.
Bug: https://bugs.gentoo.org/705736

preserve-libs: generate implicit rpath for bundled libs (bug 705736)

---

lib/_emerge/actions.py
lib/_emerge/depgraph.py
lib/portage/tests/resolver/ResolverPlayground.py
lib/portage/tests/resolver/test_or_choices.py

Make depclean traverse dependencies in the same order as update
actions, in order to ensure consistency in decisions which are
dependent on the order of dependency evaluation due to inconsistent
use of || preferences in different packages.
In unit tests, update test_virtual_w3m_realistic to assert that
the order of graph traversal is deterministic and consistent
between update and removal (depclean) actions.
Bug: https://bugs.gentoo.org/649622

depclean: ensure consistency with update actions (bug 649622)

---

lib/_emerge/AbstractEbuildProcess.py
lib/_emerge/AsynchronousTask.py
lib/_emerge/CompositeTask.py
lib/_emerge/MiscFunctionsProcess.py
lib/_emerge/TaskSequence.py
lib/portage/tests/ebuild/test_doebuild_fd_pipes.py
lib/portage/tests/ebuild/test_doebuild_spawn.py
lib/portage/tests/ebuild/test_fetch.py
lib/portage/tests/ebuild/test_ipc_daemon.py
lib/portage/tests/ebuild/test_spawn.py
lib/portage/tests/lazyimport/test_lazy_import_portage_baseline.py
lib/portage/tests/locks/test_asynchronous_lock.py
lib/portage/tests/process/test_PopenProcess.py
lib/portage/tests/process/test_PopenProcessBlockingIO.py
lib/portage/tests/process/test_poll.py
lib/portage/tests/util/futures/test_iter_completed.py
lib/portage/tests/util/test_file_copier.py

Convert the _start method to an _async_start coroutine, since
eventually this method will need to be a coroutine in order to write
messages to the build log as discussed in bug 709746.

AbstractEbuildProcess: add _async_start coroutine (bug 709746)

---

lib/portage/tests/ebuild/test_doebuild_fd_pipes.py
lib/portage/tests/util/futures/test_iter_completed.py
lib/portage/util/_async/AsyncScheduler.py
lib/portage/util/futures/iter_completed.py

Convert AsyncScheduler to use the async_start method, since
eventually this method will need to be a coroutine in order to write
messages to the build log as discussed in bug 709746.
Also fix async_iter_completed to be compatible with callback
scheduling differences introduced by migration to the async_start
method.

AsyncScheduler: use async_start method

---

lib/_emerge/AbstractEbuildProcess.py
lib/_emerge/AsynchronousLock.py
lib/_emerge/AsynchronousTask.py
lib/_emerge/BinpkgExtractorAsync.py
lib/_emerge/BinpkgFetcher.py
lib/_emerge/EbuildBuildDir.py
lib/_emerge/EbuildFetcher.py
lib/_emerge/SpawnProcess.py
lib/portage/dbapi/bintree.py
lib/portage/tests/util/futures/test_iter_completed.py
lib/portage/util/_async/AsyncFunction.py
lib/portage/util/_async/FileDigester.py
lib/portage/util/futures/executor/fork.py

Convert SpawnProcess to use the async_start method, since
eventually this method will need to be a coroutine in order to write
messages to the build log as discussed in bug 709746.
Also update AbstractEbuildProcess, AsynchronousLock,
BinpkgExtractorAsync, BinpkgFetcher, EbuildFetcher,
IterCompletedTestCase, AsyncFunction, and FileDigester for
compatibility with SpawnProcess async_start.

SpawnProcess: use async_start method (bug 709746)

---

lib/portage/tests/process/test_PopenProcess.py
lib/portage/util/_async/PipeLogger.py

Add support to write to a non-blocking pipe instead of a
log file. This is needed for the purposes of bug 709746,
where PipeLogger will write to a pipe that is drained
by anoher PipeLogger instance which is running in the same
process.

PipeLogger: non-blocking write to pipe (bug 709746)

---

lib/_emerge/AbstractEbuildProcess.py
lib/_emerge/EbuildPhase.py
lib/_emerge/SpawnProcess.py
lib/portage/package/ebuild/_config/special_env_vars.py
lib/portage/util/_async/BuildLogger.py
lib/portage/util/_async/SchedulerInterface.py
man/make.conf.5

This variable specifies a command that filters build log output to a
log file. The plan is to extend this to support a separate filter for
tty output in the future.
In order to enable the EbuildPhase class to write elog messages to
the build log with PORTAGE_LOG_FILTER_FILE support, convert its _elog
method to a coroutine, and add a SchedulerInterface async_output
method for it to use.

Support PORTAGE_LOG_FILTER_FILE (bug 709746)

---

lib/_emerge/EbuildFetcher.py
lib/portage/package/ebuild/doebuild.py
lib/portage/package/ebuild/fetch.py

Drop privileges prior to fetch function calls, so that
all necessary operations can succeed when DISTDIR is
on NFS with root_squash enabled.
Bug: https://bugs.gentoo.org/601252

fetch: drop privileges early for NFS root_squash (bug 601252)

---

lib/_emerge/AsynchronousTask.py
lib/portage/tests/util/futures/test_compat_coroutine.py
lib/portage/util/futures/compat_coroutine.py

Throw asyncio.CancelledError in a cancelled coroutine, ensuring
that the coroutine can handle this exception in order to perform
any necessary cleanup (like close the log file for bug 711174).
Note that the asyncio.CancelledError will only be thrown in the
coroutine if there's an opportunity (yield) before the generator
raises StopIteration.
Also fix the AsynchronousTask exit listener handling for
compatibility with this new behavior.
Fixes: 8074127bbc21 ("SpawnProcess: add _main coroutine")

_GeneratorTask: throw CancelledError in cancelled coroutine (bug 711174)

---

lib/_emerge/SubProcess.py

Since the super class AbstractPollTask _async_wait method
calls _unregister, it can trigger premature _unregister before
pid status is available. Therefore, only call the super class
_async_wait method after pid status is available. This should
help prevent premature _unregister events that trigger reading
of build logs before they're closed as in bug 658806 and
bug 711174.

Subprocess: delay unregister in _async_wait (bug 711174)

---

lib/_emerge/SequentialTaskQueue.py

Use addExitListener to add a _task_exit callback that will be invoked
as soon as the task exits (before the future's done callback is called).
This is required in order for bool(self) to have an updated value for
Scheduler._schedule to base assumptions upon. Delayed updates to
bool(self) is what caused Scheduler to hang as in bug 711322.
This reverts changes in SequentialTaskQueue task queue exit listener
behavior from commit c7e52d046621, so that only the changes necessary
to support async_start remain.
Fixes: c7e52d046621 ("EbuildPhase: add _async_start coroutine")

SequentialTaskQueue: update bool(self) sooner (bug 711322)

---

lib/_emerge/AsynchronousTask.py

Schedule start listeners via call_soon, in order to avoid callback races
like the SequentialTaskQueue exit listener race that triggered bug
711322. Callbacks scheduled via call_soon are placed in a fifo queue,
ensuring that they execute in an order that is unsurprising relative to
other callbacks.

AsynchronousTask: schedule start listeners via call_soon (bug 711322)

---

lib/_emerge/AsynchronousTask.py
lib/portage/tests/util/futures/test_done_callback_after_exit.py

When addExistListener is called after the task has already exited with
a returncode, immediately schedule the listener to be invoked via
call_soon.This behavior is similar to the Future add_done_callback
method.

AsynchronousTask: handle addExistListener after exit

---

lib/_emerge/AbstractPollTask.py
lib/_emerge/CompositeTask.py
lib/_emerge/FifoIpcDaemon.py
lib/_emerge/SubProcess.py

Simplify all AsynchronousTask subclasses to use the default
isAlive implementation, which returns True if self.returncode
is not None. This fixes cases where the method would erroneously
return False, leading to issues like bug 711688, where the
CompositeTask isAlive implementation returned False for a
BinpkgPrefetcher instance that was still in the process of
starting via its async_start method.
Fixes: d66e9ec0b105 ("AsynchronousTask: add coroutine async_start method")
Bug: https://bugs.gentoo.org/711688

AsynchronousTask: simplify isAlive (bug 711688)

---

lib/_emerge/AsynchronousTask.py
lib/portage/tests/util/futures/test_done_callback_after_exit.py

When addStartListener is called after the task has already exited with
a returncode, immediately schedule the listener to be invoked via
call_soon. This behavior is similar to the Future add_done_callback
method (and addExitListener since commit 5d476c4e5002).

AsynchronousTask: handle addStartListener after exit (bug 711322)

---

lib/_emerge/CompositeTask.py
lib/_emerge/SequentialTaskQueue.py

When the clear method is called, cancel any tasks which have not
started yet, in order to ensure that their start/exit listeners are
called. This fixes a case where emerge would hang after SIGINT.
Also fix the CompositeTask _cancel method to react appropriately to
the cancel event when the task has not started yet.

SequentialTaskQueue: cancel unstarted tasks when appropriate (bug 711322)

---

lib/_emerge/depgraph.py
lib/portage/tests/resolver/test_depth.py

Fix the _wrapped_select_pkg_highest_available_imp method to select an
installed package when appropriate for the current --deep=<depth>
setting, even with --update enabled. This prevents violation of the
current --deep=<depth> setting in cases where an installed package
which satisfies a dependency is masked for any reason.
Bug: https://bugs.gentoo.org/712298

depgraph: respect --deep=<depth> with --update (bug 712298)

---

lib/portage/util/compression_probe.py

Omit the zstd --long=31 argument for decompression on 32-bit
architectures, since the latest version of zstd will otherwise
abort with an error on 32-bit architectures.
Bug: https://bugs.gentoo.org/710444
Bug: https://bugs.gentoo.org/634980

compression_probe: omit zstd --long=31 on 32-bit arch (bug 710444)

---

bin/isolated-functions.sh

Make eqwarn output to the build log regardless of --quiet, via echo
to stderr instead of __vecho. This __vecho usage was originally
introduced in commit c53f52941c88, which was during the time when
build output went to the tty regardless of --quiet mode (that
changed in commit 0398470e5029).
Bug: https://bugs.gentoo.org/713818

eqawarn: output to build log regardless of --quiet (bug 713818)

---

lib/portage/package/ebuild/doebuild.py

Ensure that the userpriv UID has appropriate permission for files
created in $HOME during privileged phases like pkg_setup, in the
same way as for $T. This prevents potential permission issues for
programs invoked during unprivileged phases, and it improves
alignment with PMS which specifies identical behavior for both
$HOME and $T.
Bug: https://bugs.gentoo.org/713100

_post_phase_userpriv_perms: handle $HOME (bug 713100)

---

lib/portage/package/ebuild/fetch.py

Adjust the regular expression to avoid overly-greedy .+ groups,
so that is will properly replace all occurrences, as necessary
for the purposes of bug 713726 since PORTAGE_BINHOST may contain
multiple values.
Bug: https://bugs.gentoo.org/713726

_hide_url_passwd: replace all occurrences (bug 713726)

---

bin/misc-functions.sh
lib/portage/util/_dyn_libs/LinkageMapELF.py

For dynamic libraries, infer an implicit DT_SONAME setting from the
file basename, which is consistent with dynamic linking behavior in
practice. This makes it possible to resolve soname dependencies for
musl's libc.so which lacks a DT_SONAME setting.
Bug: https://bugs.gentoo.org/715162

NeededEntry: infer implicit soname from file basename (bug 715162)

---

lib/_emerge/Scheduler.py
lib/_emerge/SequentialTaskQueue.py

Add a wakeup callback to schedule a new merge when the merge queue
becomes empty. This prevents the scheduler from hanging in cases
where the order of _merge_exit callback invocation may cause the
the merge queue to appear non-empty when it is about to become
empty.
Bug: https://bugs.gentoo.org/716636

Scheduler: wakeup for empty merge queue (bug 711322)

---

lib/_emerge/depgraph.py
lib/portage/tests/resolver/test_slot_operator_reverse_deps.py

When searching for slot operator rebuilds, respect non slot-operator
components of parent dependencies, so that a <foo-version:= dependency
like the <dev-libs/libgit2-1:0=[ssh?] dependency from bug 717140 will
not be completely ignored. This will prevent erroneous attempts to
trigger slot operator rebuilds for upgrades that would break
<foo-version:= dependencies (which triggered upgrade/downgrade loops
when backtracking tried to resolve the breakage).
Fixes: d569a2d7275c ("_slot_operator_update_probe: fix bug #508762")
Bug: https://bugs.gentoo.org/717140

depgraph: respect <foo-version:= for slot operator rebuild (bug 717140)

---

lib/portage/cache/template.py
lib/portage/tests/dbapi/test_auxdb.py

Fix this AuxdbTestCase failure for anydbm:
```
test_anydbm (portage.tests.dbapi.test_auxdb.AuxdbTestCase) ... Exception in callback None()
handle: <Handle cancelled>
File "/usr/lib64/python3.6/asyncio/events.py", line 145, in _run
self._callback(*self._args)
File "lib/_emerge/EbuildMetadataPhase.py", line 143, in _output_handler
self._async_waitpid()
File "lib/_emerge/SubProcess.py", line 60, in _async_waitpid
add_child_handler(self.pid, self._async_waitpid_cb)
File "/usr/lib64/python3.6/asyncio/unix_events.py", line 873, in add_child_handler
self._do_waitpid(pid)
File "/usr/lib64/python3.6/asyncio/unix_events.py", line 919, in _do_waitpid
callback(pid, returncode, *args)
File "lib/_emerge/EbuildMetadataPhase.py", line 207, in _async_waitpid_cb …
```

anydbm: avoid interference between cleanse_keys and _eclasses_

---

cnf/make.globals

The ebuild will have a default enabled USE=zstd which changes the
default to zstd here.
Bug: https://bugs.gentoo.org/715108
Bug: https://bugs.gentoo.org/719456

make.globals: add default BINPKG_COMPRESS setting (bug 715108)

---

bin/misc-functions.sh
lib/portage/util/_dyn_libs/LinkageMapELF.py
lib/portage/util/_dyn_libs/NeededEntry.py

We don't use scanelf -q, since that would omit libraries like
musl's /usr/lib/libc.so which do not have any DT_NEEDED or
DT_SONAME settings. Since we don't use scanelf -q, we have to
handle the special rpath value "  -  ".
Bug: https://bugs.gentoo.org/721336
Fixes: 25fbe7bc1a92 ("NeededEntry: infer implicit soname from file basename (bug 715162)")

NeededEntry: don't use scanelf -q (bug 721336)

---

.travis.yml
cnf/make.globals
lib/portage/_compat_upgrade/binpkg_compression.py
lib/portage/tests/resolver/ResolverPlayground.py
man/make.conf.5

This includes a _compat_upgrade.binpkg_compression script that the
ebuild can call in pkg_preinst in order to maintain a backward-compatible
bzip2 default when appropriate, ensuring that binary package consumers
are not caught off guard.
Bug: https://bugs.gentoo.org/715108

Default BINPKG_COMPRESSION to zstd (bug 715108)

---

bin/ecompress

Ignore files passed to docompress -x in the QA check for
precompressed files.
Bug: https://bugs.gentoo.org/721516

ecompress: ignore docompress -x files in precompressed QA check (bug 721516)

---

lib/portage/dbapi/porttree.py

When processing category listdir results, do not use os.path.isdir to
identify packages, in order to avoid unecessary stat calls. Instead,
use the Atom class to validate package names. This may cause creation
of some cache entries for non-packages, but it will not do any harm
since these entries will never be accessed via the `__getitem__` method.
Bug: https://bugs.gentoo.org/725934

_better_cache._scan_cat: avoid stat calls (bug 725934)

---

lib/portage/repository/config.py
lib/portage/sync/syncbase.py
man/portage.5

Add a sync-openpgp-key-refresh option that makes it possible to
disable key refresh, which may be useful in cases when it is not
possible to refresh keys.
Key refresh is enabled by default, and if it is disabled then
the SyncBase._refresh_keys method will output an ewarn message
like this when the --quiet option is not enabled:
* Key refresh is disabled via a repos.conf sync-openpgp-key-refresh
* setting, and this is a security vulnerability because it prevents
* detection of revoked keys!
Bug: https://bugs.gentoo.org/661518

repos.conf: add bool sync-openpgp-key-refresh option (bug 661518)

---

lib/_emerge/AbstractEbuildProcess.py
lib/_emerge/BinpkgFetcher.py
lib/_emerge/EbuildFetcher.py
lib/_emerge/EbuildPhase.py
lib/_emerge/SpawnProcess.py
lib/portage/dbapi/_MergeProcess.py
lib/portage/package/ebuild/_config/special_env_vars.py
lib/portage/util/_async/BuildLogger.py
lib/portage/util/_async/SchedulerInterface.py
man/make.conf.5

This variable specifies a command that filters build log output to a
log file. The plan is to extend this to support a separate filter for
tty output in the future.
In order to enable the EbuildPhase class to write elog messages to
the build log with PORTAGE_LOG_FILTER_FILE_CMD support, convert its
_elog method to a coroutine, and add a SchedulerInterface async_output
method for it to use.
Use a new BuildLogger class to manage log output (with or without a
filter command), with compression support provided by PipeLogger.
BuildLogger has a stdin property which provides access to a writable
binary file stream (refers to a pipe) that log content is written to.

Support PORTAGE_LOG_FILTER_FILE_CMD (bug 709746)

---

lib/portage/util/futures/_asyncio/process.py
lib/portage/util/futures/_asyncio/streams.py

In the coroutine finally clause, do not call remove_writer in cases
where fd has been closed and then re-allocated to a concurrent
coroutine as in bug 716636.
Also, assume that the caller will put the file in non-blocking mode
and close the file when done, so that this function is suitable for
use within a loop.
Bug: https://bugs.gentoo.org/728580

_writer: fix unsafe finally clause (bug 728580)

---

bin/ecompress

Use sed -f to feed commands to sed via stdin, in order to avoid
the "Argument list too long" error reported in bug 727522.
Fixes: 5508bf7a6db5 ("ecompress: ignore docompress -x files in precompressed QA check (bug 721516)")
Bug: https://bugs.gentoo.org/727522

ecompress: fix "Argument list too long" for sed (bug 727522)

---

bin/ecompress
lib/portage/tests/resolver/ResolverPlayground.py

Use sort and comm with temporary files in order to compare lists
of docompress -x and precompressed files, since the file lists
can be extremely large. Also strip ${D%/} from paths in order to
reduce length.
Bug: https://bugs.gentoo.org/721516
Suggested-by: Robin H. Johnson <robbat2@gentoo.org>

ecompress: optimize docompress -x precompressed comparison

---

.travis.yml
repoman/setup.py
setup.py
tox.ini

It should be pretty safe to drop support for python2.7 at this point.
Bug: https://bugs.gentoo.org/731114

travis.yml: drop python 2.7 (bug 731114)

---

lib/portage/dep/__init__.py
lib/portage/versions.py

Each of these functions is called repeatedly with the same arguments
many times. Cache sizes were selected to minimize memory use increase,
while still providing about the same speedup compared to a cache with
unbounded size. "emerge -uDvpU --with-bdeps=y @world" runtime decreases
from 44.32s -> 29.94s -- a 48% speedup, while the maximum value of the
RES column in htop increases from 280 MB -> 290 MB.
"emerge -ep @world" time slightly decreases from 18.77s -> 17.93, while
max observed RES value actually decreases from 228 MB -> 214 MB (similar
values observed across a few before/after runs).
Bug: https://bugs.gentoo.org/732378

Add caching to use_reduce, vercmp, and catpkgsplit

---

lib/portage/tests/bin/setup_env.py

This solves doins test failures triggered in travis-ci when doins
executed with /usr/bin/python instead of PORTAGE_PYTHON.

BinTestCase: export PORTAGE_PYTHON

---

lib/portage/util/_desktop_entry.py

The message has changed in desktop-file-utils-0.25.
See: https://gitlab.freedesktop.org/xdg/desktop-file-utils/-/commit/e935a1b0c300d8fc97661e01a8200af14876e627
Bug: https://bugs.gentoo.org/733154

validate_desktop_entry: update _trivial_warnings regex (bug 733154)

---

lib/portage/process.py
lib/portage/sync/controller.py
lib/portage/util/_async/ForkProcess.py

Replace os.fork with multiprocessing.Process, in order to leverage
any pre-fork and post-fork interpreter housekeeping that it provides,
promoting a healthy state for the forked interpreter.
Since multiprocessing.Process closes `sys.__stdin__`, fix relevant
code to use the portage._get_stdin() compatibility function.
In case there's a legitimate need to inherit stdin for things like
PROPERTIES=interactive support, create a temporary duplicate of
fd_pipes[0] when appropriate, and restore sys.stdin and `sys.__stdin__`
in the subprocess.
Bug: https://bugs.gentoo.org/730192

ForkProcess: replace os.fork with multiprocessing.Process (bug 730192)

---

lib/portage/tests/ebuild/test_fetch.py

Reported-by: Sam James <sam@gentoo.org>

EbuildFetchTestCase: fix PORTAGE_DEPCACHEDIR leakage from calling env

---

lib/portage/dbapi/_MergeProcess.py

Since ForkProcess now receives process exit status in the
_proc_join_done method instead of the _async_waitpid_cb method,
MergeProcess needs to handle RETURNCODE_POSTINST_FAILURE there
instead.
Fixes: 3561071e07ad ("MergeProcess: replace os.fork with multiprocessing.Process (bug 730192)")

MergeProcess: handle RETURNCODE_POSTINST_FAILURE in _proc_join_done

---

lib/portage/repository/storage/hardlink_rcu.py
lib/portage/tests/sync/test_sync_local.py

If SyncManager.pre_sync creates an empty directory where
self._latest_symlink is suppose to be (which is normal if
sync-rcu-store-dir has been removed), then we need to remove
the directory or else rename will raise IsADirectoryError
when we try to replace the directory with a symlink.

HardlinkRcuRepoStorage: handle removed sync-rcu-store-dir (bug 734990)

---

pylintrc
setup.py
tox.ini

In addition to checking the whole repo, this fixes the
import-error check.

tox: call pylint for whole repo

---

lib/_emerge/BinpkgEnvExtractor.py
lib/portage/dbapi/vartree.py

Do not write to log file when in a MergeProcess subprocess,
since stdout and stderr are already redirected to the log
file by MergeProcess. This fixes log corruption when
BinpkgEnvExtractor is use to extract environment.bz2 prior
to pkg_prerm.

BinpkgEnvExtractor: fix subprocess logfile usage (bug 711174)

---

lib/portage/__init__.py
lib/portage/cache/sqlite.py
lib/portage/tests/dbapi/test_auxdb.py
lib/portage/tests/process/test_AsyncFunction.py

Use a separate connection instance for each pid, since
it is not safe to use a connection created in a parent
process.
See: https://www.sqlite.org/howtocorrupt.html
Bug: https://bugs.gentoo.org/736334

sqlite: fork safety (bug 736334)

---

cnf/repo.postsync.d/example

Add an egencache --update-pkg-desc-index example for users
of app-portage/esearch to migrate to.
Bug: https://bugs.gentoo.org/735626

cnf/repo.postsync.d/example: add egencache --update-pkg-desc-index (bug 735626)

---

lib/portage/xml/metadata.py

Tolerate broken or missing xml support in python.
This reverts a behavior change from commit
935c47d972d986f1822850618442c19c97e300c3.
Fixes: 935c47d972d9 ("lib/portage/xml/metadata.py: fix ungrouped-imports w/refactor")
Bug: https://bugs.gentoo.org/736912

lib/portage/xml/metadata.py: tolerate xml.parsers.expat import failures (bug 736912)

---

repoman/lib/repoman/argparser.py
repoman/lib/repoman/modules/scan/depend/profile.py
repoman/man/repoman.1

Add --jobs and --load-average options which allow dependency checks
for multiple profiles to run in parallel. The increase in performance
is non-linear for the number of jobs, but it can be worthwhile
(I measured a 35% decrease in time when running 'repoman -j8 full'
on sys-apps/portage). For the -j1 case (default), all dependency
checks run in the main process as usual, so there is no significant
performance penalty for the default case.
Bug: https://bugs.gentoo.org/448462

repoman: Add --jobs and --load-average options (bug 448462)

---

lib/portage/util/futures/iter_completed.py

Do not attempt to wait for the TaskScheduler instance in the finally
clause, since it will always raise InvalidStateError if its status
is not available yet (which is normal if it has remaining tasks with
done callbacks that have not been scheduled yet).
Bug: https://bugs.gentoo.org/738766

async_iter_completed: fix InvalidStateError in finally clause (bug 738766)

---

lib/_emerge/depgraph.py
lib/portage/tests/resolver/test_slot_change_without_revbump.py
lib/portage/tests/resolver/test_slot_conflict_rebuild.py

After a slot conflict occurs, allow the highest version to be eliminated
from the graph when appropriate. This is needed for correct behavior in
cases the highest version cannot be installed because an older version
is required by some package. This reverts a change related to bug 531656
from commit a9064d08ef4c92a5d0d1bfb3dc8a01b7850812b0, and that change
no longer appears to be necessary, since the unit tests related to bug
531656 now pass without it.
Due to this change in slot conflict handling, the --changed-slot test
case related to bug 456208 will now fail unless we use an @world update to
trigger rebuilds, therefore fix it to do so.
Bug: https://bugs.gentoo.org/439688

dephgraph: Allow elimination of highest version after slot conflict (bug 439688)

---

lib/_emerge/actions.py
lib/_emerge/main.py
lib/_emerge/search.py
man/emerge.1

Automatically detect regular expressions when the search string
contains any of these regular expression characters or character
sequences:
^ $ * [ ] { } | ? .+
This simplifies usage, so that users no longer have to remember
to prefix regular expressions with the % character. The new
behavior can be disabled by --regex-search-auto=n, in case the
regular expressions interpretation causes some kind of problem.
Note that fuzzy search and regular expression search are
mutually exclusive, and fuzzy search remains the default for
search strings that do not contain any regular expression
characters.
Bug: https://bugs.gentoo.org/737480

emerge --search: auto-detect regular expressions (bug 737480)

---

bin/egencache
cnf/repo.postsync.d/example
man/egencache.1

When the --verbose flag is given, make --update-pkg-desc-index emulate
esync --verbose output. Example:
```
* Searching for changes
[ N] acct-group/ultimaker (0):  Group for ultimaker
[ N] acct-user/ultimaker (0):  User for ultimaker
[ U] www-client/opera (70.0.3728.144):  A fast and secure web browser
[MU] www-client/opera-developer (72.0.3798.0):  A fast and secure web browser
[ U] x11-libs/gtksourceview (4.6.1-r1):  A text widget implementing syntax highlighting and other features
```
Bug: https://bugs.gentoo.org/737470

egencache --update-pkg-desc-index: emulate esync --verbose output (bug 737470)

---

lib/portage/package/ebuild/config.py
man/make.conf.5

Bug: https://bugs.gentoo.org/740588
Signed-off-by: Arfrever Frehtes Taifersar Arahesis <Arfrever@Apache.Org>

make.conf: Treat __* variables as local and do not propagate them.

---

lib/_emerge/BinpkgFetcher.py
lib/_emerge/actions.py
lib/portage/binrepo/config.py
lib/portage/const.py
lib/portage/dbapi/bintree.py
lib/portage/tests/emerge/test_simple.py
man/make.conf.5
man/portage.5

Support /etc/portage/binrepos.conf as a replacement for the
PORTAGE_BINHOST variable. Behavior is similar to repos.conf,
initially supporting just the sync-uri attribute. Both binrepos.conf
and PORTAGE_BINHOST can be used simultaneously, in the same way that
repos.conf and PORTDIR_OVERLAY can be used simultaneously.
The emerge --info output for binrepos.conf looks like this:
```
Binary Repositories:
example-binhost
sync-uri: https://example.com/binhost
```
Support customization of fetchcommand and resumecommand in
binrepos.conf, allowing customized authentication mechanisms for
each repository.

Add binrepos.conf to support fetchcommand customization (bug 668302)

---

lib/portage/_selinux.py

Encode path arguments as UTF-8, like portage.os wrapper.
Fixes: 6137290b2bb8 ("selinux: python3 unicode paths, bug #430488")
Bug: https://bugs.gentoo.org/741194

selinux: encode os path arguments as UTF-8 (bug 741194)

---

lib/portage/package/ebuild/fetch.py

It's necessary to use urlquote for correct behavior with ftp, http,
and https, since it's possible for file names to contain percent
encoded characters that need to be protected by an additional layer
of percent encoding. For other protocols such as sftp and rsync,
all characters are interpreted literally, so urlquote must not be
used.
Fixes: c238d5f7ed264179c263f5a2da983c4ee50b4f00
Bug: https://bugs.gentoo.org/719810
Bug: https://bugs.gentoo.org/741474

get_mirror_url: urlquote only for ftp, http, and https (bug 741474)

---

bin/egencache
cnf/repo.postsync.d/example
man/egencache.1

The --external-cache-only option is useful for client-side
use cases where writing cache files inside the repository itself
may interfere with repository verification. This option is
currently supported for --update and --update-pkg-desc-index
actions, for which consumers of the corresponding cache or
index files are already capable of consuming files from the
external cache directory (/var/cache/edb/dep).
Bug: https://bugs.gentoo.org/737470

egencache: add --external-cache-only option (bug 737470)

---

lib/portage/dep/soname/multilib_category.py

Bug: https://bugs.gentoo.org/742446

Recognize riscv_{ilp32,ilp32d} ABIs

---

lib/_emerge/depgraph.py
lib/portage/tests/resolver/test_slot_operator_missed_update.py

Prefer choices that minimize conflict atoms, so that choices
which satisfy all parents are preferred. This reduces the
minimum necessary backtrack tries from 21 to 7 for the unit
test related to bug 743115.
Bug: https://bugs.gentoo.org/743115
Bug: https://bugs.gentoo.org/743631

_slot_confict_backtrack: minimize conflict atoms (bug 743631)

---

lib/_emerge/depgraph.py
lib/_emerge/resolver/backtracking.py
lib/portage/tests/resolver/test_slot_operator_missed_update.py

When a slot conflict occurs due to a missed update, and some other
similar update(s) are available, add the similar update(s) to the
runtime package mask for the same backtracking choice. This reduces
minimum number of backtrack tries required to solve the test case
for bug 743115 from 7 to 4, where the difference of 3 corresponds
to the number of other similar setuptools updates available.
Bug: https://bugs.gentoo.org/743115

_slot_confict_backtrack: group similar missed updates (bug 743115)

---

lib/_emerge/Scheduler.py

Execute pkg_pretend phases in a coroutine while parallel-fetch
is running concurrently. When it's time to execute the pkg_pretend
phase for a remote binary package, use a Scheduler _get_prefetcher
method to get a running prefetcher if available, and otherwise
start a new fetcher.
Since pkg_pretend phases now run inside of the --keep-going retry
loop, --keep-going is now able to recover from pkg_pretend
failures, which fixes bug 404157.
Bug: https://bugs.gentoo.org/404157
Bug: https://bugs.gentoo.org/710432

emerge: enable parallel-fetch during pkg_pretend (bug 710432)

---

bin/pid-ns-init

For correct operation of Ctrl+Z, forward SIGTSTP and SIGCONT
to all sandboxed pids.
Fixes: 37e4dc5ae842 ("pid-sandbox: pid-ns-init setsid support (bug 675870)")
Bug: https://bugs.gentoo.org/704498

pid-sandbox: Forward SIGTSTP and SIGCONT (bug 704498)

---

lib/_emerge/actions.py
lib/_emerge/depgraph.py
lib/_emerge/main.py
lib/portage/tests/emerge/test_simple.py
man/emerge.1

Specify the root to use as the --quickpkg-direct package source. This
root is assumed to be immutable during the entire emerge operation.
The default is set to "/".
Bug: https://bugs.gentoo.org/752066

emerge: add --quickpkg-direct-root option

---

lib/portage/tests/resolver/test_slot_operator_bdeps.py

Test these two distinct cases:
1) Regular dev-lang/go upgrade, with rebuild of packages that
have dev-lang/go:= in BDEPEND.
2) Rebuild of packages that have dev-lang/go:= in BDEPEND, after
the built slot operator deps have already been broken by an
earlier dev-lang/go upgrade.
Bug: https://bugs.gentoo.org/752153

Add slot operator := BDEPEND unit tests for bug 752153

---

lib/portage/package/ebuild/_config/LocationsManager.py
lib/portage/package/ebuild/deprecated_profile_check.py

According to PMS, a deprecated profile warning is not inherited. Since
the current profile node may have been inherited by a user profile
node, the deprecation warning may be relevant even if it is not a
top-level profile node. Therefore, consider the deprecated warning
to be irrelevant when the current profile node belongs to the same
repo as the previous profile node.
Bug: https://bugs.gentoo.org/753497

emerge: Disable profile deprecation warning inheritance (bug 753497)

---

lib/_emerge/DepPriorityNormalRange.py
lib/_emerge/DepPrioritySatisfiedRange.py
lib/_emerge/depgraph.py
lib/portage/tests/resolver/test_merge_order.py

Enhance the find_smallest_cycle function to prioritize its
search so that it will minimize the use of installed packages
to break cycles. When installed packages must be used to
break cycles, it will now prefer to do this for runtime
dependencies over buildtime dependencies, since it's
preferable to build against latest versions of buildtime
dependencies whenever possible. This should solve some cases
of bug 199856 which have been triggered by unsafe reliance
on installed packages to break cycles.
The included unit test case demonstrates correct merge order
for a dependency calculation involving 6 independent cycles.
This test case fails with the master branch, due to a buildtime
dependency cycle of 3 packages being merged earlier than cycles
of 2 packages. We can generalize this to say …

find_smallest_cycle: enhance search prioritization

---

lib/portage/dep/dep_check.py

Fix virtual choices to be consistent with circular dependency
backtracking choices.
Fixes: f78a91e44e3e ("backtracking: adjust || preference to break dependency cycles")
Bug: https://bugs.gentoo.org/757306

backtracking: fix virtual choices for circular deps (bug 757306)

---

lib/_emerge/depgraph.py
lib/portage/dep/dep_check.py
lib/portage/tests/resolver/test_circular_choices_rust.py

If a package has a buildtime dependency on a previous version that
it will replace, then do not treat it as a slot conflict. This
solves inappropriate behavior for dev-lang/rust[system-bootstrap].
This requires adjustments to package selection logic in several
locations, in order to ensure that an installed package instance
will be selected to satisfy a buildtime dependency when
appropriate. Dependencies of the installed package will be
entirely ignored, but that has already been the case when using
installed package to break cycles, as discussed in bug 199856.
Bug: https://bugs.gentoo.org/756961

Allow a package to replace its own buildtime dependency

---

lib/_emerge/DepPrioritySatisfiedRange.py
lib/_emerge/depgraph.py
lib/portage/tests/resolver/test_merge_order.py

After PDEPENDs have been neglected by the find_smallest_cycle function,
do not try to merge them too early if they are already satisfied by
an installed package. This fixes incorrect merge order for PDEPEND
cycles involving xorg-server and xorg-drivers, which was triggered
by commit 5095c2023595a75e2848f1ad3dbe25b5fb451a44 because it gave PDEPEND higher priority than
satisfied buildtime dependencies.
Fixes: 5095c2023595 ("find_smallest_cycle: enhance search prioritization")
Reported-by: josef64 in #gentoo-portage
Bug: https://bugs.gentoo.org/754903

find_smallest_cycle: don't merge satisfied PDEPEND too early

---

lib/portage/__init__.py
lib/portage/util/_eventloop/global_event_loop.py

Use the default asyncio event loop implementation in child
processes, instead of portage's internal EventLoop. After
fork, force instantiation of a new event loop policy as
a workaround for https://bugs.python.org/issue22087, which
is necessary for RetryTestCase to succeed.
Bug: https://bugs.gentoo.org/758740

Use default asyncio event loop implementation in child processes

---

lib/portage/util/_eventloop/asyncio_event_loop.py
lib/portage/util/futures/_asyncio/__init__.py

Make the _safe_loop function return an AsyncioEventLoop instance,
so that the default asyncio event loop implementation will be used
in API consumer threads. This is possible because the underlying
asyncio.get_event_loop() function returns a separate  event loop for
each thread. The AsyncioEventLoop _run_until_complete method will
now appropriately handle a ValueError from signal.set_wakeup_fd(-1)
if it is not called in the main thread.
For external API consumers calling from a non-main thread, an
asyncio loop must be registered for the current thread, or else an
error will be raised like this:
RuntimeError: There is no current event loop in thread 'Thread-1'.
In order to avoid this RuntimeError, the external API consumer
is responsible for setting an event loop and managing its …

Use default asyncio event loop implementation in API consumer threads

---

.github/workflows/ci.yml

This will be the new default soon.
See: https://github.com/actions/virtual-environments/issues/1816

ci: upgrade workflow to ubuntu-20.04

---

lib/portage/tests/util/futures/test_retry.py

Cancel pending futures in order to avoid this "Task was destroyed but
it is pending!" warning message following migration to PEP 492
coroutines with async and await syntax:
```
testHangForever (portage.tests.util.futures.test_retry.RetryForkExecutorTestCase) ... ok
testHangForever (portage.tests.util.futures.test_retry.RetryTestCase) ... ok
testHangForever (portage.tests.util.futures.test_retry.RetryThreadExecutorTestCase) ... ok
----------------------------------------------------------------------
Ran 3 tests in 0.839s
OK
Task was destroyed but it is pending!
task: <Task cancelling name='Task-4' coro=<HangForever.__call__() running at portage/tests/util/futures/test_retry.py:58> wait_for=<Future cancelled> cb=[RetryForkExecutorTestCase._wrap_coroutine_func.<locals>.wrapper.<locals>.done_ …
```

test_retry: use context manager to cancel pending futures

---

lib/_emerge/depgraph.py
lib/portage/tests/resolver/test_slot_operator_reverse_deps.py

If an atom is the result of virtual expansion, then derefrence it to
_orig_atom in check_reverse_dependencies so that it will be correctly
handled as a built slot operator dependency when appropriate. This
solves a case triggered in bug 764764 where a virtual expansion from
virtual/dist-kernel:0/5.10.5= to =virtual/dist-kernel-5.10.5 prevented
the atom from being handled as a built slot operator dependency, which
prevented rebuilds from being triggered.
Bug: https://bugs.gentoo.org/764764

check_reverse_dependencies: deref virtual expansion (bug 764764)

---

lib/portage/util/_eventloop/global_event_loop.py
lib/portage/util/futures/_asyncio/__init__.py

Like asyncio.get_event_loop(), return the running loop for the
current thread if there is one, and otherwise construct a new
one if needed. This allows the _safe_loop function to become
synonymous with the global_event_loop function.
For the case of "loop running in non-main thread" of API
consumer, this change makes portage compatible with PEP
492 coroutines with async and await syntax. Portage
internals can safely begin using async / await syntax instead
of compat_coroutine.
Bug: https://bugs.gentoo.org/763339

global_event_loop: return running loop for current thread

---

lib/portage/dbapi/bintree.py

Omit the filename argument for the binarytree.inject method
in aux_update, since an in-place update is desired, and the
filename argument causes the file to be renamed when
binpkg-multi-instance is enabled.
Fixes: 328dd4712f88 ("binpkg-multi-instance 3 of 7")
Bug: https://bugs.gentoo.org/765847

bindbapi.aux_update: fix spurious package file renames

---

lib/portage/tests/dbapi/test_auxdb.py
lib/portage/tests/emerge/test_simple.py
lib/portage/tests/process/test_AsyncFunction.py
lib/portage/tests/process/test_PipeLogger.py
lib/portage/tests/util/futures/asyncio/test_child_watcher.py
lib/portage/tests/util/futures/asyncio/test_subprocess_exec.py
lib/portage/tests/util/futures/test_retry.py
lib/portage/util/futures/compat_coroutine.py

The loop parameter is not needed since global_event_loop now
returns the running event loop for the current thread.
Bug: https://bugs.gentoo.org/737698
Bug: https://bugs.gentoo.org/763339

coroutine: do not require loop parameter

---

lib/portage/dbapi/bintree.py
lib/portage/emaint/modules/move/move.py
lib/portage/tests/update/test_move_ent.py

Copy on write when applying package moves, and silently
skip package moves when the same move has already been
applied to the same build of the package. Since the old
package instance is preserved, it avoids the problem
of having entries for deleted packages remain in the
package index. We can simply assume that the package
will be deleted by eclean-pkg when its time comes.
Bug: https://bugs.gentoo.org/766012

binarytree.move_ent: copy on write for package move

---

lib/portage/_emirrordist/FetchTask.py

When storing a cpv as a shelve value, convert _pkg_str to str
in order to prevent pickle problems.
Bug: https://bugs.gentoo.org/766459

emirrordist: prevent distfiles_db _pkg_str pickle problems

---

lib/portage/emaint/modules/merges/__init__.py
lib/portage/emaint/modules/merges/merges.py
man/emaint.1

Since the emaint --fix merges uses emerge --ask, add
a -y, --yes option to use --ask=n instead.
Bug: https://bugs.gentoo.org/766767

emaint --fix merges: add -y, --yes option

---

lib/_emerge/create_depgraph_params.py
lib/portage/tests/resolver/test_autounmask.py
man/emerge.1

Disable --autounmask-license by default, in order to limit user
exposure to risks associated with package.license changes.
The changes that this option suggests are only intended to be
accepted when a user has made a conscious decision to accept
the corresponding license(s). Creation of package.license
changes introduces a risk that users may erroneously accept the
changes due to some kind of accident or misunderstanding,
rather than due to conscious decisions about licenses.
These risks provide motivation to disable --autounmask-license
by default. The --autounmask-use option will remain as the
only autounmask option that is still enabled by default.
The unit tests demonstrate interactions between --autounmask
and --autounmask-license options. The --autounmask option
enables …

emerge: disable --autounmask-license by default

---

lib/portage/__init__.py

Call os.getpid() lazily, which eliminates getpid calls when possible
after os.fork() in the portage.process module.
Bug: https://bugs.gentoo.org/767913

portage.getpid: call os.getpid() lazily

---

.github/workflows/ci.yml
tox.ini

ci: upgrade to pypy-3.7-v7.3.3

---

lib/portage/_compat_upgrade/binpkg_multi_instance.py

Add a _compat_upgrade.binpkg_multi_instance script that the ebuild
can call in pkg_preinst in order to maintain a backward-compatible
FEATURES=-binpkg-multi-instance default on existing installs where
enabling binpkg-multi-instance could cause disruption.
Bug: https://bugs.gentoo.org/772785

make.globals: make FEATURES=-binpkg-multi-instance sticky for existing installs

---

lib/portage/_emirrordist/Config.py
lib/portage/_emirrordist/ContentDB.py
lib/portage/_emirrordist/DeletionIterator.py
lib/portage/_emirrordist/DeletionTask.py
lib/portage/_emirrordist/FetchTask.py
lib/portage/_emirrordist/main.py
lib/portage/package/ebuild/fetch.py
lib/portage/tests/ebuild/test_fetch.py
man/emirrordist.1

Add a --content-db option which is required for the content-hash
layout because its file listings return content digests instead of
distfile names.
All keys have a prefix separated by a colon. For digest keys, the
prefix is the hash algorithm name. For filename keys, the prefix is
"filename".
The value associated with a digest key is a plain filename. The
value associated with a distfile key is a set of content revisions.
Each content revision is expressed as a dictionary of digests which
is suitable for construction of a DistfileName instance.
Bug: https://bugs.gentoo.org/756778

emirrordist: add --content-db option required for content-hash layout (bug 756778)

---

lib/_emerge/create_depgraph_params.py
lib/portage/tests/resolver/test_useflags.py
man/emerge.1

If --binpkg-respect-use=y is given explicitly, then it implies
--autounmask-use=n, because these options naturally oppose
eachother.
Bug: https://bugs.gentoo.org/773469

emerge: make --binpkg-respect-use=y imply --autounmask-use=n

---

bin/chmod-lite
bin/ebuild-ipc
bin/ebuild-pyhelper

Merge the shell script wrappers for chmod-lite and ebuild-ipc
into a single ebuild-pyhelper script.

bin/ebuild-pyhelper: wrapper for portage python helpers

---

setup.py

Bug: https://bugs.gentoo.org/775053
Reported-by: Marien Zwart <marien.zwart@gmail.com>

setup.py: fix GLOBAL_CONFIG_PATH for prefix

---

lib/portage/eapi.py

Decorate eapi_* functions so that calls use _get_eapi_attrs(eapi)
to cache results.

_get_eapi_attrs: cache eapi_* function calls via decorator

---

repoman/cnf/qa_data/qa_data.yaml
repoman/cnf/repository/qa_data.yaml
repoman/cnf/repository/repository.yaml
repoman/lib/repoman/modules/linechecks/phases/__init__.py
repoman/lib/repoman/modules/linechecks/phases/phase.py
repoman/lib/repoman/tests/simple/test_simple.py
repoman/man/repoman.1

The variable.phase check is inspired by pkgcheck's VariableScopeCheck,
and uses essentially the same PMS data to drive the check.
References:
- https://projects.gentoo.org/pms/7/pms.html#x1-10900011.1
- https://pkgcore.github.io/pkgcheck/_modules/pkgcheck/checks/codingstyle.html#VariableScopeCheck
- https://bugs.gentoo.org/775191
Bug: https://bugs.gentoo.org/608664

repoman: add variable.phase check like pkgcheck VariableScopeCheck (bug 608664)

---

lib/portage/dispatch_conf.py
lib/portage/tests/__init__.py
lib/portage/tests/resolver/ResolverPlayground.py

Lazily evaluate cnf_* variables, allowing for mock portage.const
settings created by ResolverPlayground. In ResolverPlayground,
create symlinks for PORTAGE_BIN_PATH scripts inside the mock
EPREFIX, and restore portage.const.EPREFIX in the cleanup method.
Bug: https://bugs.gentoo.org/783957

tests: lazily evaluate cnf_* vars (bug 783957)

---

lib/_emerge/main.py
lib/portage/tests/emerge/test_simple.py

The included unit test case previously failed with this error:
emerge: error: unrecognized arguments: dev-libs/A
Bug: https://bugs.gentoo.org/784566

emerge: use parse_intermixed_args when available (bug 784566)

---

lib/portage/tests/__init__.py
repoman/lib/repoman/tests/__init__.py

This is mostly just a POC
While we don't have tests for the testing harness, it does successfully
test all the tests
Used pathlib docs as a reference for translation:
https://docs.python.org/3/library/pathlib.html#correspondence-to-tools-in-the-os-module
Signed-off-by: Marco Sirabella <marco@sirabella.org>

portage/tests: Use pathlib for path handling

---

bin/ebuild-ipc.py

Bug: https://bugs.gentoo.org/787563

ebuild-ipc: silently handle KeyboardInterrupt

---

man/make.conf.5

If PORTAGE_LOG_FILTER_FILE_CMD fails after exec, then output
will be lost. Therefore, suggest to use bash as a supervisor,
with fallback to cat.
Bug: https://bugs.gentoo.org/781854

make.conf.5: Suggest PORTAGE_LOG_FILTER_FILE_CMD supervisor for cat fallback (bug 781854)

---

.github/workflows/ci.yml
README
setup.py

```
* QA Notice: setuptools warnings detected:
*
*      Usage of dash-separated 'portage-ext-modules' will not be supported in future versions. Please use the underscore name 'portage_ext_modules' instead
```
Reported-by: Patrick McLean <chutzpah@gentoo.org>

setup.cfg: eliminate dash-separated portage-ext-modules

---

lib/_emerge/resolver/output_helpers.py

Sort USE flags in output by a combined sort that treats sequences
of digits as numbers and sorts them numerically rather than lexically.
As a result, python3_10 now sorts after python3_9.
Ideally, we'd just respect the order from profiles/desc but this should
work as an intermediate solution until we figure out how to implement
that.
Bug: https://bugs.gentoo.org/show_bug.cgi?id=788346
Signed-off-by: Michał Górny <mgorny@gentoo.org>

emerge: Sort USE flags in output using combined alnum sort

---

bin/phase-functions.sh
lib/portage/package/ebuild/prepare_build_dirs.py

Symlinking FILESDIR into the work tree has the unintended consequence
of preserving all original file metadata, including system-specific ACLs
and so on.  When these files are installed, this could lead to
unintentionally copying this metadata to the system and/or binary
packages.
Let's copy all files instead and drop metadata in the process.  Since
FILESDIR is expected to be small by design, this shouldn't cause any
major trouble.  It is also easier and less likely to cause regressions
than making sure stuff is not preserved when installing.
Unfortunately, a similar problem applies to DISTDIR.  However,
installing files from DISTDIR is rarer than from FILESDIR, so I guess
we'll cross that bridge when we get to it.
Bug: https://bugs.gentoo.org/814857
Signed-off-by: Michał Górny …

Copy files/* into the work tree instead of symlinking it

---

lib/portage/package/ebuild/prepare_build_dirs.py

Bug: https://bugs.gentoo.org/815196

prepare_build_dirs: apply permissions to filesdir

---

lib/portage/package/ebuild/prepare_build_dirs.py

Bug: https://bugs.gentoo.org/815871

prepare_build_dirs: handle copytree FileExistsError

---

bin/estrip

GDB loads debug files based on the file name given in the .gnu_debuglink
section, prepended with /usr/lib/debug/${dirname}, where dirname is the
absolute path to the parent directory of the binary being executed.
For each unique inode as input, we need a link to the debug file with
the GNU debuglink as its basename. A link to the debug file should exist
for each directory in which the input inode exists.
The debug link names should be based on the .gnu_debuglink value instead
of the name of the file we are processing as input.
The .gnu_debuglink value is based on the name of the first link
processed for each inode. We save this value as a symlink, and then read
it back as we process subsequent links.
For example, given the following input:
INODE PATH
1 /usr/bin/git
1 …

estrip: rework hard link logic in save_elf_debug

---

lib/portage/package/ebuild/fetch.py

Enable resume for the digestgen case (no digests available), when
the temporary file exceeds PORTAGE_FETCH_RESUME_MIN_SIZE. This
fixes a case which caused the ebuild digest command to skip the
download and fail with a message like this:
```
!!! File b'/var/cache/distfiles/foo.tar.xz' doesn't exist, can't update Manifest
```
Bug: https://bugs.gentoo.org/821571

fetch: enable resume for digestgen case

---

bin/ebuild-ipc.py
bin/phase-functions.sh
lib/_emerge/AbstractEbuildProcess.py
lib/_emerge/EbuildIpcDaemon.py
lib/portage/package/ebuild/prepare_build_dirs.py
lib/portage/tests/ebuild/test_doebuild_spawn.py
lib/portage/tests/ebuild/test_ipc_daemon.py

Move ipc files to a .ipc subdirectory, with a setgid bit to
prevent a lockfile group permission race. The lockfile function
uses an appropriate open call with mode argument so that the
lockfile is created atomically with both group ownership and
group write bit.
Bug: https://bugs.gentoo.org/468990

EbuildIpcDaemon: fix lock permission race

---

lib/portage/util/_dyn_libs/dyn_libs.py

Python's glob.glob() function follows symlinks recursively. Use
os.walk() instead.
Also re-order the operands to short-circuit the directory walk when
PROVIDES is not empty.
Bug: https://bugs.gentoo.org/826982
Fixes: cba2156dba89a22f2858238013469b4d80208854

portage/util/_dyn_libs/dyn_libs.py: fix symlink recursion issue

---

lib/portage/dbapi/bintree.py

Resolves an error when improperly named xpak files exist in PKGDIR.
Bug: https://bugs.gentoo.org/818886

dbapi: fix logic in bintree.binarytree._parse_build_id()

---

lib/_emerge/create_depgraph_params.py
man/emerge.1

Default emerge --ignore-soname-deps=n, in order to enable
soname dependencies by default. As always, soname dependencies
remain inapplicable in the absence of the --usepkgonly option
(or --getbinpkgonly). Therefore, this change only affects
commands that specify --usepkgonly or --getbinpkgonly.
Bug: https://bugs.gentoo.org/687956

emerge: Default enable soname dependencies (bug 687956)

---

src/portage_util_file_copy_reflink_linux.c

When copy_file_range copied zero bytes, fall back to sendfile,
so that we don't call copy_file_range in an infinite loop.
Bug: https://bugs.gentoo.org/828844
Tested-by: John Helmert III <ajak@gentoo.org>

file_copy: handle zero bytes copied by copy_file_range (bug 828844)

---

cnf/dispatch-conf.conf

If there are existing files in the archive directory, this may cause
conflicts with the files/directories managed using rcs.
Bug: https://bugs.gentoo.org/837533

dispatch-conf: add a warning about changing the use-rcs setting

---

lib/portage/dbapi/_MergeProcess.py
lib/portage/dbapi/vartree.py

Use an instance of multiprocessing.Pipe to propagate mtimedb["ldpath"]
from the MergeProcess child process to the parent process. This fixes
env_update calls to avoid unnecessary regeneration of ld.so.cache in
cases where mtimedb["ldpath"] has not changed since the last call to
env_update.
Bug: https://bugs.gentoo.org/836375

MergeProcess: propagate mtimedb["ldpath"] to parent process (bug 836375)

---

lib/_emerge/MiscFunctionsProcess.py

This avoids clobbering the main sandbox.log file when
"misc-functions.sh die_hooks" is invoked after an ebuild phase.
Signed-off-by: Mike Gilbert <floppym@gentoo.org>

MiscFunctionsProcess: use a separate SANDBOX_LOG

---

pylintrc

We have cyclic imports in Portage; pylint before 2.14.0 fails to find them.
Signed-off-by: Mike Gilbert <floppym@gentoo.org>

pylintrc: disable cyclic-import check

---

lib/portage/eapi.py

This ensures we don't accidentally break portage API consumers that fail
to configure the root logger before calling the portage API.
Bug: https://bugs.gentoo.org/838406

portage.eapi: remove debug logging statement

---

lib/portage/xml/metadata.py

brian@storm ~/Dev/git/gentoolkit $ equery u smartmontools
File "/home/brian/Dev/git/gentoolkit/bin/equery", line 44, in <module>
equery.main(sys.argv)
File "/home/brian/Dev/git/gentoolkit/pym/gentoolkit/equery/__init__.py", line 359, in main
loaded_module.main(module_args)
File "/home/brian/Dev/git/gentoolkit/pym/gentoolkit/equery/uses.py", line 341, in main
output = get_output_descriptions(pkg, global_usedesc)
File "/home/brian/Dev/git/gentoolkit/pym/gentoolkit/equery/uses.py", line 201, in get_output_descriptions
local_usedesc = pkg.metadata.use()
File "/usr/lib/python3.10/site-packages/portage/xml/metadata.py", line 337, in use
self._useflags = tuple(_Useflag(node) for node in iterate("flag"))
File …

xml.metadata.py: Fix gentoolkit traceback in _Useflag class

---

lib/portage/tests/resolver/ResolverPlayground.py

Closes: https://bugs.gentoo.org/861077

ResolverPlayground: unconditionally setup essential_binaries

---

lib/portage/dbapi/porttree.py

If porttrees is a generator object, the second pass will fail.
Bug: https://bugs.gentoo.org/865635
Fixes: 9e24d0143450628f334cdb62e579efafd1bfd2ba
Signed-off-by: Mike Gilbert <floppym@gentoo.org>

dbapi: avoid iterating porttrees twice in _set_porttrees()

---

lib/portage/checksum.py
lib/portage/tests/util/test_checksum.py

The modified code may discard the file size from the output, which is never desired.
Also, it calls remove on the object being iterated over, which is problematic.
Reverts: 18e5a8170c69aecd10f162918de571d85055ae81
Reported-by: Marek Behún

Revert changes to portage.checksum._apply_hash_filter

---

lib/portage/data.py

Fix the PORTAGE_USERNAME default for the case where the portage.settings attribute exists and PORTAGE_USERNAME is unset.
Fixes: 18e5a8170c69aecd10f162918de571d85055ae81
Bug: https://bugs.gentoo.org/873088

data.py: fix PORTAGE_USERNAME default (bug 873088)

---

lib/portage/tests/util/futures/test_retry.py

Bug: https://bugs.gentoo.org/850127

testOverallTimeoutWithException: handle TimeoutError

---

lib/_emerge/depgraph.py

Add lru_cache to speed up the running time of "Calculating
dependencies".
In a ChromeOS use case, this patch decreases the running time from
311s to 197s with almost no memory usage increase.
Bug: https://bugs.gentoo.org/883071
Signed-off-by: Pin-yen Lin <treapking@chromium.org>

Add caching to _slot_operator_check_reverse_dependencies

---

NEWS
bin/egencache
lib/portage/package/ebuild/doebuild.py
lib/portage/tests/resolver/ResolverPlayground.py

Remove logic to incoporate PREROOTPATH and ROOTPATH. I'm not sure where PREROOTPATH was ever used, and ROOTPATH has been deprecated in baselayout for a while.
Remove logic to add hard-coded directories like
${EPREFIX}/{,usr{,/local}/{sbin,bin}. Adding these paths is unnecessary if env.d or the calling environment have a valid PATH setting.
Add logic to ignore PATH from the calling environment if PATH is set in env.d. This ensures that packages can update PATH by installing files in /etc/env.d and this will work without having to restart Portage with an updated environment.
Bug: https://bugs.gentoo.org/607696
Bug: https://bugs.gentoo.org/693308
Bug: https://bugs.gentoo.org/888543

_doebuild_path: simplify logic used to set PATH

---

bin/ebuild-helpers/prepinfo
bin/ebuild-helpers/prepman
bin/misc-functions.sh

Deprecate `prepinfo` when called from an ebuild.
While at it, also deprecate `prepman`.

Inline prepinfo code in install_qa_check()

---

NEWS
bin/phase-helpers.sh

Check for proper end of string for all option names beginning with "with", "disable" or "enable".

econf: Match configure --help output better

---

bin/estrip
bin/misc-functions.sh

Otherwise it will output a deprecation warning. Instead, call estrip directly with the new --prepallstrip option.
This affects only EAPI 6 and earlier and does not change functionality.
Fixes: 63d6f2e8985de480c21a5c2f09bba1547c7de6b8

misc-functions.sh: Don't call the prepallstrip helper

---

NEWS
bin/ebuild-helpers/portageq
bin/phase-helpers.sh
bin/portageq-wrapper

Move the internal portageq wrapper script out of the ebuild-helpers directory. Call the new script from best_version and has_version in the case when IPC is disabled.
The goal is to ban portageq from the ebuild environment after some transition time.

portageq-wrapper: New wrapper script

---

NEWS
lib/portage/package/ebuild/doebuild.py
lib/portage/package/ebuild/fetch.py

Bug: https://bugs.gentoo.org/485100
Bug: https://bugs.gentoo.org/890812

Adjust write tests for DISTDIR and PORTAGE_TMPDIR to work with automount directories

---

src/portage_util_file_copy_reflink_linux.c

Avoids a compiler warning:
```
../src/portage_util_file_copy_reflink_linux.c: In function ‘_reflink_linux_file_copy’:
../src/portage_util_file_copy_reflink_linux.c:379:12: warning: ‘error’ may be used uninitialized [-Wmaybe-uninitialized]
379 |         if (!error && ftruncate(fd_out, offset_out) < 0)
|            ^
../src/portage_util_file_copy_reflink_linux.c:205:22: note: ‘error’ was declared here
205 |     int eintr_retry, error, fd_in, fd_out, stat_in_acquired, stat_out_acquired;
|                      ^~~~~
```

_reflink_linux_file_copy: initialize error to 0

---

NEWS
bin/emerge-webrsync
bin/save-ebuild-env.sh
lib/portage/package/ebuild/_config/special_env_vars.py
lib/portage/sync/syncbase.py

If `https_proxy` is also set in make.conf, pick that up so it's passed down to
wget.
Bug: https://bugs.gentoo.org/911629
Signed-off-by: Sam James <sam@gentoo.org>

emerge-webrsync: handle https_proxy too

---

NEWS
lib/portage/package/ebuild/fetch.py

When fetching layout.conf, we call fetch(try_mirrors=False) to force direct use of the primary URI being passed and ignore mirrors.
The force-mirror feature causes fetch to ignore the primary URI.
Ignoring both the primary URI and mirrors leads to an unfetchable file. Give precedence to the try_mirrors parameter since we really only set it to False when fetching layout.conf from a mirror.
Bug: https://bugs.gentoo.org/877793

fetch: ignore force-mirror feature when try_mirrors is false

---

lib/portage/util/_eventloop/asyncio_event_loop.py

Fixes this DeprecationWarning triggered by
lib/portage/tests/util/futures/asyncio/test_event_loop_in_fork.py:
```
lib/portage/util/_eventloop/asyncio_event_loop.py:138: DeprecationWarning: 'AbstractChildWatcher' is deprecated as of Python 3.12 and will be removed in Python 3.14.
class _ChildWatcherThreadSafetyWrapper(_AbstractChildWatcher):
```

Remove deprecated AbstractChildWatcher usage

---

lib/portage/versions.py

Fixes this DeprecationWarning triggered by
lib/portage/tests/versions/test_vercmp.py:
```
lib/portage/versions.py:82: DeprecationWarning: typing.re is deprecated, import directly from typing instead. typing.re will be removed in Python 3.12.
def _get_slot_re(eapi_attrs: _eapi_attrs) -> typing.re.Pattern:
```

Remove deprecated typing.re.Pattern usage

---

lib/portage/__init__.py
lib/portage/locks.py

This wrapper is obsolete since python 3.5 implemented EINTR retry in the standard library.
Bug: https://bugs.gentoo.org/525552

Remove obsolete _eintr_func_wrapper

---

lib/portage/util/_async/AsyncFunction.py
lib/portage/util/_async/ForkProcess.py

If the _run method is not implemented, then use a new
"target" constructor parameter like multiprocessing.Process.
Support "args" and "kwargs" constructor parameters as well.
If the _run method is implemented, then behave in a backward
compatible manner, and ignore the "args" and "kwargs" constructor
parameters which are used by the AsyncFunction subclass.
Migrate AsyncFunction to ForkProcess target parameter.

ForkProcess: Add target constructor parameter

---

lib/_emerge/SpawnProcess.py
lib/portage/tests/ebuild/test_ipc_daemon.py

Since fd_pipes is incompatible with the multiprocessing spawn start method, allow empty fd_pipes so that ForkProcess can inherit SpawnProcess and still be compatible with multiprocessing spawn.
Bug: https://bugs.gentoo.org/915128

SpawnProcess: Make fd_pipes optional

---

lib/portage/tests/process/test_AsyncFunction.py
lib/portage/util/_async/AsyncFunction.py

Since fd_pipes does not work with the multiprocessing spawn start method, AsyncFunction should use multiprocessing.Pipe instead.
Bug: https://bugs.gentoo.org/915136

AsyncFunction: Use multiprocessing.Pipe for compat with multiprocessing spawn

---

lib/portage/util/_async/FileCopier.py

FileCopier: multiprocessing spawn compat

---

lib/portage/util/_async/ForkProcess.py

ForkProcess: Warn if _run method is used

---

.github/workflows/ci.yml
NEWS
lib/portage/__init__.py
lib/portage/_sets/__init__.py
lib/portage/dbapi/vartree.py
lib/portage/gpkg.py
lib/portage/package/ebuild/doebuild.py
lib/portage/tests/dbapi/test_portdb_cache.py
lib/portage/tests/ebuild/test_fetch.py
lib/portage/tests/emerge/test_config_protect.py
lib/portage/tests/emerge/test_emerge_blocker_file_collision.py
lib/portage/tests/emerge/test_emerge_slot_abi.py
lib/portage/tests/emerge/test_simple.py
lib/portage/tests/resolver/ResolverPlayground.py
lib/portage/tests/sync/test_sync_local.py
lib/portage/tests/util/test_getconfig.py
lib/portage/xpak.py

When a UTF-8 locale, or UTF-8 mode is detected, set
portage.utf8_mode to True, and do not wrap file access
with _unicode_func_wrapper. This is intended to mitgate
issues with byte string handling in python libraries
like shutil, as reported in bug 914722.
This patch is intended to be a simple and minimal
implementation that can be optimized later through
the elimination of unecessary encoding/decoding.
The str() wrapping in the unit tests is for lazily
evaluated instances of lazy_value, which is used to
account for mock portage.const.EPREFIX values that
exist during unit tests.
Upgrade pypy unit tests from pypy-3.9 to pypy-3.10
in order to solve [unexplainable unit test failures that
only affected pypy-3.9](https://github.com/gentoo/portage/actions/runs/6463627312/job/17547082772).
Bug: …

Support Python UTF-8 Mode via portage.utf8_mode (bug 914722)

---

lib/_emerge/depgraph.py
lib/portage/dep/_slot_operator.py
lib/portage/tests/resolver/soname/test_skip_update.py

Compare package rebuilds/reinstalls to installed packages of the same
exact version, and eliminate unecessary rebuilds/reinstalls triggered
solely by the `@__auto_slot_operator_replace_installed__` set. This is
careful to obey the user's wishes if they have explicitly requested
for a package to be rebuilt or reinstalled for some reason.
The SonameSkipUpdateTestCase::testSonameSkipUpdateNoPruneRebuilds
test case shows that the new depgraph._eliminate_rebuilds method
eliminates a backtracking run that is needed for the
testSonameSkipUpdate test case to succeed via prune_rebuilds
backtracking which was added for bug 439688.
Bug: https://bugs.gentoo.org/915494

Detect and handle unnecessary package reinstall (bug 915494)

---

lib/portage/cache/mappings.py
lib/portage/tests/process/meson.build
lib/portage/tests/process/test_pickle.py

This improves compatibility with the multiprocessing spawn start method, by eliminating this error for MergeProcess:
```
AttributeError: Can't pickle local object 'slot_dict_class.<locals>.LocalSlotDict'
```
Bug: https://bugs.gentoo.org/915834

slot_dict_class: Make instances picklable

---

lib/portage/package/ebuild/doebuild.py

Bug: https://bugs.gentoo.org/915837

_post_src_install_uid_fix: Pass unicode to write_atomic for utf8_mode

---

lib/portage/dbapi/_MergeProcess.py
lib/portage/dbapi/vartree.py

Use multiprocessing.Pipe to decouple from the fd_pipes implementation since that currently only works for the multiprocessing "fork" start method.
Bug: https://bugs.gentoo.org/915903

MergeProcess: Use multiprocessing.Pipe to decouple fd_pipes

---

NEWS
bin/ebuild-helpers/portageq
bin/ebuild-helpers/prepallstrip
bin/ebuild-helpers/prepinfo
bin/ebuild-helpers/prepman
bin/ebuild-helpers/prepstrip
bin/estrip
bin/misc-functions.sh

Finally ban portageq, prepinfo, prepman, prepstrip and prepallstrip.
Closes: https://bugs.gentoo.org/899898
Closes: https://bugs.gentoo.org/906129
Closes: https://bugs.gentoo.org/906156

Ban non-PMS helpers

---

lib/portage/tests/process/test_ForkProcess.py
lib/portage/util/_async/ForkProcess.py

This new fd_pipes implementation is only enabled
when the multiprocessing start method is not fork,
ensuring backward compatibility with existing
ForkProcess callers that rely on the fork start
method.
Note that the new fd_pipes implementation uses a
thread via run_in_executor, and threads are not
recommended for mixing with the fork start method
due to cpython issue 84559.
Bug: https://bugs.gentoo.org/915896

ForkProcess: Implement fd_pipes via send_handle

---

lib/_emerge/Scheduler.py

Use `(pkg.cpv, pkg.root)` to lookup package
instances corresponding to die messages.
Bug: https://bugs.gentoo.org/915551

_emerge: Fix NameError 'pkg' bug 915551

---

lib/_emerge/SpawnProcess.py
lib/portage/tests/process/test_AsyncFunction.py
lib/portage/util/_async/ForkProcess.py

Bug: https://bugs.gentoo.org/916116

SpawnProcess/ForkProcess: pass stdin via fd_pipes if not background

---

lib/portage/dbapi/vartree.py

Bug: https://bugs.gentoo.org/916112

vardbapi.unpack_contents: Use multiprocessing.Pipe for spawn compat

---

lib/portage/dbapi/_MergeProcess.py
lib/portage/dbapi/bintree.py

Since QueryCommand._db does not propagate to the child process
in MergeProcess with the multiprocessing spawn start method,
handle it by passing QueryCommand._db as an explicit parameter.
Since self.mydbapi can be a bindbapi instance, override the
bindbapi `__getstate__` method so that it is picklable (omit
the unpicklable _aux_cache_slot_dict attribute and regenerate
it after unpickling).
Bug: https://bugs.gentoo.org/916106

MergeProcess: Support QueryCommand with spawn start method

---

lib/portage/package/ebuild/doebuild.py

Before it failed like this with the multiprocessing spawn start method:
```
AttributeError: Can't pickle local object 'doebuild.<locals>._fetch_subprocess'
```
Bug: https://bugs.gentoo.org/916139

doebuild: Make _fetch_subprocess compatible with spawn

---

lib/portage/dbapi/bintree.py

Both the `_aux_cache_slot_dict_cache` and `_instance_key` attributes are
unpicklable, so fix `__getstate__` to exclude them both from the state.
Override `__setstate__` to initialize _instance_key appropriately.
These changes prevent the following error:
```
AttributeError: Can't pickle local object 'slot_dict_class.<locals>.LocalSlotDict'
```
Fixes: b9a85ff987ea ("MergeProcess: Support QueryCommand with spawn start method")
Bug: https://bugs.gentoo.org/916106

bindbapi: Fix pickling for MergeProcess

---

lib/portage/__init__.py

Bug: https://bugs.gentoo.org/916149

create_trees: Handle bytes arguments for utf8_mode

---

lib/portage/_sets/files.py

Bug: https://bugs.gentoo.org/916182

StaticFileSet: Fix os.walk for utf8_mode

---

lib/_emerge/EbuildFetcher.py
lib/portage/tests/ebuild/test_fetch.py

Tested with this script:
```python
import contextlib
import multiprocessing
import unittest
from portage.tests.conftest import prepare_environment
from portage.tests.ebuild.test_fetch import EbuildFetchTestCase
if __name__ == "__main__":
multiprocessing.set_start_method("spawn", force=True)
with contextlib.contextmanager(prepare_environment.__wrapped__)():
unittest.main()
```

EbuildFetcher: multiprocessing spawn compat

---

lib/portage/sync/controller.py

Tested via lib/portage/tests/ebuild/test_fetch.py with bin/emerge patched to call:
multiprocessing.set_start_method("spawn", force=True)
Bug: https://bugs.gentoo.org/916231

SyncManager: multiprocessing spawn compat

---

lib/portage/dep/soname/SonameAtom.py

Do not pickle the SonameAtom _hash_value attribute, since hash() results are not meaningfully picklable.
Bug: https://bugs.gentoo.org/916248

SonameAtom: multiprocessing spawn compat

---

lib/portage/tests/dbapi/test_auxdb.py

Use staticmethod and functools.partial to avoid unpicklable local functions. Also, don't try to pickle anydbm or sqlite modules since they currently are not picklable. Ultimately, it might be a good idea to implement pickling for the sqlite module.
Bug: https://bugs.gentoo.org/916245

test_auxdb: multiprocessing spawn compat

---

lib/portage/cache/sqlite.py
lib/portage/tests/dbapi/test_auxdb.py

Override `__getstate__` to omit unpicklable attributes, and regenerate the unpicklable attributes after unpickling. Related test_auxdb update was in https://github.com/gentoo/portage/pull/1163.

sqlite: multiprocessing spawn compat

---

lib/portage/__init__.py

The multiprocessing.util.register_after_fork function is undocumented, so use the documented os.register_at_fork function instead.

Use documented os.register_at_fork function

---

NEWS
lib/_emerge/actions.py
lib/portage/dbapi/bintree.py
lib/portage/tests/dbapi/test_bintree.py
lib/portage/tests/emerge/test_actions.py

Trust helpers are likely to need privileges and it's a bit too far for pretend there, I think. People can run it manually if they want it done for them anyway.
We could check writable instead but I'd like to get a fix in for the regression first.
Bug: https://bugs.gentoo.org/915842

bintree: don't call trust helper with --pretend

---

lib/portage/tests/resolver/meson.build
lib/portage/tests/resolver/test_alternatives_gzip.py

Test bug 917259, where app-alternatives/gzip is upgraded before its pigz RDEPEND is installed. This is triggered when find_smallest_cycle selects a large cycle and the topological sort produces poor results when leaf_nodes returns app-alternatives/gzip as part of a large group of nodes. This problem might be solved by implementing a finer-grained ignore_priority for leaf_nodes calls.
Bug: https://bugs.gentoo.org/917259

Add test case to reproduce bug 917259

---

lib/_emerge/depgraph.py
lib/portage/tests/resolver/meson.build
lib/portage/tests/resolver/test_alternatives_gzip.py
lib/portage/tests/resolver/test_merge_order.py
lib/portage/tests/resolver/test_rebuild_ghostscript.py

Fix AlternativesGzipTestCase by increasing ignore_priority in
order to find smaller cycles. This causes some changes in merge
order for MergeOrderTestCase, but they appear to be acceptable
since they prevent temporarily unsatisfied RDEPEND by relying
on satisfied installed build-time dependencies.
Add a test case for [bug 690436](https://bugs.gentoo.org/690436), since the change to merge order
in MergeOrderTestCase is related (see commit 680276cc4d4f).
Bug: https://bugs.gentoo.org/690436
Bug: https://bugs.gentoo.org/917259

find_smallest_cycle: Increase ignore_priority to find smaller cycles

---

lib/_emerge/Scheduler.py

If there is a parallel-fetch task fetching a binpkg in the background, refer to emerge-fetch.log for status updates, just like the Binpkg class does prior to pkg_setup.
Bug: https://bugs.gentoo.org/760893

_run_pkg_pretend: Refer to emerge-fetch.log for binpkg parallel-fetch

---

lib/_emerge/depgraph.py
lib/portage/tests/resolver/test_rebuild_ghostscript.py
lib/portage/tests/resolver/test_runtime_cycle_merge_order.py

If gather_deps is traversing a cycle that is greater than or equal to the size of the current smallest_cycle, then abort early. Also abort early if we traverse a node encountered in a previous cycle for the same ignore_priority, since that means the two cycles are identical.
On my laptop, this brings the `emerge -pe @world` time down to 3m28.884s, compared to 10m44.268s with portage-3.0.55.
Bug: https://bugs.gentoo.org/918682

find_smallest_cycle: Optimize to traverse fewer nodes

---

lib/_emerge/Binpkg.py
lib/_emerge/CompositeTask.py
lib/_emerge/EbuildBuild.py
lib/_emerge/Scheduler.py

Cancel prefetchers that	have not started yet. This will cause the parallel-fetch SequentialTaskQueue to simply discard them, and a regular fetcher will be instantiated immediately. This prevents errors when accessing the pkg_path attribute of BinpkgPrefetcher instances that have not started yet.
Bug: https://bugs.gentoo.org/918636

Cancel prefetchers that have not started yet

---

lib/_emerge/depgraph.py

In order to avoid possibly merging a package too early, prefer installed leaves in runtime cycle topological sort. This fixes an AlternativesGzipTestCase failure that arose after 2e298ea7ba36 caused leaves to be selected in a slightly different order.
Bug: https://bugs.gentoo.org/917259

Prefer installed leaves in runtime cycle topological sort

---

lib/_emerge/depgraph.py
lib/portage/tests/resolver/test_merge_order.py

Since increasing ignore_priority can only lead to a larger selection of leaf nodes, there is no need to increase ignore_priority to search for smaller groups of leaf nodes.
It was the "only harvest one node at a time" part of commit 3487594cd8f4 that caused the test case to succeed.
Fixes: 3487594cd8f4 ("Increase ignore_priority during topological sort for runtime cycle")
Bug: https://bugs.gentoo.org/917259

Optimize runtime cycle ignore_priority leaf selection loop for topological sort

---

lib/_emerge/DepPriority.py

Since 2e298ea7ba36, the digraph.debug_print() output may not display runtime_slot_op when appropriate, since it relies on DepPriority sort order to determine which priority is most relevant to display. Adjust DepPriority sort order to account for this, which makes the debug output for AlternativesGzipTestCase display runtime_slot_op where appropriate:
```
runtime cycle digraph (9 nodes):
(app-alternatives/gzip-1:0/0::test_repo, ebuild scheduled for merge) depends on
(app-arch/pigz-2.8:0/0::test_repo, ebuild scheduled for merge) (runtime)
(sys-libs/zlib-1.3-r1:0/1::test_repo, ebuild scheduled for merge) depends on
(sys-devel/automake-1.16.5-r1:0/0::test_repo, installed) (buildtime)
(sys-devel/automake-1.16.5-r1:0/0::test_repo, installed) depends on
(dev-lang/perl-5.36.1-r3:0/0::test_repo, …
```

Account for runtime_slot_op in DepPriority sort for digraph.debug_print()

---

lib/portage/tests/ebuild/test_fetch.py

Bug: https://bugs.gentoo.org/919105

EbuildFetchTestCase: Fix dict/shelve key order assumption

---

lib/_emerge/resolver/circular_dependency.py

Treat soname deps as unconditional for now. In some
cases they can be avoided by a rebuild with changed
USE, but ebuilds sometimes do not specify the
corresponding conditional dependency (especially for
system packages like gcc which provides libstdc++.so.6
and libgcc_s.so.1).
Bug: https://bugs.gentoo.org/919311

circular_dependency: Handle SonameAtom

---

lib/_emerge/DepPriority.py
lib/_emerge/DepPriorityNormalRange.py
lib/_emerge/DepPrioritySatisfiedRange.py
lib/_emerge/UnmergeDepPriority.py
lib/_emerge/depgraph.py
lib/portage/tests/resolver/meson.build
lib/portage/tests/resolver/test_cross_dep_priority.py

When the dependency parent is for a cross root (ROOT != /) package, weaken _ignore_runtime in order to tolerate runtime cycles that are less problematic for cross root packages.
The included test case fails with this error without the fix:
```
* Error: circular dependencies:
(dev-libs/gmp-6.3.0:0/10.4::test_repo, binary scheduled for merge to '/tmp/tmp25nwdjn7/cross_root/') depends on
(sys-devel/gcc-13.2.1_p20230826:0/0::test_repo, binary scheduled for merge to '/tmp/tmp25nwdjn7/cross_root/') (runtime)
(dev-libs/gmp-6.3.0:0/10.4::test_repo, binary scheduled for merge to '/tmp/tmp25nwdjn7/cross_root/') (runtime_slot_op)
It might be possible to break this cycle
by applying the following change:
- dev-libs/gmp-6.3.0 (Change USE: -cxx)
```
Bug: https://bugs.gentoo.org/919174

DepPriority{Normal,Satisfied}Range: weaken _ignore_runtime for cross root

---

lib/portage/dbapi/bintree.py

The _pkg_str_aux_keys are used inside dbapi.update_ents,
and need to contain SIZE in order for the fakedbapi
_instance_key_multi_instance method to operate correctly.
Incorrect operation of _instance_key_multi_instance could
prevent binarytree.inject from removing an old instance
from its internal state. It could also trigger a KeyError
in bindbapi.aux_update as in bug 918597, since it could
cause binarytree.getname to return a non-existent path.
It could also cause binarytree.getname to return an
existing but incorrect path, which might trigger an
InvalidBinaryPackageFormat exception as in bug 906675.
Bug: https://bugs.gentoo.org/906675
Bug: https://bugs.gentoo.org/918597
Bug: https://bugs.gentoo.org/919668

bindbapi: add SIZE to _pkg_str_aux_keys

---

lib/portage/tests/dbapi/test_portdb_cache.py
lib/portage/tests/emerge/test_baseline.py
lib/portage/tests/emerge/test_config_protect.py
lib/portage/tests/emerge/test_emerge_blocker_file_collision.py
lib/portage/tests/emerge/test_emerge_slot_abi.py
lib/portage/tests/emerge/test_libc_dep_inject.py
lib/portage/tests/resolver/ResolverPlayground.py
lib/portage/tests/sync/test_sync_local.py

This ensures that CrossDepPriorityTestCase uses the correct python implementation when it calls emerge, by overriding behavior of `#!/usr/bin/env python` shebangs.
Fixes: 1d856747ada4 ("DepPriority{Normal,Satisfied}Range: weaken _ignore_runtime for cross root")

ResolverPlayground: Create $EPREFIX/usr/bin/python symlink

---

lib/_emerge/Scheduler.py

For completed tasks, reset current_task to None so that it does not cause the clean phase to execute with an invalid environment in the finally block.
Bug: https://bugs.gentoo.org/920258

Scheduler: Reset current_task in _run_pkg_pretend

---

lib/_emerge/depgraph.py
lib/portage/tests/resolver/soname/test_skip_update.py

The included test case will fail without strip_libc_deps because the "injected" >=sys-libs/glibc-2.37 dependency will be interpreted as a dependency change, triggering unwanted reinstall of app-misc/A-1.
Bug: https://bugs.gentoo.org/915494

depgraph: Use strip_libc_deps in _eliminate_rebuilds

---

lib/portage/dbapi/bintree.py
lib/portage/tests/update/test_move_slot_ent.py
lib/portage/tests/update/test_update_dbentry.py

When removing a signed gpkg in aux_update, update internal state including $PKGDIR/Packages (important especially for FEATURES=pkgdir-index-trusted).
Bug: https://bugs.gentoo.org/920095
Fixes: a7bbb4fc4d38 ("Fix move_ent with signed binpkg")

bindbapi: Update state for package remove in aux_update

---

lib/_emerge/actions.py
lib/portage/tests/resolver/test_depclean_order.py

Drop direct circular deps in the depclean merge order calculation, since it does not handle them well as shown by the test case for bug 916135 (https://github.com/gentoo/portage/pull/1147).
Bug: https://bugs.gentoo.org/916135

depclean: drop direct circular deps in merge order calculation

---

lib/_emerge/BinpkgFetcher.py
lib/portage/dbapi/bintree.py
lib/portage/tests/emerge/conftest.py
lib/portage/util/_async/AsyncTaskFuture.py

Add local file scheme support for binhost src-uri in bintree and BinpkgFetcher. Make BinpkgFetcher use a coroutine to avoid using callbacks. Add AsyncTaskFuture isAlive method that BinpkgFetcher can use to check FileCopier state. Add test command to test emerge -f --getbinpkgonly with local file scheme in binrepos.conf.
Also, fix the getbinpkgonly_fetchonly test command so that it does not rename binhost_dir to pkgdir. It seems like it should not do this, and it caused the getbinpkgonly_file_uri command to fail.
Bug: https://bugs.gentoo.org/920537

bintree: support file scheme for binhost src-uri

---

lib/_emerge/AbstractDepPriority.py
lib/_emerge/UnmergeDepPriority.py
lib/_emerge/actions.py
lib/_emerge/depgraph.py
lib/portage/tests/resolver/test_depclean_order.py

Increase priority of IDEPEND so that it is stronger than RDEPEND in unmerge order calculations. This causes IDEPEND to be unmerged afterwards when packages are involved in RDEPEND cycles.
Bug: https://bugs.gentoo.org/916135

depclean: Strengthen IDEPEND in unmerge order

---

lib/_emerge/Scheduler.py

This will handle the InvalidSignature exception that triggered bug 920258, allowing emerge --keep-going to skip the package if possible. All of the gpg stderr output is dumped before the exception is raised, as shown in [bug 920258 comment #0](https://bugs.gentoo.org/920258#c0).
Bug: https://bugs.gentoo.org/920258

Scheduler: Handle unpack_metadata SignatureException in _run_pkg_pretend

---

NEWS
bin/ebuild.sh

According to PMS and the Devmanual, only a single item is allowed as argument for addread, addwrite, adddeny and addpredict:
https://projects.gentoo.org/pms/8/pms.html#x1-12300012.3.3
https://devmanual.gentoo.org/function-reference/sandbox-functions/
Bug: https://bugs.gentoo.org/920654

ebuild.sh: Warn about colon-separated argument in sandbox functions

---

lib/portage/dbapi/__init__.py
lib/portage/dbapi/bintree.py
lib/portage/dbapi/vartree.py
lib/portage/exception.py
lib/portage/tests/update/test_update_dbentry.py

Raise a new CorruptionKeyError exception type instead of a plain KeyError when os.stat fails. Treat this type of exception as a warning during package moves.
Also fix this error that the test case triggered in the binarytree.remove method:
```
NameError: name 'binpkg_path' is not defined
```
Bug: https://bugs.gentoo.org/920828

dbapi: KeyError tolerance during package moves

---

lib/portage/gpkg.py
lib/portage/tests/update/test_move_ent.py

Bug: https://bugs.gentoo.org/920828
Thanks-to: Zac Medico <zmedico@gentoo.org>

gpkg: fix basename handling via aux_update

---

NEWS
lib/portage/dbapi/bintree.py

Followup to 6ae45739e208b7a9d59e0b6056be72a5791aae04. My qualm there wrt writable was whether or not doing something which mutated state (and therefore possibly the package list) would be confusing but that doesn't make much sense for a few reasons.
Anyway, change the test to be not just for no-pretend, but also whether the
bindb is writable too, as pretend is already a proxy for whether we may
not have privileges (I can imagine someone possibly having bindb privileges
but not /etc/portage/gnupg, so better to just head this off entirely).
Bug: https://bugs.gentoo.org/915842
Bug: https://bugs.gentoo.org/920180

bintree: don't call trust helper unless bindb is writable

---

lib/_emerge/actions.py
lib/_emerge/depgraph.py
lib/portage/tests/resolver/ResolverPlayground.py
lib/portage/tests/resolver/meson.build
lib/portage/tests/resolver/test_broken_deps.py

Add a dep_check action which can be used to check the
dependencies of all installed packages. The plan is for depgraph
to use this action to check for broken dependencies prior to the
merge order calculation. The new frozen_config parameter will
allow depgraph to pass a shared frozen config to _calc_depclean.
The result of the dep_check action becomes stale as soon as there
is any change to the installed packages. So, in order to account
for dependencies that may become broken or satisfied during the
process of updating installed packages, the merge order
calculation will need to refresh the dep_check calculation for
every merge order choice that it makes. This refresh will need
to be optimized to identify the portion of the graph that would
become stale due to a given change, so that it …

_calc_depclean: add dep_check action

---

cnf/make.globals
lib/_emerge/Scheduler.py
lib/portage/const.py
man/make.conf.5

Add a new merge-wait FEATURES setting, enabled by default, which prevents packages from being merged while other packages are building. Previously, this behavior was already implemented for packages that satisfy direct or indirect dependencies of the system set. This feature can be disabled only for other packages which do not satisfy direct or indirect dependencies of the system set, in order to trade the possibility of random build failures for greater parallelism.
Currently, it is known that having merge-wait disabled can cause "random" build failures for builds using setuptools when setuptools plugins are merged during the build.
Bug: https://bugs.gentoo.org/663324

Add merge-wait FEATURES setting enabled by default

---

lib/portage/dbapi/bintree.py

Ignore package moves for packages that raise SignatureException, just as they are ignored for packages that have a valid signature.
Bug: https://bugs.gentoo.org/922142

Handle SignatureException during package moves

---

lib/portage/tests/util/dyn_libs/meson.build
lib/portage/tests/util/dyn_libs/test_installed_dynlibs.py
lib/portage/util/_dyn_libs/dyn_libs.py

Resolve *.so symlinks to check if they point to regular files inside the top directory. If a symlink points outside the top directory then try to follow the corresponding file inside the top directory if it exists, and otherwise stop following.
Bug: https://bugs.gentoo.org/921170

installed_dynlibs: Resolve *.so symlinks

---

.github/workflows/lint.yml
.pre-commit-config.yaml

The versions must be consistent, since psf/black@stable now refers to 24.1.1 which triggers some reformatting relative to black 23.x.
The consistency should correct lint failures like this:
https://github.com/gentoo/portage/actions/runs/7667403073/job/20950314014?pr=1239
https://github.com/gentoo/portage/pull/1240 will migrate to black 24.1.x.

actions: Use psf/black@23.12.1 and sync pre-commit version

---

misc/emerge-delta-webrsync

The cd to TMPDIR before rsync was erroneously removed in commit fa0f8720e168c95bcd6a8bd57d5abf09c488fd32. Apparently this problem was not reported earlier because this code path only executes when tarsync is not installed, and the emerge-delta-webrsync postinstall suggests to install tarsync since version 3.7.3 released near the end of 2015.
Bug: https://bugs.gentoo.org/922923
Fixes: fa0f8720e168 ("emerge-delta-webrsync: handle gentoo-YYYYMMDD directory name")

emerge-delta-webrsync: cd to TMPDIR before rsync

---

lib/portage/process.py
lib/portage/tests/locks/test_lock_nonblock.py
lib/portage/util/locale.py

Because os.register_at_fork is used instead of multiprocessing.util.register_after_fork since commit cc7c40199850acb3d36f0a6452987231d592c360, we can rely on the _ForkWatcher hook being automatically invoked after os.fork().
Fixes: https://github.com/gentoo/portage/pull/1173

Rely on os.register_at_fork for _ForkWatcher hook invocation

---

lib/portage/process.py
lib/portage/tests/locks/test_lock_nonblock.py
lib/portage/util/locale.py

Since os.fork() is unsafe in threaded processes, add a basic
abstraction layer that will ultimately allow support of other process
cloning implementations.
Usage of os.fork() is now wrapped in a _start_fork function which can
easily be replaced with an alternative implementation.  This function
takes target, args, and kwargs arguments which are equivalent to
the corresponding multiprocessing.Process parameters. It also has
fd_pipes and close_fds parameters, since implementation of these is
dependent on the process cloning implementation.
The process cloning implementation does not need to be bothered with
the details of the _exec function, since spawn uses an _exec_wrapper
function as a target function which calls _exec and handles any
exceptions appropriately (special exception handling …

process.spawn: add abstraction layer for os.fork()

---

lib/portage/process.py
lib/portage/tests/process/meson.build
lib/portage/tests/process/test_spawn_returnproc.py

In order to migrate away from unsafe os.fork() usage in threaded processes (https://github.com/python/cpython/issues/84559), add a returnproc parameter that is similar to returnpid, which causes spawn to return a single Process object instead of a list of pids.  The Process API is a subset of asyncio.subprocess.Process. The returnproc parameter conflicts with the logfile parameter, since the caller is expected to use the fd_pipes parameter to implement logging (this was also true for the returnpid parameter).
In the future, spawn will return objects of a different type but with a compatible interface to Process, in order to encapsulate implementation-dependent objects like multiprocessing.Process which are designed to manage the process lifecycle and need to persist until it exits. …

process.spawn: Add returnproc parameter

---

lib/_emerge/EbuildMetadataPhase.py
lib/_emerge/SpawnProcess.py
lib/_emerge/SubProcess.py
lib/portage/package/ebuild/doebuild.py
lib/portage/process.py
lib/portage/util/_async/ForkProcess.py
lib/portage/util/_async/PopenProcess.py

Migrate SpawnProcess to use the spawn returnproc parameter, and make adaptations to descendent classes as needed. Introduce a portage.process.MultiprocessingProcess class for ForkProcess to wrap multiprocessing.Process instances, needed because ForkProcess inherits from SpawnProcess. Use portage.process.Process to wrap the pid in EbuildMetadataPhase, so that returnproc support in the doebuild function can be reserved for a later commit.

SpawnProcess: Use spawn returnproc parameter

---

lib/_emerge/SpawnProcess.py
lib/portage/process.py
lib/portage/tests/ebuild/test_doebuild_fd_pipes.py
lib/portage/tests/process/test_AsyncFunction.py
lib/portage/util/_async/ForkProcess.py

Use multiprocessing.Process for returnproc, so that fork will stop being used when python makes "spawn" the default multiprocessing start method.
Continue to use _start_fork when returnproc is not enabled, for backward compatibility. Ultimately, it can be removed at the same time as the returnpid parameter.

process.spawn: Use multiprocessing.Process for returnproc

---

lib/_emerge/EbuildMetadataPhase.py
lib/portage/package/ebuild/doebuild.py

Raise NotImplementedError if returnproc is enabled for anything other than the "depend" phase, since corresponding returnpid support has long been deprecated.

doebuild: Add returnproc parameter and deprecate returnpid

---

lib/portage/output.py
lib/portage/process.py

When set_term_size is called from an asynchronous context, we
can wait for the process to exit asynchronously. This will
prevent a "RuntimeError: This event loop is already running"
error in the future when synchronous spawn calls will need
to run the event loop in order to wait for the spawned
process(es).
Bug: https://bugs.gentoo.org/923750

set_term_size: Wait asynchronously if event loop is running

---

.github/workflows/ci.yml

Add multiprocessing start-method to matrix so that we are prepared for when python changes to default to spawn. Exclude all python versions except 3.12-dev for now.
This adds a conditional ci step that patches the sources just for the spawn start-method. It patches all bin/* scripts with python shebangs, and also patches the test command in meson.build.
@thesamesam this does something like what you suggested in https://github.com/gentoo/portage/pull/1249#issuecomment-1925460360. This implementation is kind of ugly, but maybe good enough for the first iteration. I've also added this to https://github.com/gentoo/portage/pull/1251.

actions: Add muliprocessing start-method to matrix

---

lib/_emerge/EbuildMetadataPhase.py
lib/_emerge/SpawnProcess.py
lib/portage/package/ebuild/doebuild.py
lib/portage/process.py
lib/portage/sync/modules/rsync/rsync.py
lib/portage/tests/util/futures/test_retry.py
lib/portage/util/_async/ForkProcess.py
lib/portage/util/futures/_asyncio/__init__.py
lib/portage/util/futures/executor/fork.py
lib/portage/util/socks5.py

Now includes a 3.12-dev ci job patched to set the multiprocessing start method to spawn, which took 7m 11s compared to 4m 16s for the 3.12-dev fork ci job.

Bug 916566 returnproc migration

---

lib/_emerge/EbuildMetadataPhase.py
lib/_emerge/EbuildPhase.py
lib/portage/package/ebuild/config.py
lib/portage/util/futures/_asyncio/__init__.py
lib/portage/util/locale.py

Since os.fork() is unsafe in threaded processes, use multiprocessing.Process instead. This way the fork will be eliminated when the default multiprocessing start method changes to "spawn".
Change config.environ() check_locale calls to async_check_locale calls in the EbuildPhase _async_start method in order to eliminate synchronous waiting for child processes in the main event loop thread.
Bug: https://bugs.gentoo.org/923841

check_locale: Call asynchronously in EbuildPhase

---

bin/quickpkg
lib/_emerge/actions.py
lib/portage/gpg.py
lib/portage/tests/gpkg/test_gpkg_gpg.py
lib/portage/tests/gpkg/test_gpkg_metadata_url.py

GPG: Proactively stop to avoid "GPG keepalive failed" error in pypy ci jobs
This seems to help mitigate pypy ci job hangs like those fba76a545f2 triggered.
Use threading.Event for thread safety during GPG stop, and use the wait method to improve responsiveness for stop requests.
Bug: https://bugs.gentoo.org/924192

GPG: Proactively stop to avoid "GPG keepalive failed" error in pypy ci jobs

---

lib/portage/dep/dep_check.py
lib/portage/tests/dep/test_overlap_dnf.py

Duplicate any-of blocks are eliminated since DNF expansion of duplicates is nonsensical.
Bug: https://bugs.gentoo.org/891137

_overlap_dnf: deduplicate any-of blocks

---

lib/_emerge/EbuildMetadataPhase.py
lib/_emerge/EbuildPhase.py
lib/portage/package/ebuild/config.py
lib/portage/util/futures/_asyncio/__init__.py
lib/portage/util/locale.py

This reverts commit c95fc64abf9698263090b3ffd4a056e989dd2be1 since we had assumed EbuildMetadataPhase._start would serialize access to the portdbapi doebuild_settings attribute, and that assumption broke when _async_start was introduced in order to call async_check_locale.
Bug: https://bugs.gentoo.org/923841
Bug: https://bugs.gentoo.org/924319

Revert "EbuildPhase: async_check_locale"

---

.github/workflows/ci.yml
lib/portage/tests/__init__.py
lib/portage/tests/env/config/test_PortageModulesFile.py
lib/portage/tests/news/test_NewsItem.py
lib/portage/tests/sets/files/test_config_file_set.py
lib/portage/tests/sets/files/test_static_file_set.py
lib/portage/tests/sets/shell/test_shell.py
lib/portage/tests/util/futures/test_retry.py

Use portage.test.TestCase setUp method to setup the multiprocessing start method if needed. It needs to be done relatively late in order to work with the pytest-xdist plugin due to execnet usage.

actions: Fix interaction between start-method and pytest-xdist

---

.github/workflows/ci.yml

https://github.com/gentoo/portage/pull/1265 triggered intermittent pytest-xdist worker crashes.
Bug: https://bugs.gentoo.org/924416

actions: disable pytest-xdist for spawn start-method (workers crash)

---

lib/portage/util/_async/BuildLogger.py

The _file_close_wrapper __getattribute__ method needs to be overridden to expose its close method, otherwise the underlying file's close method is called and the closed file object remains as a memory leak in the global portage.locks._open_fds dict. For reference, see similar classes like portage.util.atomic_ofstream which overrides methods in the same way.
Bug: https://bugs.gentoo.org/919072
Fixes:  https://github.com/gentoo/portage/pull/1199  df212738bbb2 ("BuildLogger: Close self._stdin after fork")
NOTE: This leak seems to be not much of a leak because the file descriptor numbers tend to recycle and kick the previous instances out of _open_fds.

BuildLogger: Fix portage.locks._open_fds memory leak

---

.github/workflows/ci.yml

Since pytest-xdist workers crash intermittently for the multiprocessing spawn start method, use pytest-rerunfailures to detect and handle this case. Only use pytest-rerunfailures for the spawn start-method since that is the only case where we've observed intermittent pytest-xdist worker crashes, and use `--only-rerun 'worker .* crashed while running'` to ensure that rerun only triggers for worker crashes.
Bug: https://bugs.gentoo.org/924416

actions: Use pytest-rerunfailures for pytest-xdist worker crash

---

lib/_emerge/EbuildMetadataPhase.py
lib/_emerge/EbuildPhase.py
lib/_emerge/MetadataRegen.py
lib/_emerge/SubProcess.py
lib/_emerge/depgraph.py
lib/portage/_emirrordist/FetchIterator.py
lib/portage/cache/anydbm.py
lib/portage/dbapi/porttree.py
lib/portage/package/ebuild/config.py
lib/portage/tests/dbapi/test_auxdb.py
lib/portage/tests/dbapi/test_portdb_cache.py
lib/portage/tests/resolver/ResolverPlayground.py
lib/portage/tests/update/test_move_ent.py
lib/portage/util/futures/_asyncio/__init__.py
lib/portage/util/locale.py

Change config.environ() check_locale calls to async_check_locale calls in the EbuildPhase/EbuildMetadataPhase _async_start method in order to eliminate synchronous waiting for child processes in the main event loop thread.
Note that this series of changes causes access to the portdbapi doebuild_settings attribute to no longer be serialized via the EbuildMetadataPhase _start method. As a result, exclusive access to config instances needs to be guaranteed in some other way to avoid triggering problems (see bug 924319), such as by maintaining a config pool or by serializing access via an asyncio.Lock instance.
Bug: https://bugs.gentoo.org/923841
Bug: https://bugs.gentoo.org/924319

EbuildPhase/EbuildMetadataPhase: async check_locale

---

bin/socks5-server.py
lib/portage/tests/util/test_socks5.py
lib/portage/util/futures/_asyncio/__init__.py
lib/portage/util/socks5.py

When called via the real asyncio.run implementation, wrap the running asyncio loop. Otherwise, it's not possible to call portage libraries via the real asyncio.run without triggering Future "attached to a different loop" errors.
Use real asyncio.run to demonstrate that it is compatible with portage internals. Since the socks5 ProxyManager uses the process.spawn function, the internal _running_loop function needs to return the correct loop for use in the wait method of MultiprocessingProcess, or else it will lead to Future "attached to a different loop" errors.
Bug: https://bugs.gentoo.org/761538

_get_running_loop: Support real asyncio.run

---

lib/portage/tests/emerge/conftest.py

Use emerge -e to fix this error we've seen since
https://github.com/gentoo/portage/pull/1272 92ff02b9189f for python 3.9 CI jobs:
https://github.com/gentoo/portage/actions/runs/8014796128/job/21893963019
```
test_portage_baseline[binhost emerge-gpkg] - AssertionError: 'emerge' failed with args '('-e', '--getbinpkgonly', 'dev-libs/A')'
```
```
emerge: there are no binary packages to satisfy "dev-libs/B[flag]". (dependency required by "dev-libs/A-1::test_repo" [binary]) (dependency required by "dev-libs/A" [argument])
```
Fixes: 92ff02b9189f ("emerge: Skip installed packages with emptytree in depgraph selection")
Bug: https://bugs.gentoo.org/651018
Also see https://github.com/gentoo/portage/pull/1277.

Fix python 3.9 CI jobs since 92ff02b9189f

---

lib/_emerge/PollScheduler.py
lib/_emerge/depgraph.py
lib/portage/dbapi/porttree.py
lib/portage/tests/ebuild/test_doebuild_spawn.py
lib/portage/tests/ebuild/test_ipc_daemon.py
lib/portage/util/_async/SchedulerInterface.py

This allows async_aux_get to easily verify the identity of the underlying loop so that this assertion will not fail:
```
_start_with_metadata
(settings.configdict["pkg"]["SRC_URI"],) = aux_get_task.future.result()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/site-packages/portage/dbapi/porttree.py", line 786, in async_aux_get
raise AssertionError(
AssertionError: async_aux_get called from thread <_MainThread(MainThread, started 281473559502880)> with loop <_emerge.Scheduler.Scheduler._iface_class object at 0xffff8e3a8840>
Terminated
```
Fixes: 389bb304abf5 ("async_aux_get: Use EbuildMetadataPhase deallocate_config future")
Bug: https://bugs.gentoo.org/925333

SchedulerInterface/PollScheduler: Add _loop property

---

lib/portage/process.py

Fix `unshare_*` variables to be False when the libc is missing, libc.unshare is missing, or libc.unshare fails.
Also, if socket.sethostname is missing then _exec2 needs libc for the network-sandbox sethostname call which is wrapped by a blanket Exception handler.
Fixes: 419cce79f908 ("process._exec: Use _start_fork for os.fork() error handling")
Bug: https://bugs.gentoo.org/925311

process.spawn: Fix logic for missing libc.unshare on musl

---

NEWS
lib/portage/dbapi/_MergeProcess.py
lib/portage/dbapi/_SyncfsProcess.py
lib/portage/process.py
lib/portage/util/_ctypes.py
lib/portage/util/locale.py

musl libc has no soname, which causes ctypes.util.find_library to fail. As a fallback, try to load "libc.so".

Add workaround for loading libc on musl

---

lib/_emerge/BinpkgFetcher.py
lib/_emerge/EbuildFetcher.py
lib/_emerge/SpawnProcess.py
lib/portage/output.py
lib/portage/util/_pty.py

Use the SpawnProcess _unregister method to handle async set_term_size results, avoiding possible messages like bug 925456 triggered:
[ERROR] Task was destroyed but it is pending!
Also update _BinpkgFetcherProcess and _EbuildFetcherProcess which inherit the _pty_ready attribute from SpawnProcess.
Fixes: f97e414ce980 ("set_term_size: Wait asynchronously if event loop is running")
Bug: https://bugs.gentoo.org/923750
Bug: https://bugs.gentoo.org/925456

SpawnProcess: Wait for async set_term_size

---

cnf/sets/portage.conf
lib/portage/tests/resolver/ResolverPlayground.py
lib/portage/tests/sets/base/test_variable_set.py

Bug: https://bugs.gentoo.org/919751

cnf: sets: Migrate @golang-rebuild to dev-lang/go

---

lib/_emerge/PackageMerge.py
lib/_emerge/Scheduler.py
man/make.conf.5

For system packages, always serialize install regardless parallel-install, in order to mitigate failures triggered by fragile states as in bug 256616. For other packages, continue to populate self._task_queues.merge, which will serialize install unless parallel-install is enabled.
Fixes: 825db01b91a3 ("Add merge-wait FEATURES setting enabled by default")
Bug: https://bugs.gentoo.org/256616
Bug: https://bugs.gentoo.org/925213

Scheduler: Support parallel-install with merge-wait

---

lib/portage/package/ebuild/doebuild.py
lib/portage/tests/ebuild/test_doebuild_fd_pipes.py

Call _setup_locale in order to prevent an AssertionError from config.environ() for the config phase (or any other phase for that matter).
For returnproc or returnpid assume that the event loop is running so we can't run the event loop to call _setup_locale in this case and we have to assume the caller took care of it (otherwise config.environ() will raise AssertionError).
Update DoebuildFdPipesTestCase to use EAPI 8 and test the pkg_config function with an ebuild located in /var/db/pkg just like emerge --config does. Set LC_ALL=C just before doebuild calls in order to try and trigger the config.environ() split_LC_ALL assertion.
Bug: https://bugs.gentoo.org/925863

doebuild: Call _setup_locale

---

lib/portage/elog/mod_custom.py
lib/portage/process.py
lib/portage/util/_eventloop/asyncio_event_loop.py

Since elog_process is typically called while the event loop is running, hold references to spawned processes and wait for them asynchronously, ultimately waiting for them if necessary when the AsyncioEventLoop _close_main method calls _async_finalize via portage.process.run_coroutine_exitfuncs().
ConfigProtectTestCase is useful for exercising this code, and this little make.globals patch can be used to test failure during finalize with this error message:
!!! PORTAGE_ELOG_COMMAND failed with exitcode 1
```diff
--- a/cnf/make.globals
+++ b/cnf/make.globals
@@ -144 +144,2 @@ PORTAGE_ELOG_CLASSES="log warn error"
-PORTAGE_ELOG_SYSTEM="save_summary:log,warn,error,qa echo"
+PORTAGE_ELOG_SYSTEM="save_summary:log,warn,error,qa echo custom"
+PORTAGE_ELOG_COMMAND="/bin/false"
```
Bug: …

elog/mod_custom: Spawn processes in background

---

lib/portage/package/ebuild/doebuild.py
lib/portage/tests/ebuild/test_doebuild_fd_pipes.py
lib/portage/tests/resolver/ResolverPlayground.py

Since configdict["pkg"]["USE"] may contain package.use settings from config.setcpv, it is inappropriate to use here (bug 675748), so discard it. This is only an issue because configdict["pkg"] is a sub-optimal place to extract metadata from. This issue does not necessarily indicate a flaw in the Package constructor, since passing in precalculated USE can be valid for things like autounmask USE changes.
Bug: https://bugs.gentoo.org/675748

_validate_deps: Discard configdict["pkg"]["USE"]

---

lib/portage/tests/util/test_socks5.py
lib/portage/util/_eventloop/asyncio_event_loop.py
lib/portage/util/socks5.py

Since commit c3ebdbb42e72 from https://github.com/gentoo/portage/pull/1295 the atexit_register(proxy.stop) call in the get_socks5_proxy function can accept a coroutine function to execute in run_coroutine_exitfuncs(), so convert the ProxyManager stop method to a coroutine and use run_coroutine_exitfuncs().
Bug: https://bugs.gentoo.org/925240

socks5: Use run_coroutine_exitfuncs()

---

lib/_emerge/SpawnProcess.py
lib/portage/util/_async/ForkProcess.py

When create_pipe=False support was added in commit e8b31c86eaed from https://github.com/gentoo/portage/pull/1253, a null input file descriptor was used for PipeLogger and BuildLogger instances. Optimize this away, eliminating the unnecessary loggers.
Fixes: e8b31c86eaed ("ForkProcess: Prevent redundant pipe and set_term_size recursion")

SpawnProcess: Optimize away null input for create_pipe=False

---

lib/portage/util/_urlopen.py

A hung urlopen call can cause emerge to produce no output when fetching binhost data.
Bug: https://bugs.gentoo.org/926221

util: set a timeout for urlopen calls

---

cnf/METADATA
meson.build

Install dist-info METADATA for pip to resolve dependencies:
```console
portage==3.0.63
```
Suggested-by: Eli Schwartz <eschwartz93@gmail.com>
Bug: https://bugs.gentoo.org/920330

meson.build: Install dist-info METADATA

---

bin/phase-functions.sh
lib/_emerge/EbuildPhase.py
lib/portage/package/ebuild/_config/special_env_vars.py

Record REPO_REVISIONS as a json object that maps repo name to revision for an ebuild's source repository and any repositories that eclasses were inherited from:
```console
$ cat /var/tmp/portage/sys-apps/portage-3.0.63/build-info/REPO_REVISIONS
{"gentoo": "34875e30e73e33d3597d1101cdf97dc22729b268"}
```
Ultimately the intention is to expose this information in binhost metadata so that clients can select consistent revisions of source repositories.
Bug: https://bugs.gentoo.org/924772

__dyn_install: Record REPO_REVISIONS in build-info

---

bin/ebuild

We don't implement merge-wait for the ebuild command, so discard it from FEATURES. This prevents premature WORKDIR removal (see https://github.com/gentoo/portage/pull/1302#issuecomment-1989714617).
Fixes: 8eb2502bf264 from https://github.com/gentoo/portage/pull/1302 ("phase-functions: prematurely delete WORKDIR if FEATURES=merge-wait")

bin/ebuild: Discard merge-wait from FEATURES

---

lib/_emerge/BinpkgPrefetcher.py

Since it is confusing when emerge exits due to an error that only shows in the fetch log, emit an eerror message when binarytree inject fails:
```
>>> Running pre-merge checks for sys-libs/glibc-2.38-r10
* Fetching in the background:
* /var/cache/binpkgs/sys-libs/glibc/glibc-2.38-r10-5.gpkg.tar.partial
* To view fetch progress, run in another terminal:
* tail -f /var/log/emerge-fetch.log
>>> Failed to emerge sys-libs/glibc-2.38-r10
* Messages for package sys-libs/glibc-2.38-r10:
* Binary package is not usable:
*      !!!
*      gpg: keyblock resource '/etc/portage/gnupg/pubring.kbx': No such file or directory
*     	[GNUPG:] ERROR add_keyblock_resource 33587281
*     	[GNUPG:] PLAINTEXT 74 0
*     	[GNUPG:] NEWSIG
*     	gpg: Signature made Wed 20 Mar 2024 10:34:45 PM CET
*     	gpg: …
```

BinpkgPrefetcher: Emit eerror message for binarytree inject failure

---

bin/install-qa-check.d/60bash-completion

This triggers unwanted warnings in at least two known cases.
Bug: https://bugs.gentoo.org/928599
Bug: https://bugs.gentoo.org/928869

Remove QA warning when no bash completions are found

---

lib/portage/binrepo/config.py
lib/portage/dbapi/bintree.py
man/portage.5

In order to allow consistent and reproducible dependency calculations during mixed source and binary updates, add a "frozen" binrepos.conf attribute which will freeze binrepo index updates and cause messsages to indicate that the repo is frozen rather than up-to-date:
Local copy of remote index is frozen and will be used.
This should only be set temporarily in order to guarantee consistent and reproducible dependency calculations for mixed binary and source updates.
Bug: https://bugs.gentoo.org/932739

binrepos.conf: Support "frozen" attribute

---

lib/portage/dbapi/bintree.py

I noticed that the remote index was rewritten with a new DOWNLOAD_TIMESTAMP even while frozen, and this patch fixed it.

binarytree: Rewrite remote index only on change

---

lib/portage/util/__init__.py

Bug: https://bugs.gentoo.org/851015

atomic_ofstream: Use mkstemp rather than getpid (pid namespace safety)

---

lib/portage/tests/util/meson.build
lib/portage/tests/util/test_atomic_ofstream.py
lib/portage/util/__init__.py

Handle OSError from mkstemp for (default) follow_symlinks mode, not following the symlink if necessary (the target's parent may not exist or may be readonly). This restores the fallback behavior that existed before the introduction of mkstemp in commit de19f3a7215d.
Handle missing _file and _tmp_name attributes during close. Also set the default file mode respecting umask if a previous file does not exist, which fixes the mode of CONTENTS files since mkstemp.
Fixes: https://github.com/gentoo/portage/pull/1334 de19f3a7215d ("atomic_ofstream: Use mkstemp rather than getpid (pid namespace safety)")

atomic_ofstream: fix follow_symlinks fallback and default file mode

---

bin/eapi.sh
bin/ebuild-helpers/dohtml

This was added because of a council decision 10 years ago: https://projects.gentoo.org/council/meeting-logs/20140909-summary.txt
It has outlived its usefulness since dohtml is banned in EAPI 7 and later.

eapi.sh: Drop ___eapi_has_dohtml_deprecated()

---

lib/portage/dbapi/_MergeProcess.py

It's required for FEATURES=*-backup.
Fixes: b9a85ff987ea ("MergeProcess: Support QueryCommand with spawn start method")
Bug: https://bugs.gentoo.org/933297

MergeProcess: Pass bintree to subprocess

---

lib/portage/gpkg.py

This attribute was previously initialized only
in an exception handler.
Fixes: b8c3f38ec5ee ("Add more error handling for binpkgs")
Bug: https://bugs.gentoo.org/933385

tar_stream_writer: Add missing error attribute

---

lib/_emerge/Scheduler.py
lib/_emerge/actions.py
lib/_emerge/depgraph.py
lib/portage/tests/util/test_mtimedb.py

In order to fix emerge --resume and --keep-going to make appropriate binary package selections, store a list of binpkgs in the resume data. By adding the data as a new key which older versions of portage will ignore, the extension is backward compatible.
Without this fix, emerge --resume and --keep-going make poor package selection choices which do not account for the --binpkg-respect-use option.
Bug: https://bugs.gentoo.org/933442

Add binpkgs info to mtimedb resume data

---

lib/portage/gpkg.py

This suppresses a DeprecationWarning triggered because the tarfile.data_filter will become the new default in python3.14. The fully_trusted filter should be suitable here because tar_safe_extract already performs security validation on tar members prior to extraction.
Bug: https://bugs.gentoo.org/933433
@syu-nya

tar_safe_extract: Use tarfile.fully_trusted_filter

---

NEWS
bin/ebuild.sh

See 69cac73ba0a7bcf2e2cff88c60d389895a550623.
globskipdots is a new option in bash-5.2 that is also default-on in that release. The default value is not gated by BASH_COMPAT (see bug #907061), hence we need to disable it for older Bashes to avoid behaviour changes in ebuilds and eclasses.
Bug: https://bugs.gentoo.org/907061

bin/ebuild.sh: disable globskipdots in Bash 5.2

---

NEWS
lib/portage/dbapi/vartree.py
lib/portage/util/movefile.py

See PMS section 13.4.1 (Rewriting):
Any absolute symlink whose link starts with D must be rewritten with the leading D removed. The package manager should issue a notice when doing this.
Bug: https://bugs.gentoo.org/934514

vartree, movefile: Warn when rewriting a symlink

---

src/portage_util__whirlpool.c

In 3.13 python extensions need to [declare support for GIL features](https://github.com/python/cpython/issues/116322), for example if they don't declare Py_MOD_GIL_NOT_USED then it will cause the GIL to be enabled even when python was launched in free-threaded mode.
This requires "multi-phase initialization" because `Py_mod_create` is incompatible with `m_slots`. There's a `PyUnstable_Module_SetGIL()` function that can be used with single-phase init, but it's an unstable API, so it's better to use multi-phase init. There's no need to use `PyModule_GetState()` because the whirlpool module has no mutable state.
Bug: https://bugs.gentoo.org/934220

Allow GIL to be disabled in whirlpool C extension

---

lib/_emerge/Binpkg.py
lib/_emerge/BinpkgFetcher.py
lib/_emerge/BinpkgPrefetcher.py
lib/_emerge/Scheduler.py
lib/_emerge/actions.py
lib/portage/binrepo/config.py
lib/portage/dbapi/bintree.py
lib/portage/versions.py
man/portage.5

Download packages to a custom location if it is configured in binrepos.conf, instead of PKGDIR. If a custom download location is not configured then inject downloaded packages into PKGDIR as usual.
The binarytree download_required method should now be used instead of the isremote method to check if download is required, since a remote package may or may not be cached in the custom location. The get_local_repo_location method should be used to check if there is a custom download location, and if there is then downloaded packages must not be injected into PKGDIR.
If any packages from a repo with a custom download location were injected into PKGDIR in the past, their identity will be recognized and will not be re-downloaded to the custom location.
Bug: https://bugs.gentoo.org/934784

binrepos.conf: Support custom download location

---

NEWS
lib/_emerge/EbuildFetcher.py
lib/portage/package/ebuild/fetch.py
lib/portage/tests/ebuild/test_fetch.py
lib/portage/tests/util/test_socks5.py

Fix _EbuildFetcherProcess to handle SIGTERM, so that FETCHCOMMAND processes will not be left running in the background:
* Convert the fetch function to an async_fetch coroutine function so that it can use asyncio.CancelledError handlers to terminate running processes.
* Use multiprocessing.active_children() to detect and terminate any processes that asyncio.CancelledError handlers did not have an opportunity to terminate because the exception arrived too soon after fork/spawn.
* Add unit test to verify that a child process is correctly killed when EbuildFetcher is cancelled, with short timeout in case it takes some time for the process to disappear.
Bug: https://bugs.gentoo.org/936273

_EbuildFetcherProcess: Handle SIGTERM

---

lib/portage/process.py
lib/portage/tests/__init__.py
lib/portage/tests/util/test_socks5.py
lib/portage/util/_async/ForkProcess.py
lib/portage/util/futures/_asyncio/__init__.py

Handle the case where the loop has not been explicitly closed before exit. In this case, run_exitfuncs previously tried to call coroutine functions as though they were normal functions, which obvously would not behave correctly.
Solve this problem by storing the coroutine functions in a separate _coroutine_exithandlers list that belongs exclusively to the run_coroutine_exitfuncs function, so that it is safe to close the loop and call run_coroutine_exitfuncs from inside a run_exitfuncs hook. A _thread_weakrefs_atexit hook already exists that will close weakly referenced loops. The _thread_weakrefs_atexit hook is now fixed to release its lock when it closes a loop, since the same lock may need to be re-acquired when run_coroutine_exitfuncs runs.
The included test case demonstrates that …

run_exitfuncs: Support loop close via hook

---

lib/portage/process.py
lib/portage/tests/util/test_socks5.py
lib/portage/util/_eventloop/asyncio_event_loop.py
lib/portage/util/futures/_asyncio/__init__.py

Since an API consumer can cause loops to be instantiated for non-main threads, support coroutine exitfuncs for each loop. The included Socks5ServerAtExitThreadedTestCase calls get_socks5_proxy from a non-main thread, and demonstrates that coroutine exitfuncs for the resulting non-main loop will reliably stop the socks5 proxy via atexit hook.
The _thread_weakrefs_atexit function will now make a temporary adjustment to _thread_weakrefs.loops so that a loop is associated with the current thread when it is closing. Also, the _get_running_loop function will now store weak references to all _AsyncioEventLoop instances it creates, since each has a _coroutine_exithandlers attribute that can be modified by atexit_register calls.
Bug: https://bugs.gentoo.org/937740

Support coroutine exitfuncs for non-main loops

---

bin/dispatch-conf

There is no need to use SHELL here, and this can actually cause problems when SHELL is set to "nologin" or "false".
Bug: https://bugs.gentoo.org/910560

dispatch-conf: ignore SHELL in spawn_shell

---

lib/portage/util/futures/_asyncio/__init__.py

Ultimately the loop arguments that necessitate the _wrap_loop function can be removed, because our aim since [bug 761538](https://bugs.gentoo.org/761538) should be to eliminate them. Meanwhile, we don't want _wrap_loop to return redundant AsyncioEventLoop instances if we can easily prevent it.
Therefore, use `_safe_loop(create=False)` to look up the AsyncioEventLoop instance associated with the current thread, and avoid creating redundant instances. This serves to guard against garbage collection of AsyncioEventLoop instances which may have _coroutine_exithandlers added by the atexit_register function since commit cb0c09d8cecb from [bug 937740](https://bugs.gentoo.org/937740).
If `_safe_loop(create=False)` fails to associate a loop with the current thread, raise an AssertionError for …

_wrap_loop: Prevent redundant AsyncioEventLoop instances

---

lib/portage/util/futures/_asyncio/__init__.py

Since commit cb0c09d8cecb, _get_running_loop can wrap loops from asyncio.run, so these loops need to be discarded if they've been closed.
Fixes: cb0c09d8cecb ("Support coroutine exitfuncs for non-main loops")
Bug: https://bugs.gentoo.org/938761
Bug: https://bugs.gentoo.org/761538

_safe_loop: Discard wrapped asyncio.run loop that was closed

---

lib/portage/util/futures/_asyncio/__init__.py

When a loop argument is not given, use the default asyncio sleep / ensure_future implementations and avoid unnecessary _wrap_loop usage.
Bug: https://bugs.gentoo.org/761538

asyncio: Use default sleep / ensure_future implementations when possible

---

NEWS
lib/portage/dbapi/bintree.py

For remote packages that reference source repos which do not exist locally, do not inject repo revisions.
Fixes: 5aed7289d516 ("bintree: Add REPO_REVISIONS to package index header")
Bug: https://bugs.gentoo.org/939299

binarytree: Fix _inject_repo_revisions to ignore remote packages

---

NEWS
lib/portage/gpkg.py

Symlinks size is already accounted for, so there is no need to account for the pointed to file.
Moreover, previous code failed to handle permission error when using ROOT= and having absolute symlinks pointing to running root.
Bug: https://bugs.gentoo.org/942512

gpkg: do not consider symlinks targets for size estimation

---

lib/_emerge/Scheduler.py
lib/portage/package/ebuild/doebuild.py

If we are running from source (git) or as a module installed via pip, we don't need to worry about overwriting the existing system install via an ebuild installation.

Skip self update logic when installation.TYPE != SYSTEM

---

lib/portage/repository/storage/hardlink_rcu.py
lib/portage/sync/modules/rsync/rsync.py
lib/portage/tests/sync/test_sync_local.py

DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
Beware that this may break interaction with gemato timestamps if they are not UTC aware:
```python
>>> datetime.datetime.now(datetime.UTC) - datetime.datetime.utcnow()
File "<stdin>", line 1, in <module>
TypeError: can't subtract offset-naive and offset-aware datetimes
```
Also at least python3.11 is required for the datetime.UTC alias for datetime.timezone.utc.

Fix deprecated datetime.datetime.utcnow() usage

---

NEWS
bin/misc-functions.sh

Fixes: 8ac72ee300c1 ("install_qa_check: prematurely delete WORKDIR if FEATURES=merge-wait")
Bug: https://bugs.gentoo.org/942760

install_qa_check: Fix noclean interaction with merge-wait

---

NEWS
bin/save-ebuild-env.sh

None of the functions added in EAPIs 6, 7 and 8 were filtered out.

save-ebuild-env.sh: Add functions from newer EAPIs to filter list

---

NEWS
bin/isolated-functions.sh

PMS says about eend: "Takes one fixed argument, which is a numeric return code, and an optional message in all subsequent arguments."
A QA notice was in place since commit 95cd9583d415 in 2021.
Bug: https://bugs.gentoo.org/703520

eend: Make missing argument an error

---

NEWS
lib/_emerge/JobStatusDisplay.py
lib/_emerge/Scheduler.py
lib/portage/output.py

Do not use curses in the get_term_size function, since curses caches the terminal width and does not account for resize.
Bug: https://bugs.gentoo.org/945382

Scheduler: Handle SIGWINCH for JobStatusDisplay

---

NEWS
bin/save-ebuild-env.sh
lib/portage/__init__.py
lib/portage/package/ebuild/_config/special_env_vars.py
lib/portage/package/ebuild/doebuild.py
man/make.conf.5

Allow the MAKEFLAGS environment variable to pass through, in case a centralized GNU Make POSIX Jobserver is available. In order to prevent persistence of this variable in environment.bz2, exclude it when the __save_ebuild_env --exclude-init-phases argument is given.
Ultimately we may want to add support for portage to parse MAKEFLAGS and use it to allocate job tokens in various circumstances. For example, emerge could allocate a job token for each job started for emerge --jobs. This would remove a job token from the pool that is available to nested make calls, but is reasonable because nested make calls will execute jobs serially when no jobserver tokens remain.
Bug: https://bugs.gentoo.org/692576

Pass through MAKEFLAGS and exclude from environment.bz2

---

lib/portage/output.py

Use curses if stdin is not a tty, since stty fails in this case with the following error:
stty: 'standard input': Inappropriate ioctl for device
Bug: https://bugs.gentoo.org/947282

get_term_size: Use curses if stdin is not a tty

---

NEWS
lib/portage/dbapi/bintree.py

Bug: https://bugs.gentoo.org/923530

binarytree.move_ent: Allocate path with binpkg_format

---

lib/portage/__init__.py

If we are running Portage from a git checkout but the git command is unavailable or broken, we never set the VERSION variable.

portage.VERSION: prevent infinite recursion when lazy loading

---

cnf/make.globals
lib/portage/package/ebuild/config.py

Intialize default PORTAGE_USERNAME and PORTAGE_GRPNAME for
privileged mode.

config: Initialize default PORTAGE_USERNAME and PORTAGE_GRPNAME

---

cnf/sets/portage.conf
lib/portage/_sets/dbapi.py
lib/portage/tests/sets/base/test_variable_set.py

sets: VariableSet: honour 'excludes'
This allows defining @golang-rebuild and @rust-rebuild in such a way that
dev-lang/go and dev-lang/rust (and -bin) are excluded, as users don't
usually want to rebuild the toolchain there, just packages affected
by static linking and such.
For VariableSet:
* Make 'excludes' do something for VariableSet where variable is *DEPEND:
operate on the actual *DEPEND match, not the package in question though.
I'm not convinced this is super-useful as it is, but I wanted to try
preserve 'excludes' semantics as it is for other variables than *DEPEND.
* Add 'excludes_output' which drops matches on the original package being
tested/filtered.
e.g.
variable = BDEPEND
includes = dev-lang/rust
excludes_output = dev-lang/rust
will include any package with dev-lang/rust …

sets: VariableSet: honour 'excludes'

---

NEWS
lib/portage/_global_updates.py

Fixes: b6a2901f66b6 ("Support cross-root package moves")
Bug: https://bugs.gentoo.org/953449

_global_updates: Skip if vardb lock raises PermissionDenied

---

lib/portage/package/ebuild/doebuild.py

The distcc masquerade directory was moved from for better upstream compat.
Bug: https://bugs.gentoo.org/650986

check for /usr/lib/distcc/bin or /usr/lib/distcc
