gentoo/portage

pym/portage/sync/modules/git/git.py
Fix updates to respect sync-depth (previously it was only respected for
clone operations). Since the default merge strategy typically fails when
the depth is not unlimited, use `git fetch` followed by `git reset --hard`.
X-Gentoo-Bug: 552814
X-Gentoo-Bug-url: https://bugs.gentoo.org/show_bug.cgi?id=552814
=> GitSync.update: respect sync-depth (bug 552814)

repoman/pym/repoman/modules/scan/depend/_depend_checks.py
X-Gentoo-bug: 591184
X-Gentoo-bug-url: https://bugs.gentoo.org/show_bug.cgi?id=591184
=> repoman: fix erroneous LICENSE.syntax (bug 591184)

pym/_emerge/Scheduler.py
Fix the _terminate_tasks method to purge unstarted tasks from
self._running_tasks, so that they don't keep the main loop
running indefinitely.
X-Gentoo-bug: 425554
X-Gentoo-bug-url: https://bugs.gentoo.org/show_bug.cgi?id=425554
=> Scheduler._terminate_tasks: purge _running_tasks (bug 425554)

pym/portage/_selinux.py
When selinux is not fully installed yet the getcon call can sometimes return
"kernel" instead of a correct triple (eg "root:sysadm_r:sysadm_t"). Catch the
IndexError and skip selinux initialization.
File "/usr/lib64/python2.7/site-packages/portage/util/_async/ForkProcess.py", line 45, in _spawn
rval = self._run()
File "/usr/lib64/python2.7/site-packages/_emerge/EbuildFetcher.py", line 172, in _run
allow_missing_digests=allow_missing):
File "/usr/lib64/python2.7/site-packages/portage/package/ebuild/fetch.py", line 520, in fetch
if _userpriv_test_write_file(mysettings, write_test_file):
File "/usr/lib64/python2.7/site-packages/portage/package/ebuild/fetch.py", line 134, in _userpriv_test_write_file
returncode = _spawn_fetch(settings, args)
File …
=> selinux: fix crash for invalid context

pym/portage/util/writeable_check.py
X-Gentoo-bug: 594284
X-Gentoo-bug-url: https://bugs.gentoo.org/show_bug.cgi?id=594284
=> writeable_check: handle mountinfo quirks (bug 594284)

pym/portage/locks.py
This is needed for Windows Subsystem for Linux (WSL), as well as
older versions of PyPy.
X-Gentoo-bug: 595146
X-Gentoo-bug-url: https://bugs.gentoo.org/show_bug.cgi?id=595146
@mpkh @kerframil @Sazpaimon
This fixes ipc!
=> locks: use fcntl.flock if fcntl.lockf is broken (bug 595146)

pym/portage/xml/metadata.py
Descriptions may exist for multiple languages, so ignore all except
the first description found for a particular value of restrict, so
that use.local.desc content is consistent.
X-Gentoo-Bug: 599060
X-Gentoo-Bug-URL: https://bugs.gentoo.org/show_bug.cgi?id=599060
=> parse_metadata_use: apply English language preference (bug 599060)

pym/_emerge/resolver/slot_collision.py
Report packages that need to be rebuilt in order to solve slot
conflicts, but cannot be rebuilt for some reason. The following
reasons will be detected:
* matched by --exclude argument
* matched by --useoldpkg-atoms argument
* ebuild is masked or unavailable
Example output:
```
!!! The slot conflict(s) shown above involve package(s) which may need to
!!! be rebuilt in order to solve the conflict(s). However, the following
!!! package(s) cannot be rebuilt for the reasons shown:
(sys-apps/less-480:0/0::gentoo, installed): ebuild is masked or unavailable
```
X-Gentoo-bug: 602964
X-Gentoo-bug-url: https://bugs.gentoo.org/602964
=> slot_conflict_handler: report packages that can't be rebuilt (bug 602964)

pym/portage/util/_dyn_libs/LinkageMapELF.py
When support for parsing ELF headers in order to compute multilib
category was added in commit f1c1b8a77eebf7713b32e5f9945690f60f4f46de,
the LinkageMapELF class was not updated to do the same for preserved
libraries. This has resulted in incorrect preserve-libs handling
as reported in bug 598080, for ABIs including x32 where the
_approx_multilib_categories mapping is insufficient. This patch fixes
LinkageMapELF to compute the multilib category for each preserved
library, in the same way as the _post_src_install_soname_symlinks
function, so that the LinkageMapELF.findConsumers method will operate
correctly with preserved libraries of all ABIs.
Fixes: f1c1b8a77eeb ("Generate soname dependency metadata (bug 282639)")
X-Gentoo-bug: 598080
X-Gentoo-bug-url: https://bugs.gentoo.org/598080
=> LinkageMapELF: compute multilib category for preserved libs (bug 598080)

repoman/man/repoman.1, repoman/pym/repoman/modules/scan/metadata/ebuild_metadata.py, repoman/pym/repoman/qa_data.py
X-Gentoo-Bug: 533554
X-Gentoo-Bug-URL: https://bugs.gentoo.org/533554
=> repoman: add HOMEPAGE.missingurischeme check (bug 533554)

bin/glsa-check
Merge patch from the gentookit repo:
https://gitweb.gentoo.org/proj/gentoolkit.git/commit/?id=d158f2e656bd72f01b72bb94cb734fb1021934b5
Author: Roland Hopferwieser <gentoo@int0x80.at>
X-Gentoo-bug: 400763
X-Gentoo-bug-url: https://bugs.gentoo.org/show_bug.cgi?id=400763
=> glsa-check: Apply list only affected versions patch from bug 400763

repoman/pym/repoman/modules/scan/ebuild/checks.py
Use a regular expression to detect line continuations, instead
of the unicode_escape codec, since the unicode_escape codec is
not really intended to be used this way.
This solves an issue with python3.6, where a DeprecationWarning
is triggered by ebuilds containing escape sequences, like this
warning triggered by a sed expression in the dev-db/sqlite
ebuilds:
DeprecationWarning: invalid escape sequence '\['
X-Gentoo-Bug: 610414
X-Gentoo-Bug-Url: https://bugs.gentoo.org/show_bug.cgi?id=610414
=> repoman: use regular expression to detect line continuations

pym/_emerge/depgraph.py, pym/portage/dbapi/vartree.py
X-Gentoo-bug: 591760
X-Gentoo-bug-url: https://bugs.gentoo.org/show_bug.cgi?id=591760
=> emerge: use asyncio interfaces for spinner during owner lookup (bug 591760)

pym/_emerge/UseFlagDisplay.py
Fix pkg_use_display to test if the prefixed flag is in use.force or
use.mask, rather than the unprefixed flag.
X-Gentoo-bug: 490562
X-Gentoo-bug-url: https://bugs.gentoo.org/show_bug.cgi?id=490562
=> pkg_use_display: show masked/forced state of USE_EXPAND flags (bug 490562)

pym/_emerge/AsynchronousLock.py, pym/portage/tests/locks/test_asynchronous_lock.py
Add an async_unlock method, in order to avoid event loop
recursion which is incompatible with asyncio.
X-Gentoo-bug: 614108
X-Gentoo-bug-url: https://bugs.gentoo.org/show_bug.cgi?id=614108
=> AsynchronousLock: add async_unlock method (bug 614108)

pym/portage/util/_eventloop/EventLoop.py
Guarantee that newly added idle_add/call_soon callbacks have an
opportunity to execute before the event loop decides to wait on
self._thread_condition without a timeout. This fixes a case where
the event loop would wait on self._thread_condition indefinitely,
even though a callback scheduled by the AsynchronousTask._async_wait
method needed to be executed first.
X-Gentoo-bug: 617550
X-Gentoo-bug-url: https://bugs.gentoo.org/show_bug.cgi?id=617550
=> Eventloop: fix deadlock involving idle_add/call_soon (bug 617550)

pym/_emerge/search.py
Weigh the similarity of category and package names independently,
in order to avoid matching lots of irrelevant packages in the same
category when the package name is much shorter than the category
name.
X-Gentoo-bug: 623648
X-Gentoo-bug-url: https://bugs.gentoo.org/show_bug.cgi?id=623648
=> fuzzy search: weigh category similarity independently (bug 623648)

pym/portage/util/digraph.py
Reported-by: Sergei Trofimovich <slyfox@gentoo.org>
@trofi
=> digraph.add: sort priorities with bisect.insort

src/portage_util_file_copy_reflink_linux.c
The sendfile *offset parameter refers to the input file offest, so
it cannot be used in the same way as the copy_file_range *off_out
parameter. Therefore, add sf_wrapper function which implements the
*off_out behavior for sendfile.
Also update cfr_wrapper so that it does not rely on the fd_in file
offset, and remove corresponding fd_in lseek calls which are no
longer needed.
The file offset of fd_in is now completely unused, except in the
plain read/write loop, where lseek is called prior to entering
the loop.
Bug: https://bugs.gentoo.org/635126
=> file_copy: use sendfile return value to measure bytes copied (bug 635126)

pym/portage/dbapi/vartree.py
When removing files from CONTENTS, also remove the corresponding
lines from NEEDED, so that they do not corrupt LinkageMap data
for preserve-libs.
Bug: https://bugs.gentoo.org/637284
=> vardbapi.removeFromContents: update NEEDED (bug 637284)

bin/doins.py, pym/portage/tests/bin/test_doins.py
Bug: https://bugs.gentoo.org/642632
=> bin/doins.py: implement install -p option (bug 642632)

pym/portage/dep/dep_check.py, pym/portage/tests/resolver/test_virtual_minimize_children.py
Prefer choices with fewer new slots, rather than choices with the lowest
total number of slots. This fixes a case triggered by the catalyst stage1
build, where paludis was selected to satisfy perl-cleaner dependencies
because that choice happened to have a smaller number of slots:
```
|| (
( sys-apps/portage app-portage/portage-utils )
sys-apps/pkgcore
sys-apps/paludis
)
```
Bug: https://bugs.gentoo.org/645002
Fixes: 9fdaf9bdbdf5 ("dep_check: use DNF to optimize overlapping virtual || deps (bug 632026)")
=> dep_zapdeps: prefer choices with fewer new slots (bug 645002)

pym/portage/tests/ebuild/test_ipc_daemon.py, pym/portage/util/_eventloop/EventLoop.py
Bug: https://bugs.gentoo.org/591760
=> EventLoop: implement call_later for asyncio compat (bug 591760)

pym/portage/tests/util/futures/asyncio/test_subprocess_exec.py, pym/portage/util/futures/unix_events.py
In python versions that support asyncio, this allows API consumers
to use subprocess.PIPE for asyncio.create_subprocess_exec() stdout
and stderr parameters.
Bug: https://bugs.gentoo.org/649588
.../util/futures/asyncio/test_subprocess_exec.py   |  30 ++++
pym/portage/util/futures/unix_events.py            | 157 ++++++++++++++++++++-
2 files changed, 184 insertions(+), 3 deletions(-)
=> Implement AbstractEventLoop.connect_read_pipe (bug 649588)

pym/_emerge/EbuildPhase.py
Use async_unlock to avoid event loop recursion, and AsyncTaskFuture
to fit the resulting future into the CompositeTask framework that
EbuildPhase uses.
Bug: https://bugs.gentoo.org/614108
=> EbuildPhase._ebuild_exit: use async_unlock (bug 614108)

pym/_emerge/BinpkgFetcher.py
In order to avoid event loop recursion, convert the
_BinpkgFetcherProcess.lock() method to an async_lock
method for use by BinpkgFetcher.
Bug: https://bugs.gentoo.org/614110
=> BinpkgFetcher: use async lock (bug 614110)

pym/portage/sync/modules/git/git.py
Fetch the upstream remote and use git merge to update the checkout
only after successful verification of the upstream head.
Suggested-by: Richard Freeman <rich0@gentoo.org>
Bug: https://bugs.gentoo.org/660372
=> GitSync: abort checkout for signature problem (bug 660372)

lib/portage/package/ebuild/config.py
Since RESTRICT="!test? ( test )" can be very useful within the context
of bug 663278, pass an appropriate uselist parameter to the RESTRICT
use_reduce call. Make self.configdict["features"]["USE"] independent
of IUSE and RESTRICT, so that the same value can be shared between
packages with different settings, which is important when evaluating
USE conditional RESTRICT. When the evaluated value of RESTRICT contains
"test", handle it like IUSE="-test", since features USE is independent
of RESTRICT.
Bug: https://bugs.gentoo.org/663278
=> Support !test? conditionals in RESTRICT (bug 663278)

repoman/lib/repoman/actions.py, repoman/lib/repoman/copyrights.py
Bug: https://bugs.gentoo.org/656698
=> repoman: regen thick manifest after copyright update (bug 656698)

lib/portage/util/ExtractKernelVersion.py
Use KeyValuePairFileLoader to parse the kernel config and report errors
without raising an exception. Silently handle empty settings like the
CONFIG_UEVENT_HELPER_PATH= setting that triggered the ParseError reported
in bug 673224.
Bug: https://bugs.gentoo.org/673224
=> ExtractKernelVersion: use KeyValuePairFileLoader (bug 673224)

lib/portage/sync/modules/rsync/rsync.py
Write temporary timestamp files in ${PORTAGE_TMPDIR}/portage,
since writing files directly in ${PORTAGE_TMPDIR} is generally
unexpected. Also, use the rsync --inplace option, since it's
writing to a temp file created in advance and the usersync
user does not necessarily have write access to the parent
directory.
Bug: https://bugs.gentoo.org/671808
Fixes: 3f7f72cf339d ("Bug #336503 - Use PORTAGE_TMPDIR for the emerge --sync server timestamp")
=> rsync: user ${PORTAGE_TMPDIR}/portage (bug 671808)

lib/portage/process.py
In order to prevent failed unshare calls from corrupting the state
of an essential process, validate the relevant unshare call in a
short-lived subprocess. An unshare call is considered valid if it
successfully executes in a short-lived subprocess.
Bug: https://bugs.gentoo.org/673900
=> process.spawn: validate unshare calls (bug 673900)

bin/socks5-server.py, lib/portage/tests/util/test_socks5.py, lib/portage/util/socks5.py
Bug: https://bugs.gentoo.org/604474
=> tests: add unit test for portage.util.socks5 (FEATURES=network-sandbox-proxy)

lib/portage/locks.py
Handle cases where a lock file on NFS has been removed by a concurrent
process that held the lock earlier. Since stat is not reliable for
removed files on NFS with the default file attribute cache behavior
('ac' mount option), create a temporary hardlink in order to prove
that the file path exists on the NFS server.
Bug: https://bugs.gentoo.org/636798
=> locks: handle lock file removal on NFS (bug 636798)

lib/portage/locks.py
Since hardlinks on sshfs do not have matching inode numbers, detect
this behavior and use a simple stat call to detect if lock_path has
been removed.
Bug: https://bugs.gentoo.org/678218
=> locks: handle sshfs hardlink inode numbers (bug 678218)

lib/portage/locks.py
Bug: https://bugs.gentoo.org/678278
=> locks: check for removed lockfile only if unlinkfile is True

bin/isolated-functions.sh, bin/phase-helpers.sh
Closes: https://bugs.gentoo.org/662468
=> Add bash ___is_indexed_array_var function (bug 662468)

repoman/lib/repoman/argparser.py
Bug: https://bugs.gentoo.org/686074
=> repoman: report error for unknown arguments (bug 686074)

lib/portage/process.py
Add _has_ipv6() function and use it in _configure_loopback_interface()
to decide whether to add an IPv6 address.
Bug: https://bugs.gentoo.org/691290
=> process: add _has_ipv6() function

lib/portage/repository/config.py, repoman/lib/repoman/modules/scan/metadata/restrict.py
Bug: https://bugs.gentoo.org/690786
=> repoman: support metadata/layout.conf restrict-allowed

lib/portage/repository/config.py
Bug: https://bugs.gentoo.org/690786
=> RepoConfig: add properties-allowed attribute

lib/portage/dbapi/vartree.py
Fix the dblink _find_libs_to_preserve method to ignore a dropped
non-soname symlink. For example, pam-1.3.1-r1 drops the non-soname
symlink named libpam_misc.so, and we don't want this to trigger
unnecessary preservation of the corresponding library, since the
corresponding libpam_misc.so.0 soname symlink and the hardlink
that it references are still provided by pam-1.3.1-r1.
Bug: https://bugs.gentoo.org/692698
=> preserve-libs: ignore dropped non-soname symlink (bug 692698)

bin/glsa-check
Bug: https://bugs.gentoo.org/693088
=> glsa-check: forward port remaining changes from gentoolkit (bug 693088)

lib/portage/package/ebuild/fetch.py, lib/portage/tests/ebuild/test_fetch.py
Fix cases here fetch assumes that DISTDIR is writable when it's actually
read-only. This preserves old behavior which allowed users to override
FETCHCOMMAND to fetch files on a remote system, even though DISTDIR is
locally mounted in read-only mode.
Bug: https://bugs.gentoo.org/220533
Fixes: ebbde237d33e ("fetch: atomic downloads (bug 175612)")
=> fetch: minimal skiprocheck fixes (bug 220533)

lib/portage/package/ebuild/fetch.py, lib/portage/tests/ebuild/test_fetch.py
Add a force parameter which forces download even when a file already
exists in DISTDIR (and no digests are available to verify it). This
avoids the need to remove the existing file in advance, which makes
it possible to atomically replace the file and avoid interference
with concurrent processes. This is useful when using FETCHCOMMAND to
fetch a mirror's layout.conf file, for the purposes of bug 697566.
Bug: https://bugs.gentoo.org/697566
=> fetch: add force parameter (bug 697566)

lib/_emerge/depgraph.py, lib/portage/tests/resolver/test_blocker.py
Bug: https://bugs.gentoo.org/689226
=> emerge --buildpkgonly: respect buildtime hard blockers

repoman/cnf/qa_data/qa_data.yaml, repoman/cnf/repository/qa_data.yaml, repoman/lib/repoman/modules/scan/depend/_depend_checks.py, repoman/lib/repoman/scanner.py, repoman/man/repoman.1
Bug: https://bugs.gentoo.org/702100
=> repoman: support profiles/package.deprecated (bug 702100)

.travis.yml
Bug: https://bugs.gentoo.org/575840
=> travis.yml: enable pypy3

.travis.yml, tox.ini
=> travis.yml: drop pypy and python 3.5

bin/socks5-server.py
https://bugs.gentoo.org/709334
=> bin/socks5-server.py: PEP 492 coroutines with async and await syntax

lib/_emerge/Scheduler.py
Use add_done_callback instead of addExistListener, in order to avoid
callback races like the SequentialTaskQueue exit listener race that
triggered bug 711322. The addExistListener method is prone to races
because its listeners are executed in quick succession. In contrast,
callbacks scheduled via add_done_callback are placed in a fifo
queue, ensuring that they execute in an unsurprising order.
=> Scheduler: use add_done_callback (bug 711322)

lib/_emerge/AsynchronousTask.py
Schedule exit listeners via call_soon, in order to avoid callback races
like the SequentialTaskQueue exit listener race that triggered bug
711322. Callbacks scheduled via call_soon are placed in a fifo queue,
ensuring that they execute in an order that is unsurprising relative to
other callbacks.
=> AsynchronousTask: schedule exit listeners via call_soon (bug 711322)

lib/portage/tests/emerge/test_simple.py
=> SimpleEmergeTestCase: test binhost support

lib/portage/package/ebuild/prepare_build_dirs.py
Apply secure PORTAGE_WORKDIR_MODE permissions to PORTAGE_BUILDDIR,
since the child directory ${D} and its children may have vulnerable
permissions as reported in bug 692492.
Bug: https://bugs.gentoo.org/692492
=> _prepare_workdir: apply PORTAGE_WORKDIR_MODE to PORTAGE_BUILDDIR (bug 692492)

repoman/lib/repoman/modules/vcs/git/changes.py
For files returned by git diff-index, call git update-index in order
to ensure that the index reflects the state on disk. This will prevent
incorrect assumptions in cases where the index is missing or stale for
some reason. Since repoman uses this information to decide when to
update copyright header dates, this can prevent spurious copyright
header updates.
Bug: https://bugs.gentoo.org/712106
=> repoman.modules.vcs.git.changes: reindex (bug 712106)

lib/portage/locks.py, lib/portage/tests/locks/test_lock_nonblock.py
Raise TryAgain if the current inode is already locked by the current
process, since in this case the lock will not behave as intended with
the default fcntl.lockf function. With the alternative fcntl.flock
function, TryAgain is raised earlier.
Bug: https://bugs.gentoo.org/714480
=> lockfile: raise TryAgain if inode is already locked

lib/portage/dbapi/_MergeProcess.py
Fix the MergeProcess _spawn method to call the superclass _spawn
method, in order to replace os.fork with multiprocessing.Process,
promoting a healthy state for the forked interpreter.
Bug: https://bugs.gentoo.org/730192
=> MergeProcess: replace os.fork with multiprocessing.Process (bug 730192)

lib/_emerge/EbuildFetcher.py
Since ForkProcess now receives process exit status in the
_proc_join_done method instead of the _async_waitpid_cb method,
_EbuildFetcherProcess needs to emit eerror messages there
instead.
Fixes: bde44b75407d ("ForkProcess: replace os.fork with multiprocessing.Process (bug 730192)")
Bug: https://bugs.gentoo.org/730192
=> _EbuildFetcherProcess: emit eerror for fetch failure in  _proc_join_done

lib/portage/util/_async/BuildLogger.py
Cleanup PipeLogger as quickly as possible, in order to prevent
access to unclosed logs.
=> BuildLogger: fix _cancel to cleanup PipeLogger quickly

lib/_emerge/SpawnProcess.py
Cleanup PipeLogger as quickly as possible, in order to prevent
access to unclosed logs.
=> SpawnProcess: fix _cancel to cleanup PipeLogger quickly

lib/portage/_sets/dbapi.py
Bug: https://bugs.gentoo.org/739908
=> ChangedDepsSet: use strip_slots function like --changed-deps (bug 739908)

lib/portage/const.py, lib/portage/sync/modules/mercurial/__init__.py, lib/portage/sync/modules/mercurial/mercurial.py, lib/portage/tests/sync/test_sync_local.py, man/portage.5
Bug: https://bugs.gentoo.org/644246
=> Add mercurial sync support

lib/portage/package/ebuild/config.py
Bug: https://bugs.gentoo.org/752147
=> make.conf: expand special *ROOT variables (bug 752147)

lib/portage/util/futures/_asyncio/__init__.py
In order to maintain compatibility with an API consumer thread which
has not instantiated an asyncio loop for the current thread prior
to calling the portage API, instantiate a loop on its behalf. Since
a ResourceWarning will be triggered if the loop has not been closed
before the process exits, add the loop to a WeakValueDictionary,
and close it if it still exists during exit for the current pid.
Fixes: cecd2f8a259c ("Use default asyncio event loop implementation in API consumer threads")
Bug: https://bugs.gentoo.org/758755
=> _safe_loop: instantiate asyncio loop for API consumer thread

.github/workflows/ci.yml, lib/portage/__init__.py, tox.ini
Bug: https://bugs.gentoo.org/763045
=> ci: enable repoman tests

lib/portage/util/_eventloop/asyncio_event_loop.py
Use a child watcher wrapper to deliver the callbacks via the
call_soon_threadsafe method, since documentation for the asycio
AbstractChildWatcher class says that callbacks must be thread
safe.
Bug: https://bugs.gentoo.org/764905
=> AsyncioEventLoop: wrap child watcher for thread safety (bug 764905)

repoman/lib/repoman/modules/scan/depend/profile.py
=> repoman: Use async and await syntax

lib/portage/repository/storage/hardlink_quarantine.py, lib/portage/repository/storage/hardlink_rcu.py, lib/portage/repository/storage/inplace.py, lib/portage/repository/storage/interface.py, lib/portage/util/futures/_sync_decorator.py
=> RepoStorageInterface: Use async and await syntax

lib/portage/package/ebuild/config.py
Discard parent profile USE from the expand_map variable before
it is used to evaluate a child profile. This prevents accidents
triggered by USE="${USE} ..." settings at the top of make.defaults
which caused parent profile USE to override parent profile
package.use settings.
Note that would be nice to guard the USE_EXPAND variables like
this too, but unfortunately USE_EXPAND is not known until after
make.defaults has been evaluated, so that will require some form
make make.defaults preprocessing.
Bug: https://bugs.gentoo.org/771549
=> make.defaults: prevent USE="${USE} ..." misbehavior

lib/portage/package/ebuild/fetch.py, lib/portage/tests/ebuild/test_fetch.py
The content-hash layout is identical to the filename-hash layout,
except for these three differences:
1) A content digest is used instead of a filename digest.
2) The final element of the path returned from the get_path method
corresponds to the complete content digest. The path is a function
of the content digest alone.
3) Because the path is a function of content digest alone, the
get_filenames implementation cannot derive distfiles names from
paths, so it instead yields DistfileName instances whose names are
equal to content digest values. The DistfileName documentation
discusses resulting implications.
Motivations to use the content-hash layout instead of the
filename-hash layout may include:
1) Since the file path is independent of the file name, file
name collisions cannot occur. …
=> Add content-hash distfiles layout

cnf/make.globals, lib/portage/tests/emerge/test_simple.py, man/make.conf.5
Bug: https://bugs.gentoo.org/715112
=> make.globals: default enable FEATURES=binpkg-multi-instance

bin/shelve-utils, lib/portage/tests/util/test_shelve.py, lib/portage/util/shelve.py
Bug: https://bugs.gentoo.org/721680
=> Add emirrordist shelve dump/restore (bug 721680)

lib/portage/util/bin_entry_point.py, setup.py
=> setup.py: add entry_points when installed with pip

repoman/lib/repoman/tests/simple/test_simple.py
=> SimpleRepomanTestCase: compare QATracker results to expected values

lib/_emerge/Scheduler.py
Bug: https://bugs.gentoo.org/787545
=> _run_pkg_pretend: raise asyncio.CancelledError when terminated

repoman/setup.py, setup.py
Bug: https://bugs.gentoo.org/794166
=> setup.py: prefer setuptools over distutils (bug 794166)

.github/workflows/ci.yml, tox.ini
Signed-off-by: Michał Górny <mgorny@gentoo.org>
=> ci: Test using the newest version of PyPy3.7

lib/portage/util/futures/extendedfutures.py
DeprecationWarning: There is no current event loop
=> ExtendedFuture: Fix python3.10 DeprecationWarning

lib/portage/sync/modules/git/git.py
While this doesn't solve the odd permissions issue for communication
b/t gemato & git & portage, it does stop it manifesting.
This fixes compatibility with >=dev-vcs/git-2.35.2.
Bug: https://bugs.gentoo.org/838223
Bug: https://bugs.gentoo.org/838271
=> git: mark repository as safe for newer gits

lib/portage/tests/ebuild/test_doebuild_fd_pipes.py, lib/portage/tests/ebuild/test_ipc_daemon.py, lib/portage/tests/util/futures/test_iter_completed.py
=> tests: Migrate to ForkProcess target parameter

lib/portage/util/_async/FileDigester.py
=> FileDigester: Migrate to AsyncFunction

lib/portage/dbapi/_SyncfsProcess.py
=> SyncfsProcess: Migrate to ForkProcess target parameter

lib/_emerge/EbuildFetcher.py
=> EbuildFetcherProcess: Migrate to ForkProcess target parameter

lib/portage/package/ebuild/_parallel_manifest/ManifestProcess.py
=> ManifestProcess: Migrate to ForkProcess target parameter

lib/portage/dbapi/_MergeProcess.py
=> MergeProcess: Migrate to ForkProcess target parameter

lib/portage/util/_eventloop/asyncio_event_loop.py
In case there are multiple loops running in different threads, use _ChildWatcherThreadSafetyWrapper. This partially reverts commit 690ac6e78c4099e83b84ef11c0b4064b077a8ef0.
Bug: https://bugs.gentoo.org/914873
=> AsyncioEventLoop: Put back _ChildWatcherThreadSafetyWrapper

lib/portage/dbapi/_MergeProcess.py
This improves compatibility with the multiprocessing spawn start method, by eliminating this error:
```
AttributeError: Can't pickle local object 'MergeProcess._start.<locals>.<lambda>'
```
=> MergeProcess: Eliminate target arguments that reference self

lib/portage/dbapi/vartree.py
This solves the following error with the multiprocessing spawn start method:
```
AttributeError: Can't pickle local object 'vardbapi.unpack_metadata.<locals>.async_copy'
```
Bug: https://bugs.gentoo.org/916108
=> vardbapi.unpack_metadata: Make compatible with spawn start method

bin/emaint
Bug: https://bugs.gentoo.org/916142
=> bin/emaint: Use __main__ for spawn compat

bin/ebuild
Bug: https://bugs.gentoo.org/916142
=> bin/ebuild: Use __main__ for spawn compat

bin/emerge
Bug: https://bugs.gentoo.org/916142
=> bin/emerge: Use __main__ for spawn compat

lib/portage/dbapi/__init__.py
Bug: https://bugs.gentoo.org/916235
=> dbapi: Make _iuse_implicit_cnstr picklable for spawn compat

lib/portage/process.py
Since ctypes objects are not picklable for the multiprocessing spawn start method, acquire them in the subprocess.
Bug: https://bugs.gentoo.org/916242
=> _unshare_validator: multiprocessing spawn compat

lib/portage/tests/ebuild/test_doebuild_fd_pipes.py
Use multiprocessing.Pipe for compatibility with the spawn start method. Also pass QueryCommand._db to the child process, like MergeProcess does.
Bug: https://bugs.gentoo.org/916247
=> test_doebuild_fd_pipes.py: multiprocessing spawn compat

lib/portage/tests/process/test_AsyncFunction.py
For compatibility with the multiprocessing spawn start method, we delay restoration of the stdin file descriptor, since this file descriptor is sent to the subprocess asynchronously.
Bug: https://bugs.gentoo.org/916601
=> testAsyncFunctionStdin: multiprocessing spawn compat

lib/_emerge/Scheduler.py
Bug: https://bugs.gentoo.org/917315
=> _emerge: Fix _failed_pkg cpv AttributeError

lib/portage/_global_updates.py
Also use bindbapi.writable attribute in case the
PKGDIR is missing for some reason.
Bug: https://bugs.gentoo.org/587088
=> _global_updates: Acquire global vardbapi lock

lib/_emerge/EbuildBinpkg.py
Capture stdout and stderr for logging during
binarytree inject, and set returncode to 1 when
inject fails and returns None.
Bug: https://bugs.gentoo.org/921089
=> EbuildBinpkg: Handle binarytree inject failure

lib/portage/emaint/modules/merges/merges.py
Bug: https://bugs.gentoo.org/921181
=> emaint: merges: fix TrackingFile for utf8_mode

lib/portage/dbapi/bintree.py
When allocating a local file name for a remote package,
prefer re-using the existing build id if the file name
is unused locally, in order to avoid unnecessary build
id incrementation triggered when the _max_build_id
method counts remote build ids. Use the same file name
reservation via open with O_EXCL which has been used
during build_id incrementation since fa901a6510c.
If the preferred path is not locally available, then
the value returned from binarytree inject calls will
need to be used as discussed in bug 921208. This will
be implemented in a separate patch.
Bug: https://bugs.gentoo.org/921208
=> binarytree: Avoid unnecessary build id incrementation

lib/_emerge/Binpkg.py, lib/_emerge/BinpkgPrefetcher.py, lib/_emerge/Scheduler.py
Capture stdout and stderr for logging purposes during binarytree inject calls (like https://github.com/gentoo/portage/pull/1221), and use the inject return value to report success or failure.
For failures prior to pkg_pretend, use an eerror/elog message to indicate that the binary package is not usable. Move corresponding elog_process call to a finally block so that it is called for all pkg_pretend failures.
Bug: https://bugs.gentoo.org/921327
=> binarytree: Handle inject failures

.git-blame-ignore-revs, .github/workflows/lint.yml, .pre-commit-config.yaml, lib/_emerge/AsynchronousTask.py, lib/_emerge/EbuildMetadataPhase.py, lib/_emerge/MergeListItem.py, lib/_emerge/PipeReader.py, lib/_emerge/SpawnProcess.py, lib/_emerge/depgraph.py, lib/_emerge/resolver/slot_collision.py, lib/portage/_emirrordist/DeletionIterator.py, lib/portage/_emirrordist/FetchIterator.py, lib/portage/_sets/libs.py, lib/portage/dbapi/porttree.py, lib/portage/dbapi/vartree.py, lib/portage/dep/__init__.py, lib/portage/package/ebuild/config.py, lib/portage/package/ebuild/doebuild.py, lib/portage/proxy/objectproxy.py, lib/portage/tests/ebuild/test_fetch.py, lib/portage/tests/process/test_AsyncFunction.py, lib/portage/util/_async/PipeLogger.py, lib/portage/util/_async/TaskScheduler.py, lib/portage/util/_dyn_libs/LinkageMapELF.py, lib/portage/util/file_copy/__init__.py, lib/portage/util/futures/_sync_decorator.py
Lint / pre-commit failures due to [inconsistent black versions](https://github.com/gentoo/portage/actions/runs/7667403073/job/20897151681?pr=1239) are already corrected by https://github.com/gentoo/portage/pull/1241.
=> */*: rerun black w/ 24.1.0

lib/_emerge/SpawnProcess.py, lib/portage/util/_async/ForkProcess.py
When process.spawn is updated to call ForkProcess
for bug 916566, it needs to avoid recursion via
set_term_size.
Bug: https://bugs.gentoo.org/923750
NOTE: This patch is also in https://github.com/gentoo/portage/pull/1251.
=> ForkProcess: Prevent redundant pipe and set_term_size recursion

lib/portage/gpkg.py
Do not kill tar_stream_reader instances if we can successfully close them, since that can trigger BrokenPipeError during self.proc.stdin.close() calls, and this state is best avoided because it's unclear how the caller should handle the error.
If a BrokenPipeError does occur then simply print a traceback and hope that the corresponding file descriptor is closed during garbage collection. Do not try to reverse the order of self.proc.kill() and self.proc.stdin.close() as in commit fba76a545f2 since that triggered pypy ci job hangs for which no reliable solution has been found so far.
Bug: https://bugs.gentoo.org/923368
=> gpkg: Less aggressive subprocess.Popen kill in order to avoid BrokenPipeError

lib/portage/_selinux.py, lib/portage/process.py
Local functions are unpicklable, which triggered this error
with the multiprocessing "spawn" start method:
```
AttributeError: Can't pickle local object 'spawn_wrapper.__call__.<locals>._pre_exec'
```
Bug: https://bugs.gentoo.org/924273
=> spawn_wrapper: Make pre_exec function picklable

lib/portage/tests/util/test_socks5.py, lib/portage/util/_eventloop/asyncio_event_loop.py, lib/portage/util/socks5.py
For the event loop running in the main thread, call process.run_exitfuncs() before close with the event loop running so that anything attached can clean itself up (like the socks5 ProxyManager for bug 925240). This is necessary because process.spawn uses the event loop to implement the new returnproc parameter related to bug 916566.
Bug: https://bugs.gentoo.org/925240
=> AsyncioEventLoop: Call process.run_exitfuncs() before close

bin/misc-functions.sh, lib/_emerge/EbuildBinpkg.py, lib/_emerge/EbuildPhase.py, lib/portage/dbapi/bintree.py
Bug: https://bugs.gentoo.org/712222
=> EbuildPhase/EbuildBinpkg: Ensure PKGDIR subdirectory permissions

bin/phase-helpers.sh
=> unpack: skip unrecognized file formats *silently*

lib/portage/process.py
Drop hooks inherited via fork because they can trigger redundant actions as shown in bug 937891. Note that atexit hooks only work after fork since issue 83856 was fixed in Python 3.13.
Bug: https://bugs.gentoo.org/937891
=> run_exitfuncs: Drop hooks inherited via fork

lib/portage/process.py, lib/portage/tests/util/futures/asyncio/test_policy_wrapper_recursion.py, lib/portage/util/_eventloop/asyncio_event_loop.py, lib/portage/util/futures/_asyncio/__init__.py, lib/portage/util/futures/unix_events.py
Bug: https://bugs.gentoo.org/941955
=> Handle python3.14 ChildWatcher changes

lib/portage/sync/modules/webrsync/webrsync.py
Bug: https://bugs.gentoo.org/945861
=> webrsync: Support sync-webrsync-verify-signature = false

NEWS, bin/fixpackages, lib/_emerge/actions.py, lib/portage/_global_updates.py, lib/portage/emaint/modules/sync/sync.py, lib/portage/tests/update/test_move_ent.py, lib/portage/tests/update/test_move_slot_ent.py, lib/portage/tests/update/test_update_dbentry.py
Bug: https://bugs.gentoo.org/946326
=> Support cross-root package moves

NEWS, lib/_emerge/actions.py, lib/portage/tests/ebuild/test_ipc_daemon.py, lib/portage/tests/locks/test_asynchronous_lock.py, lib/portage/tests/util/futures/test_retry.py
Bug: https://bugs.gentoo.org/904702
=> action_config: Call elog_process

bin/ebuild-helpers/fowners, bin/ebuild-helpers/fperms, bin/ebuild.sh
=> Drop qa warnings

lib/portage/dbapi/bintree.py
Bug: https://bugs.gentoo.org/948643
=> getname: Handle None remotepkgs

.github/workflows/ci.yml
Fixes: e18f0aab473b3bfaa4507bc600dcb27b23125d19
=> github ci: create gtar symlink
